INSERT INTO texts (name, text) VALUES ('tekst01.txt', '
Chętnie by miał jedną z nich. Ale nie było warto. Były tak ładnie szablonowe. Podobał mu się ten szablon. Był podniecający. Ale Krebs nie miał ochoty przechodzić przez to całe gadanie. Nie miał dość silnej ochoty na dziewczynę. Mimo to lubił na nie patrzeć. Tylko że nie było warto. Szczególnie teraz, kiedy wszystko zaczynało się znowu dobrze układać. Siedział na ganku i czytał książkę o wojnie. Była to praca historyczna i czytał o wszystkich walkach, w których brał udział. Uważał, że to najciekawsza lektura, jaką dotąd miał. Żałował, że nie ma tam więcej map. Z przyjemnością zapatrywał się na przeczytanie wszystkich naprawdę dobrych prac historycznych, kiedy ukażą się z dobrymi, szczegółowymi mapami. Teraz naprawdę dowiadywał się czegoś o wojnie. W swoim czasie był dobrym żołnierzem. A to było ważne.
');
INSERT INTO texts (name, text) VALUES ('tekst02.txt', '
Nie chciał też żadnej konsekwencji. Nie chciał nigdy więcej jakichkolwiek konsekwencji. Chciał sobie żyć bez nich. Poza tym w gruncie rzeczy nie potrzebował dziewczyny. Tego nauczyło go wojsko. Można było pozować na to, że musi się mieć dziewczynę. Prawie każdy to robił. Ale to nie była prawda. Nie potrzebowało się dziewczyny. To właśnie najśmieszniejsze. Najpierw ktoś się przechwalał, że dziewczyny nic dla niego nie znaczą, że nigdy o nich nie myśli, że wcale go nie obchodzą. Potem przechwalał się, że nie może sobie dać rady bez dziewczyn, że musi je mieć stale, że nie może bez nich zasnąć. To wszystko było kłamstwo. Kłamstwem było i jedno i drugie. Nie potrzebowałeś dziewczyny, jeśli o niej nie myślałeś. Tego nauczył się w wojsku.
');
INSERT INTO texts (name, text) VALUES ('tekst03.txt', '
Minął nas duży samochód jadący bardzo szybko i płachta błotnistej wody chlusnęła na naszą chłodnicę i przednią szybę. Automatyczne wycieraczki zaczęły poruszać się tam i z powrotem, rozprowadzając jej warstwę na szybie. Zatrzymaliśmy się w Sestri na obiad. Restauracja nie była ogrzewana i siedzieliśmy w paltach i kapeluszach. Przez okno widzieliśmy nasz wóz. Był pokryty błotem i stał przy jakichś łodziach, które wciągnięto na brzeg poza zasięg fal. W restauracji widziało się parę własnego oddechu. Pasta asciutta była dobra; wino miało posmak ałunu i dolaliśmy do niego wody. Później kelner przyniósł befsztyki z przysmażanymi kartoflami.
');
INSERT INTO texts (name, text) VALUES ('tekst04.txt', '
Doktor powiedział mi, że żona majora, która była bardzo młoda i z którą ożenił się dopiero wtedy, gdy jako inwalida został ostatecznie wyeliminowany z wojny, umarła na zapalenie płuc. Chorowała tylko kilka dni. Nikt się nie spodziewał, że umrze. Major przez trzy dni nie przychodził do szpitala. Potem zjawił się o zwykłej godzinie, z czarną opaską na rękawie munduru. Kiedy wrócił, na ścianach wisiały duże oprawione fotografie przedstawiające wszelkie rodzaje ran przed i po leczeniu za pomocą aparatów. Przed tym aparatem, którego używał major, były trzy fotografie kompletnie wyleczonych rąk, takich jak jego ręka. Nie wiem, skąd doktor je wziął. Zawsze słyszałem, że my pierwsi używaliśmy tych aparatów. Fotografie nie zrobiły większego wrażenia na majorze, bo tylko spoglądał przez okno.
');
INSERT INTO texts (name, text) VALUES ('tekst05b.txt', '
Jego twarz pokryła maska całkowitej, ostatecznej rozpaczy wynikającej z wiedzy, która przyszła za późno. Wielkie koło hamulcowe znajdowało się na swoim miejscu, po drugiej stronie wagonu, lecz nie trzymała go niczyja ręka. Zamiast niego, ręka ściskała otwartą Biblię, leżącą grzbietem do góry na podłodze. Sam Devlin, także grzbietem do góry, leżał obok swego prowizorycznego posłania. Między jego chudymi łopatkami sterczała rękojeść noża. Bellew odwrócił napiętą twarz i wpatrzył się tępo w ośnieżone sosny na poboczu toru, mijające go ze świstem z prędkością stu mil na godzinę. Przeżegnał się, choć nie robił tego od dzieciństwa, i strach zniknął z jego twarzy. Zastąpiła go rezygnacja - sierżant pogodził się z nieuchronną śmiercią.
');
INSERT INTO texts (name, text) VALUES ('tekst05.txt', '
Bellew dotarł do drzwi z tyłu wagonu i rozpaczliwie szarpnął za klamkę. Bez skutku - te drzwi również były zamknięte na klucz. Wyciągnął colta i strzelił, mierząc tuż powyżej i nieco z boku zamka. Strzelił cztery razy, nie przejmując się dwoma potencjalnie śmiercionośnymi rykoszetami, które z gwizdem przeleciały przez wagon - teraz groziło im już większe niebezpieczeństwo. Po czwartym strzale drzwi ustąpiły pod rozpaczliwym naciskiem jego dłoni. Wyskoczył na tylny pomost. Natychmiast odrzucił go podmuch wiatru, który osiągnął bez mała siłę huraganu, oraz wyjątkowo gwałtowny przechył wagonu. W ostatniej chwili oburącz przytrzymał się poręczy. Colt, którego ściskał w prawej ręce, wyleciał na pobocze, koziołkując w powietrzu. Sierżant zdecydował się na samobójcze ryzyko, lecz między samobójstwem a nagłą śmiercią z innych powodów nie ma istotnej różnicy.
');
INSERT INTO texts (name, text) VALUES ('tekst06.txt', '
Pułkownik Claremont, którego wybuchowy temperament często dawał o sobie znać, heroicznie starał się utrzymać go na wodzy. Była to jednak z góry przegrana walka. Pedantyczny i skrupulatny oficer, dla którego rozkaz i porządek dzienny były rzeczą świętą, nie znosił, kiedy coś mu zakłócało, a tym bardziej niweczyło raz powzięte plany. Dodając zaś do tego skrajną nietolerancję wobec głupoty i nieudolności, trudno się dziwić, że nie potrafił on znaleźć jakiegoś wentyla bezpieczeństwa, przez który mógłby dawać upust swojej jedynej wadzie, niegodnej tak oficera, jak mężczyzny. Stopniowe uwalnianie albo sublimacja gwałtownego - i gwałtownie narastającego - gniewu wywołanego frustracją w jego wypadku nie wchodziły w rachubę, mimo iż oscylująca wokół punktu wrzenia wściekłość nie wpływała najlepiej na jego ciśnienie.
');
INSERT INTO texts (name, text) VALUES ('tekst07b.txt', '
A jednak kolejny paradoks sprawił, że uratowały go potencjalnie śmiercionośne wentylatory. Bez namysłu, instynktownie, wyciągnął rękę i złapał za jeden z nich. Odniósł wrażenie, że coś wyrwało mu prawe ramię z barku, wentylator brutalnie wydarł się z jego uścisku, lecz szybkość, z jaką sunął, wyraźnie się zmniejszyła. Ponownie wyciągnął rękę. Znów przeszył go dojmujący ból, ale teraz już ślizgał się w tempie nieomal spacerowym. Zobaczył, że zbliża się trzecie i ostatni wentylator. Tym razem objął go oburącz i zacisnął lewą rękę na prawym nadgarstku. Czuł, że jakaś potężna siła znowu wyrywa mu prawe ramię, czyżby odrosło mu nowe? Ale trzymał się twardo. Zatoczył szeroki łuk, wypadając nogami poza dach. Ale trzymał się dalej. Wiedział, że musi coś zrobić, bo siły go opuszczają. Powoli, zmagając się z bólem, podciągnął się na środek dachu, doczołgał na tył wagonu i nie tyle zszedł, co spadł na pomost.
');
INSERT INTO texts (name, text) VALUES ('tekst07.txt', '
Widząc zbliżającą się gałąź sosny, nie wahał się ani chwili. Wiedział, że jeżeli nie zrobi tego teraz, prawdopodobnie nie zdobędzie się po raz drugi na tak samobójczy krok. Żeby złagodzić skutki zderzenia, cofnął się szybko, rozkładając szeroko ręce na wysokości piersi. Złapał gałąź oburącz i z przerażeniem stwierdził, że jest o wiele cieńsza niż przypuszczał - zmyliła go gruba warstwa śniegu. Gałąź ugięła się. Desperacko zarzucił na nią nogi i wisząc w ten sposób, szybował pół metra nad dachem. Zerknął w dół. Nieświadom niczego Carlos mignął mu zaledwie trzydzieści centymetrów pod plecami i zniknął z widoku. Deakin opuścił nogi i żłobiąc obcasami podwójny ślad na oblodzonym dachu, spoglądał do tyłu. Nagle puścił gałąź, wiedząc doskonale, że któryś ze sterczących wentylatorów może mu wypruć wnętrzności.
');
INSERT INTO texts (name, text) VALUES ('tekst08.txt', '
Jestem przekonany, że wszystkie te dobre uczynki mam do zawdzięczenia mojej taktyce niestosowania przemocy. Gdybym zabiegał o ponowne przyjęcie mnie do kasty, usiłował ją rozbić na poszczególne obozy lub zachował się prowokacyjnie wobec jej członków, ci z pewnością odwzajemniliby się w podobny sposób i zamiast szczęśliwie uniknąć burzy po przybyciu z Anglii, wpadłbym w sam wir rozagitowania, kto wie, czy nie uprawianego częściowo za moimi plecami. Mój stosunek do żony wciąż jeszcze nie był taki, jakiego pragnąłem. Nawet pobyt w Anglii nie uleczył mnie z zazdrości. Byłem w dalszym ciągu drobnostkowy i zazdrosny o byle co, a wszystkie moje najbardziej utajone pragnienia zostawały nie zaspokojone.
');
INSERT INTO texts (name, text) VALUES ('tekst09.txt', '
Któregoś dnia do kuwety stojącej w ciemni fotograficznej wpuściłem karpia. Wrzaski niczego nie podejrzewającej dziewczyny rozległy się na całą szkołę. Ten niewinny żarcik pociągnął za sobą śledztwo na wielką skalę. Reżyserowałem też bardziej wyrafinowane skecze. Pewnego razu zaaranżowałem gwałtowną sprzeczkę z Majewskim. Kłócąc się zawzięcie, zapomniawszy na pozór o bożym świecie, przeszliśmy korytarzem, następnie schodami w dół, aż dotarliśmy do gabinetu, gdzie urzędowała ułomna sekretarka rektora, Nina. Grupa kolegów, których wtajemniczyliśmy w sprawę, usiłowała nas rozdzielić, ale bez skutku.
');
INSERT INTO texts (name, text) VALUES ('tekst10.txt', '
Paryż jest miastem stworzonym dla spacerów. Podczas którejś z naszych nocnych przechadzek - wcześniej wkręciliśmy na studencką zabawę w Akademii Sztuk Pięknych - zabrałem Gesę, żeby pokazać jej Hale. Zaledwie o kilka minut od Luwru zapuściliśmy się w wąskie uliczki, zasłane liśćmi kapusty i odpadkami wszelkiego rodzaju jarzyn. Widząc niewielkie na pozór, stłoczone stragany, sklepy i magazyny, trudno było uwierzyć, że stąd rozprowadza się niemal całą żywność dla Paryża i północnej Francji. Kierowca, który dotrze nocą w głąb Hal, może uważać się za szczęściarza, jeśli przed świtem uda mu się wydostać z labiryntu ciężarówek wiozących wszelkiego rodzaju bogactwa: od połci wołowiny do homarów i kręgów żółtego sera.
');
INSERT INTO texts (name, text) VALUES ('tekst11.txt', '
Pod jednym względem książka nie odpowiadała mi: byłem agnostykiem - w równym stopniu nie wierzyłem w szatana jako wcielenie zła, co w uosobienie Boga. Cały pomysł "Dziecka Rosemary" kłócił się z moją racjonalną wizją świata. Aby więc film stał się wiarygodny, postanowiłem zastosować pewien wybieg: dopuścić interpretację, że nadprzyrodzone przeżycia Rosemary są wytworem jej wyobraźni. Cała historia oglądana z jej punktu widzenia mogła wydawać się jedynie ciągiem koszmarnych zbiegów okoliczności, produktem rozgorączkowanej wyobraźni bohaterki. Knowania sąsiadów, sabat czarownic, w czasie którego, w obecności męża, szatan bierze ją przemocą oraz końcowa scena przy kołysce musiały mieć racjonalne wytłumaczenie. Oto dlaczego przez cały film rozmyślnie przewija się nić dwuznaczności.
');
INSERT INTO texts (name, text) VALUES ('tekst12b.txt', '
Kiedy już było po wszystkim, ja i moja partnerka ubraliśmy się i siedząc na dwóch taboretach, gwarzyliśmy dopijając szampana. Tymczasem sala opustoszała. Opuszczono kurtynę, ostatni klienci wyszli, a obsługa ustawiała krzesła na stolikach. Orkiestra usadowiła się wówczas tuż pod naszą lożą i muzycy zagrali wiedeńskiego walca, śląc w naszą stronę tęskne spojrzenia. "Król Pralni" nonszalancko sięgnął do kieszeni, wyciągnął gruby plik stuszylingowych banknotów i rozrzucił je dostojnym gestem siewcy. Poszybowały ku muzykom, jak jesienne liście. Zbierali je dyskretnie, nie uroniwszy ani jednej nuty.
');
INSERT INTO texts (name, text) VALUES ('tekst12.txt', '
Po odkorkowaniu szampana osobnik dyskretnie się wycofał. Wówczas dziewczyna zrzuciła z siebie ubranie i została tylko w pantoflach na wysokim obcasie, czarnych siatkowych pończochach i podwiązkach: wyglądała jak postać z rysunku Kokoschki. Kiedy mnie rozbierała, zerknąłem, co się dzieje na dole. Prestidigator z niezwykłą zręcznością prezentował swój numer. Panienka z równą wprawą wyczarowała prezerwatywę i szybko mi ją nałożyła. Potem golnąwszy sobie szampana siadła na mnie okrakiem i zabrała się do roboty. Zużytą prezerwatywę wrzuciła do kubełka z szampanem. Zachowałem gdzieś w pamięci mglisty obraz nagiego Sama goniącego po lożach równie nagą dziewczynę.
');
INSERT INTO texts (name, text) VALUES ('tekst13.txt', '
Coraz bardziej nienawidził tego Pope. Człowiek może się uśmiechać, a być łajdakiem. Bezlitosnym, zdradliwym, wszetecznym, zepsutym łajdakiem. Co właściwie znaczą te słowa? Miał tylko niejasne pojęcie. Ale ich czar był silny, szumiały mu w głowie, i zdało mu się, że dotychczas nie czuł do Pope prawdziwej nienawiści; nigdy dotąd nie nienawidził go tak naprawdę, bo nigdy dotąd nie umiał wypowiedzieć, jak bardzo go nienawidzi. A teraz miał już te słowa, słowa jak bębny, jak śpiew i zaklęcia. Te słowa i dziwna, dziwna opowieść, z której pochodziły (nie potrafił zebrać jej w całość, ale i tak była cudowna, cudowna), pozwoliły mu nienawidzić Pope; uczyniły tę nienawiść bardziej realną; nawet samego Pope uczyniły bardziej realnym.
');
INSERT INTO texts (name, text) VALUES ('tekst14.txt', '
Złapałem znów za plazmówkę i bez ceregieli wbiłem mu widelcowate zakończenie lufy prosto w serce (to znaczy tam, gdzie wydawało mi się, że ono jest). Aby dobić go zupełnie, wystrzeliłem. Tym razem zaskoczył mnie całkowicie; zamiast osunąć się martwym na ziemię, zaczął miotać się na wszystkie strony jak szaleniec. Zżerająca go od środka plazma wydawała jakby zagęszczony dźwięk ton zgniatanego papieru. W pewnym momencie pomyślałem nawet, że wybuchnie i jakież było moje zdziwienie, gdy tak właśnie się stało: powietrze przeszył głośny huk, i cała górna część jego ciała znikła w kłębach żółtego pyłu. Dolna padła na ziemię jak kawał czarnego płótna. Ciągnąc za sobą warkocz dymu, coś zwęglonego spadło tuż pod moje stopy i poturlało się jeszcze przez kilka metrów. To musiała być jego czaszka.
');
INSERT INTO texts (name, text) VALUES ('tekst15.txt', '
Liu Kang wracał późnym wieczorem do mieszkania położonego na przedmieściu Nowego Jorku. Wybrał tę okolicę specjalnie po to, aby w wolnych chwilach móc bez obaw poćwiczyć. Nie wszyscy sąsiedzi lubią facetów ubranych w same spodnie, latających z jednego końca ogródka na drugi z nogami wysuniętymi do przodu i wrzeszczących przy tym niemiłosiernie. W momencie, gdy Kang otwierał furtkę, wiedział już, że popełnił błąd. Ułamek sekundy później upadł twarzą na chodnik po silnym kopnięciu. Jednak klasztor Szaolin wyrobił w nim pewne zachowania które prawdopodobnie uratowały mu życie. Błyskawicznie poderwał się na nogi unikając tym samym miażdżącego buta. Jeszcze w tej samej sekundzie wyprowadził dwa szybkie ciosy lewą nogą prosto w gardło pozbawiając przeciwnika oddechu, a chwilę później życia.
');
INSERT INTO texts (name, text) VALUES ('tekst16b.txt', '
Rozejrzał się. Wokoło był tylko las i droga. Las. Postanowił, że ukryje się między drzewami i poczeka na roboty. Wprawdzie przeciwko trzem miał małe szanse, ale miał nadzieję, że może się rozdzielą. Wszedł głębiej w las. Dotychczas roboty trzymały się bezbłędnie jego śladów. Liczył, że między drzewami trochę się pogubią i ofiara zamieni się w myśliwego. W pewnym momencie zamajaczyło mu w oddali migające światełko. Ruszył w tamtą stronę. Światełko okazało się małym ogniskiem, przy którym siedziało dwoje ludzi. A on znał tych ludzi.
');
INSERT INTO texts (name, text) VALUES ('tekst16.txt', '
Uciekał już mniej więcej dwie godziny. Zaczynało mu brakować oddechu. Podczas biegu zastanawiał się, jak go znaleźli. Już wcześniej ukrył się poza miastem, gdyż przewidział, że może zostać zdradzony. Teraz gonili go jego dawni przyjaciele. Chcieli go zabić. Wszystko było dobrze do czasu, gdy w laboratorium opracowano nowy model cyborga, który był lepszym wojownikiem niż ludzie. Po tym wszystkim stał się on niepotrzebny. A ponieważ za dużo wiedział, chciano go zlikwidować. Trzy wysłane za nim roboty wpadły na trop dopiero dwie godziny temu. Od tego czasu zaczął się szaleńczy wyścig człowieka z maszynami. Przystanął i obejrzał się za siebie. Za nim rozciągała się pusta ulica. Ogólną ciemność rozjaśniały postawione tu i ówdzie latarnie. Wziął głębszy oddech i pobiegł dalej, ale po kilku minutach zatrzymał się ponownie. Zadecydował, że najwyższy czas przejść do ofensywy.
');
INSERT INTO texts (name, text) VALUES ('tekst17.txt', '
Gdy powiedział, że ją kocha, zapytała, czy prędko się pobiorą. Wówczas on oświadczył, że niestety, ale jest żonaty. Była tym tak zgnębiona, że chciała zaraz iść do domu, a on nie puścił jej, dopóki nie obiecała, że jutro przyjdzie. Nie przyszła jednak więcej, a to dlatego, że zwierzyła się nazajutrz koleżance z siódmej klasy, pannie Jóźwińskiej, ta zaś wytłumaczyła Magdzie wiele rzeczy, o których Magda dotychczas pojęcia nie miała. Drugą miłością był właśnie brat Toli Jóźwińskiej. Zaprzyjaźniły się po tych zwierzeniach i Tola zapraszała ją do siebie na potańcówki. Pan Jóźwiński był bardzo bogatym adwokatem, a Karol studiował na politechnice, miał motocykl z wózkiem i kilka razy zabierał Magdę aż za Wilanów.
');
INSERT INTO texts (name, text) VALUES ('tekst18b.txt', '
Kilkakrotnie odbywano wycieczki do lasów, leżących na Dalekim Zachodzie. Koloniści nie obawiali się zbyt wysokiej temperatury, bo promienie słoneczne zaledwie gdzieniegdzie zdołały się przedrzeć przez nadzwyczaj gęste sklepienie lasu. Zwiedzili cały lewy brzeg Rzeki Miłosierdzia. Wybierając się na te wycieczki, zawsze dobrze się uzbrajali, gdyż często zachodziły im drogę dziki nadzwyczaj zuchwałe, z którymi musieli staczać uparte walki.
W tej także porze roku Gedeon i Harbert rozpoczęli straszną wojnę z jaguarami. Obaj myśliwi uzupełniali się wzajemnie. Harbert był nadzwyczaj odważny, reporter odznaczał się zimną krwią i przezornością. Dzięki tym zapalonym myśliwym już przeszło dwadzieścia prześlicznych skór jaguarów zdobiło ściany wielkiej sali Granitowego Pałacu, z czego można było wnosić, że potrafią osiągnąć zamierzony cel i oczyszczą wyspę z tych niebezpiecznych zwierząt.
');
INSERT INTO texts (name, text) VALUES ('tekst18.txt', '
12 lutego cała instalacja była już wykończona, i zaraz Cyrus zapytał Ayrtona, czy co złego nie zaszło w owczarni; w kilka minut odebrał zadowalającą odpowiedź. Penkroff nie posiadał się z radości i codziennie rano i wieczór wysyłał telegramy do owczarni, na które zawsze odbierał żądane odpowiedzi.
Urządzenie telegrafu zapewniało podwójną korzyść: po pierwsze mogli zawsze wiedzieć, czy Ayrton nie opuścił chaty, a po wtóre, nie pozwalali mu zostawać w zupełnym odosobnieniu. Oprócz tego Cyrus odwiedzał go regularnie przynajmniej raz na tydzień, a ilekroć Ayrton przybywał do Granitowego Pałacu, przyjmowano go życzliwie.
');
INSERT INTO texts (name, text) VALUES ('tekst19.txt', '
Powrócili wszyscy do niej, aby przyjrzeć się lepiej. Miała pięć stóp długości, a trzy szerokości; była starannie zamknięta i pokryta grubą skórą, przybitą mosiężnymi gwoździami; dwie próżne beczułki, szczelnie zaszpuntowane, przywiązane były do jej boków mocnymi powrozami. Nie znać na niej było żadnego uszkodzenia, co można by przypisać temu, że morze wyrzuciło ją na piasek, a nie między skały. Nadto, przyjrzawszy się jej bacznie, trudno było nie poznać, że niedługo przebywała w morzu i niedawno osiadła na piasku.
Morze tymczasem przybierało ciągle i woda dochodziła już do skrzyni. Nab i Penkroff odrzucili obsypujący ją piasek i wkrótce łódka, ciągnąc za sobą skrzynię, oddaliła się od wąskiego pasa ziemi, który nazwano Cyplem Skrzyni.
');
INSERT INTO texts (name, text) VALUES ('tekst20b.txt', '
Bardzo możliwe, że w Gedeonie odezwała się żyłka dziennikarska i pragnął wysłać w świat krótki artykulik streszczający przygody kolonistów Wyspy Lincolna przewidując, jak wielkiego tam narobi rozgłosu. Opisał wszystko, co się stało, treściwie na ćwiartce papieru, i dołączył usilną prośbę, aby ktokolwiek znajdzie to pismo, przesłał je natychmiast do redakcji New York Heralda. Następnie włożył karteczkę do małego woreczka z gumowego płótna i przywiązał go nie do nogi, lecz do szyi albatrosa, gdyż te ptaki odpoczywają zwykle na powierzchni morza. Gdy wreszcie wypuścili powietrznego gońca, z widocznym wzruszeniem patrzyli, dopóki nie zniknął im z oczu, lecąc ku zachodowi.
');
INSERT INTO texts (name, text) VALUES ('tekst20.txt', '
W tym czasie koloniści po raz pierwszy spróbowali porozumieć się z ludźmi. Gedeon Spilett od dawna nosił się z tym, aby powierzyć małą karteczkę gołębiowi lub w zakorkowanej dobrze butelce rzucić ją w morze. Zaniechał jednak tego zważywszy, że niepodobna było przypuścić, aby gołąb lub butelka mogły przebyć odległość tysiąca dwustu mil, które oddzielały wyspę od zamieszkanej ziemi. W ostatnim dniu czerwca udało się Harbertowi schwytać albatrosa, którego przedtem zranił w nogę strzałem z fuzji. Był to wielki ptak, którego rozpostarte skrzydła miały dziesięć stóp długości, mógł więc przebyć Ocean Spokojny.
');
INSERT INTO texts (name, text) VALUES ('tekst21.txt', '
Cała robota zajęła dwadzieścia cztery godziny. Po wielu próbach udało im się porobić knoty z włókien roślinnych, które umoczone w roztopionej stearynie, utworzyły świece; brakło im tylko wybielania i politury. Wprawdzie nie dorównywały one świecom, których knoty nasycone są kwasem borny, spalają się w miarę topienia stearyny i dlatego nie potrzebują obcinania, ale Cyrus Smith zrobił dobre szczypce i świece te bardzo były użyteczne podczas długich wieczorów.
Przez cały ten miesiąc pracowali gorliwie w nowym mieszkaniu. Stolarskiej roboty nie zabrakło, a oprócz tego udoskonalano i uzupełniano narzędzia.
Mogli już zrobić sobie nożyczki i poobcinać włosy, spadające prawie na ramiona. Nab i Harbert nie mieli zarostu, lecz towarzysze ich wyglądali okropnie, więc teraz mogli przynajmniej skrócić brody, wąsy i faworyty.
');
INSERT INTO texts (name, text) VALUES ('tekst22.txt', '
O jedenastej przed południem żeglarze byli już tylko o dwie mile od wyspy, czy raczej wysepki, jak ją nazwał Harbert, przypatrzywszy się jej lepiej, i mogli już rozróżnić grupy rozmaitych drzew. Dziwiło ich, że nie dostrzegli nigdzie dymu, a na wybrzeżu żadnego sygnału pozwalającego wnosić, że człowiek tu się znajduje i wzywa pomocy przepływających statków. Dokument znaleziony w butelce nie pozwalał jednak wątpić o tym.
Statek przesuwał się ostrożnie przez wąskie przesmyki między skałami, które Penkroff śledził bacznie, stojąc na dziobie statku, gdy tymczasem Harbert zastępował go przy sterze. Na koniec około południa zbliżono się do piaszczystego wybrzeża, zwinięto żagiel i rzucono kotwicę.
');
INSERT INTO texts (name, text) VALUES ('tekst23.txt', '
Trzy dni później wielki, czarny lincoln continental sunął zatłoczonymi ulicami Waszyngtonu. Na tylnym siedzeniu, oddzielonym od kierowcy szybą, siedział starszy, dystyngowany pan o starannie zaczesanych, srebrzystoszarych włosach. O takim odcieniu mówi się "salt and pepper". Obok niego na siedzeniu spoczywała aktówka z czarnej, cielęcej skóry. Były w niej trzy kartki papieru, egzemplarz gazety z zakreślonym flamastrem komunikatem umieszczonym u dołu drugiej strony oraz przypięte spinaczem tłumaczenie tekstu na język angielski. Jego treść sprawiała, że starszy pan myślał intensywnie, a nie były to myśli wesołe.
');
INSERT INTO texts (name, text) VALUES ('tekst24b.txt', '
Dzień był ładny, więc po śniadaniu poszedł na spacer, ciesząc się niepowtarzalną atmosferą, jaka zawsze panuje tam, dokąd przybywa parę tysięcy młodych ludzi ze wszystkich stron świata. Ktoś wpadł na pomysł znakomicie rozwiązujący problem poruszania się po rozległym terenie wioski, wprowadzając małe rowerki. Od razu cieszyły się olbrzymim powodzeniem. Było ich w wiosce tysiące i w niektórych miejscach trzeba było uważać, by nie zostać staranowanym przez hożą dziewoję, pędzącą na złamanie karku. Niektórzy zresztą specjalnie wystawali w takich miejscach.
Polscy floreciści wymyślili zabawę w piłkę rowerowo-nożną na trawie i odtąd na placyku przed gmachem, gdzie mieszkali zbierała się coraz liczniejsza grupka kibiców nowego sportu. Jerzy wziął raz tylko udział w takim meczu, ale stłukł piszczel i od tego czasu postanowił udzielać się wyłącznie jako sympatyk tego sportu.
');
INSERT INTO texts (name, text) VALUES ('tekst24.txt', '
Wśród uśmiechów, poklepywań i gratulacji, czuł, że jeszcze jest coś wart, on i jego ambicja. Pojawiające się od czasu do czasu na horyzoncie widmo Padwy stawało się coraz bardziej zwiewne i wyblakłe. Stosunki z Dropakiem były zimne, lecz poprawne. Żaden nie ryzykował ostatecznej rozgrywki. Nie stwarzało to najlepszej atmosfery nawet tu, w Tokio, ale na szczęście gorączka przedstartowa zepchnęła wszystko na dalszy plan.
Uspokoiwszy się nieco poszedł do mikroskopijnej łazienki, wziął tusz, po czym ułożył się na kozetce i momentalnie zapadł w sen.
Ranek przyniósł wyjaśnienie wczorajszych niepokojów. Okazało się, że przeżył pierwsze w życiu trzęsienie ziemi. Nie było to silne, gazety poświęcały mu zaledwie kilkuwierszowe wzmianki.
');
INSERT INTO texts (name, text) VALUES ('tekst25b.txt', '
W ekipie są przekonani, że ma zapewnione już miejsce w finale, gdyż ostatnią przeszkodą jest Włoch Cesare Salwadore, zawodnik zdecydowanie słabszy.
Ale kto może być pewny czegoś w sporcie do końca? Gdy wywołują ich walkę, Pawłowski jest trochę zmęczony, natomiast Włoch - jakby chciał zmienić niepochlebną opinię o sobie - atakuje z furią i trafia. Jerzy szybko przezwycięża kryzys i zaskoczenie, ale impet Włocha działa deprymująco. Pierwszą walkę wygrał zaledwie jednym trafieniem, drugą przegrał do trzech i o wszystkim ma zadecydować ostatnia, trzecia walka.
Włosi już szaleją z radości. Im w ogóle niewiele trzeba, całą grupą masują Salwadoremu nogi, hałas czynią niemożliwy, a jego przeciwnik...
');
INSERT INTO texts (name, text) VALUES ('tekst25.txt', '
Tu już zaczynają się problemy. Co prawda system ten daje jeszcze szansę w repasażach, ale przecież wiadomo, że jeżeli nie wyeliminuje swych rywali, to sam odpadnie. Żona jest pierwszy raz z nim na mistrzostwach świata i od rana nie opuszcza hali. Trochę to przeszkadza, ale z drugiej strony...
Do rundy ósemkowej wchodzi bez problemu. Dawno już mu się tak dobrze nie walczyło. Jakby znikły gdzieś kłopoty i zmory, zwłaszcza jedna z nich. Jakby nie spędził setek godzin na treningach, jakby nie było tych trudnych momentów, kiedy się ma wszystkiego dość, chce się rzucić z rozmachem, aż zajęczy, szablę i maskę i pójść gdzieś przed siebie.
');
INSERT INTO texts (name, text) VALUES ('tekst26b.txt', '
Z przerażeniem czekał na szczęk metalu, na wybuch i wdarcie się wody, na potwierdzenie tej strasznej pewności, że znalazł się w pułapce, że woda go zadusi, zanim zdąży ruszyć się z miejsca.
Którejś nocy udało mu się zasnąć, mimo że ostrzegano o grupie okrętów podwodnych gdzieś w pobliżu. Zapadł w drzemkę po godzinie napiętej czujności i właśnie wtedy, pomiędzy snem a jawą, usłyszał potworny wybuch, jak gdyby w samym wnętrzu okrętu. Kiedy wyskoczył z koi, rozległ się klakson na alarm i zaraz potem pospieszny tupot nóg. Pędził co sił do trapu, do otwartego nieba. Czuł, jak zalewa go fala ślepego strachu.
');
INSERT INTO texts (name, text) VALUES ('tekst26.txt', '
Mógł zejść na dół i spać w swej kabinie bez przerwy aż do rana. Nigdy jednak z tego nie korzystał, chyba na samym początku i na końcu rejsu, kiedy płynęli po wodach spokojnych i bezpiecznych. Już w samym fakcie układania się do snu poniżej linii wodnej było coś, co dręczyło jego wyobraźnię. Zdawało mu się zupełnie wykluczone, aby w ciągu tej nocy torpeda mogła nie trafić w korwetę. A jeśli trafi, to wedrze się na pewno aż tu, do jego kabiny... W bezsenne noce na otwartym bezkresnym Atlantyku wracały koszmarne myśli. Okręt stale kołysał się i stękał, a woda przepływała o kilka cali od jego posłania. Pocił się z lęku, wpatrywał się w gródź i w nity, które trzymały razem cienkie blachy poszycia. Tylko to poszycie dzieliło go od ciemnej wody.
');
INSERT INTO texts (name, text) VALUES ('tekst27b.txt', '
Tomlinson czuł się lepiej obsługując pospiesznie klientów, którzy żądali gorących pasztecików lub suchej kiełbasy (wyłącznie za gotówkę, bez żadnych reklamacji!), niż w wytworniejszym świecie mesy oficerskiej. Ponieważ jednak Lockhart dawnym zwyczajem zasiadał do swych samotnych posiłków z książką w ręku, nie drażniły go ani niedbała obsługa, ani bezbarwne jedzenie.
Korweta była przycumowana tuż obok "Viperous", na którym także czyszczono kotły. Po raz pierwszy Lockhart miał możność z bliska oglądać niszczyciela. Korzystając z tego sąsiedztwa, odwiedzał dość często kolegę na bratnim okręcie. Był nim podporucznik ze służby zawodowej, pozostawiony również na dyżurze, gdy inni poszli na urlop.
');
INSERT INTO texts (name, text) VALUES ('tekst27.txt', '
Lockhart wyciągnął los, że zostanie jako dyżurny oficer na okręcie. Jego kolej na urlop miała przyjść następnym razem. Nie uważał się wcale za skrzywdzonego. Ostatnio dostał awans na porucznika. Dodatkowy złocisty pasek błyszczał na rękawie, potęgując poczucie odpowiedzialności. Poza tym mógł zażyć odpoczynku, jakiego potrzebował. Wolne chwile spędzał na urlopie - czytał i słuchał radia, rozplątywał skomplikowany węzeł ostatnich miesięcy. Na "Compass Rose" wygaszono kotły, wentylatory nie działały, było chłodno i cicho. Dziwne wrażenie sprawiała korweta, przedtem zawsze aktywna i ruchliwa, a teraz zawieszona w mgławicy lenistwa, jak on sam. Miał bardzo mało do roboty, a już zupełnie nic takiego, co wymagałoby skupienia. Po śniadaniu robił przegląd załogi i zapowiadał Phillipsowi, co trzeba w tym dniu sprzątnąć i co pomalować.
');
INSERT INTO texts (name, text) VALUES ('tekst28b.txt', '
Wciąż się mylili, spóźniali, robota nie wychodziła. Dziwili się, kiedy coś poszło gładko, a gdy się nie udało, spoglądali posępnie, obojętnie. Pozostawiony sam sobie, Ferraby pewnie by okrzepł i stopniowo doprowadził swój dział do stanu sprawności. Lecz Bennett cel łatwiejszy od Lockharta. Łaził więc bez ustanku na pokład nad rufą i przechyliwszy się przez reling, zasypywał młodszego oficera mnóstwem uwag i sprzecznych rozkazów, kruszył na proch tę odrobinę ufności w swe siły, jaką Ferraby zdołał odbudować. Doszło do tego, że Ferraby ze strachem rozpoczynał ćwiczenia, które musiał prowadzić co dzień w czasie całego postoju w porcie.
');
INSERT INTO texts (name, text) VALUES ('tekst28.txt', '
Ferraby, odosobniony na rufie wraz ze swoimi bombami, nie mógł się pochwalić sukcesem w podciągnięciu swych ludzi do jakiegoś znośnego poziomu. Obydwu starszym marynarzom trudno było cokolwiek zarzucić - obaj byli zupełnie pewni i energiczni. Torpedysta Wainwright odbezpieczał i nastawiał bomby, a także sam je wyrzucał. Starszy marynarz Tonbridge stał na czele całej obsługi wyrzutni. Lecz reszta ludzi była w większości poniżej przeciętnego poziomu. Praca ich polegała na szybkim wkładaniu bomb do opróżnionych przedziałów. Wymagało to zgranego współdziałania zespołu ludzi. Ferraby rozporządzał dość przypadkowym kompletem marynarzy z maszyny, którzy nie mieli wachty, oraz radiotelegrafistów nie kwapiących się zbytnio do pracy na pokładzie, gdzie wiatr przewiewał człowieka na wylot.
');
INSERT INTO texts (name, text) VALUES ('tekst29b.txt', '
Starszy marynarz Tonbridge miał dwadzieścia trzy lata, był dzieckiem londyńskich slumsów i miał za sobą siedem lat służby w Royal Navy. Fakt, że nie uciekł od tej próby, że potrafił okazać sprawność w działaniu, wykraczał swoją treścią poza wszelkie normalne pochwały.
Robili, co tylko mogli. Wiosłowali w ciemności, kierując się wołaniem, przerażeni do szpiku kości zduszonym krzykiem ludzi, którzy tonęli, zanim zdołali podpłynąć. Ze wszystkich sił starali się ratować i pomagać. Wyciągnęli czternastu ludzi: jeden już nie żył, drugi był konający, ośmiu rannych, a pozostali oszołomieni wstrząsem i całkowicie wyczerpani. Niewiele brakowało, a byłoby piętnastu.
');
INSERT INTO texts (name, text) VALUES ('tekst29.txt', '
Gdy Tonbridge ujął za rumpel i spojrzał w jego kierunku chcąc wziąć właściwy kurs, rozległ się ponad wodą zgrzyt rozdzieranej stali i statek zaczął się pogrążać. Tonbridge patrzył, wstrząśnięty do głębi grozą i lękiem. Nigdy nie widział czegoś podobnego, nigdy nie powierzono mu jeszcze takiego zadania. Niełatwo będzie je spełnić jak należy. Wystarczyło, że odeszli od "Compass Rose" w sam środek ciemności, że widzieli, jak ich okręt rozpływa się w mroku, że konwój także znikł w oddali, oni zaś byli sami w maleńkiej łodzi pod niebem pełnym gwiazd, pośród wielkiego, nieprzyjaznego oceanu. Ale to, na co musieli patrzeć teraz, podobne było raczej do zmory sennej niż do jawy: storpedowany statek zanurzał się w ich oczach, ludzie, miotając się w wodzie, krzyczeli rozpaczliwie, duszący zapach ropy niósł się ciężką falą w powietrzu.
');
INSERT INTO texts (name, text) VALUES ('tekst30b.txt', '
Potworny zgiełk skłębiony nad konwojem osiągnął punkt kulminacyjny w chwili, gdy samolot zrzucił dwie bomby na czoło środkowej kolumny: jedna upadła w morze, wzbijając ogromny, pierzasty słup wody, połyskujący w poświecie księżyca; druga trafiła w cel. Trzasnęła z metalicznym szczękiem w statek, którego nie mogli dojrzeć i którego na pewno już nigdy nie zobaczą. Bo zaraz po pierwszym wybuchu rozległ się drugi. Potężna pomarańczowa łuna oświetliła widmowym blaskiem konwój i całe niebo nad konwojem. Pod takim ciosem każdy statek, obojętne - mały czy duży, musiał natychmiast rozlecieć się w drzazgi. Wyrzucone w powietrze szczątki statku z pluskiem spadały znów do morza w promieniu pół mili od miejsca eksplozji.
');
INSERT INTO texts (name, text) VALUES ('tekst30.txt', '
Atakujący samolot leciał nisko nad środkiem konwoju, ścigany i smagany ogniem dział przeciwlotniczych z kilkudziesięciu statków równocześnie. Samolotu nie było widać, lecz jego drogę znaczyły płonące wstęgi pocisków świetlnych, rozwijające się w olbrzymi wachlarz nad czołem konwoju. Powstał straszliwy zgiełk - warkot samolotu drążył ciemność, huczały setki dział naraz, na kilku statkach ryczały syreny alarmowe. Prawdziwym piekłem musiał być środek konwoju, gdzie ze wszystkich statków prano w nisko lecący samolot, nie troszcząc się o to, co znajdzie się na linii celu. Stali na rufie, tuż nad wodą umykającą wartkim strumieniem spod śruby, i patrzyli, czekali, usiłowali przewidzieć, w którą stronę poleci samolot po skończonym ataku. Nad nimi, na platformie 47-milimetrowego działa, marynarze z obsługi stali w hełmach na głowie, nieruchomi na tle ciemnego nieba, gotowi do oddania strzału, gdy przyjdzie ich kolej. Ale nie przyszła ich kolej, gotowe do użycia taśmy pocisków nie zostały użyte.
');
INSERT INTO texts (name, text) VALUES ('tekst31.txt', '
Teoria narastających defektów opiera się na innym założeniu - stopniowym zużywaniu komórek, spowodowanym ciągłym przeprowadzaniem przez nie niezbędnych do życia reakcji chemicznych, które powoli zatruwają ich mechanizmy. Mechanizmy obronne komórki po prostu po pewnym czasie się wyczerpują i zaczyna ona się starzeć aż w końcu umiera. Najbardziej prawdopodobną przyczyną tak szybkiego zużywania się komórek są tzw. wolne rodniki, grupa związków chemicznych, będących produktem ubocznym procesów przemian niektórych związków. Te związki chemiczne kiedy już zostaną uwolnione w komórce, uszkadzają cząsteczki niezbędne do jej naprawy.
');
INSERT INTO texts (name, text) VALUES ('tekst32.txt', '
Do tej chwili wykład Golema nie odbiega wiele od rewelacji współczesnych genetyków, jest też, co ciekawe, zadziwiająco zbieżny z głośną, a powstałą niezależnie i w zbliżonym czasie książką Richarda Dawkinsa Samolubny gen. Wątek nowy pojawi się w momencie, gdy Lem, głosem komputera, pocznie dywagować nad kwestią uwikłania Rozumu w drabinę ewoluujących gatunków. Powie nam wówczas, że Rozum nie tyle jest ukoronowaniem doskonalących się funkcji organicznych, ile kołem ratowniczym rzuconym zdefektowanym, niedoskonałym właśnie, produktom późnych etapów biologicznej kreacji.
');
INSERT INTO texts (name, text) VALUES ('tekst33.txt', '
Już chciałem skierować się na powrót w bezmiar przestrzeni, gdy dostrzegłem, że jakaś malutka postać daje mi z dołu znaki. Zamknąwszy silnik, splanowałem szybko i osadziłem wehikuł w pobliżu grupy malowniczych skał, na których wznosił się spory budynek z ciosanego kamienia. Na moje spotkanie biegł polem rosły starzec w białym habicie dominikanina. Był to, jak się okazało, ojciec Lacymon, przełożony wszystkich misji działających na obszarach pobliskich gwiazdozbiorów w promieniu sześciuset lat świetlnych. Okolica ta liczy około pięciu milionów planet, w tym dwa miliony czterysta tysięcy zamieszkanych. Ojciec Lacymon, dowiedziawszy się o przyczynie, która sprowadziła mnie w te strony, wyraził współczucie, zarazem zaś radość z mego przybycia, bo jak mi rzekł, jestem pierwszym człowiekiem, jakiego widzi od siedmiu miesięcy.
');
INSERT INTO texts (name, text) VALUES ('tekst34.txt', '
Pytanie, które zostało pomyślane nie doczekało się pomyślnej odpowiedzi, a to zaowocowało podejrzeniem w stosunku do leżącego przede mną kalafiora. Postanowiłem rozkroić go na pół aby przyjrzeć się mu od środka. Tak też zrobiłem. W środku kalafiora był... najzwyklejszy środek kalafiora, nic szczególnego. Znaczyło to zapewne, że ten kalafior był najzupełniej zdrowy - przynajmniej od środka. No to sekcja ugotowanego kalafiora zrobiona, ale co to za czarne małe drobinki?? Czy to aby jest normalne u takiego ugotowanego kalafiora? Przed skonsumowaniem tej rośliny postanowiłem zaistniałą sytuację zbadać osobiście.
');
INSERT INTO texts (name, text) VALUES ('tekst35.txt', '
Otóż pisarz to w gruncie rzeczy świnia. Ostatni cham. Nie, to zbyt łagodne określenia. To kat. Morderca. Spójrzcie - tworzy światy, zapala słońca, ziszcza ludzi - zupełnie jak Pan Bóg. Tylko, że on je potem niszczy. Pomyślcie, ile książek nie powstało dla jednego opowiadania, ileż dzieł zostało zamordowanych w zarodku, by mogło powstać jedno. To już znamy, gdzieś zapewne słyszeliśmy. Ale to nie jest jeszcze najgorsze. Można to złożyć na karby poświęcenia, musi zginąć jeden, by mógł żyć inny, nie ma tutaj mowy o żadnej niehumanitarności. Lecz czy nie pomyśleliście nigdy, że pisarz może sobie tworzyć światy dla samej zabawy i potem je sobie obserwować, aż sczezną - z jego winy.
');
INSERT INTO texts (name, text) VALUES ('tekst36.txt', '
Klawiatura to taka wspaniała, przydatna i wygodna rzecz. Dlaczego w takim razie, siedząc przed nią kilka godzin, nie jestem w stanie napisać ani jednego sensownego zdania? Zlecenie jest, termin oddania też, wiem nawet, jakie będzie honorarium. Nie będzie zbyt wysokie, ale zawsze coś. Zresztą nie piszę dla zarobku. Robię to tylko dlatego, że lubię. Mimo wszystko, tylko siedzę i patrzę w okno. Szukam pomysłów, gdzie tylko mogę. Patrzę na deszcz, widzę jak jego krople bardzo powoli spływają po szybie. Łączą się z innymi i odpływają dalej, w tylko sobie znanym kierunku. Przypomina to trochę ludzkie życie. To znaczy, te krople deszczu, one są jak ludzie.
');
INSERT INTO texts (name, text) VALUES ('tekst37.txt', '
Był przeciętną młodą osobą, chodził do przeciętnej szkoły średniej, przeciętnie się uczył, przeciętnie wyglądał. Żył w przeciętności i razem z nią. Nic nie mąciło mu spokoju, miał swoje życie, ze zwykłymi problemami. Wiedział, że jest jak wszyscy, ale wcale mu to nie przeszkadzało. Nie lubił się wyróżniać, to mogło przynieść wyłącznie kłopoty. Miał kolegów i koleżanki, normalną rodzinę, dobre widoki na przyszłość. Lubił oglądać telewizję, grać na komputerze. Robili to przecież wszyscy. Czuł się bezpiecznie. Sądził, że trudno o lepsze szczęście. Mylił się.
');
INSERT INTO texts (name, text) VALUES ('tekst38.txt', '
Mało jest chwil w życiu, w których by człowiek doznawał większej przykrości, nie zjednywając sobie przy tym żadnego współczucia, jak wówczas, gdy odbywa polowanie na swój własny kapelusz. Trzeba mieć wielki zasób zimnej krwi i zdolność do szybkiej decyzji, by go złowić. Najlepsza metoda polega na tym, by biec równolegle do przedmiotu naszych zabiegów, zachować największą przezorność, umieć skorzystać ze sposobnej chwili, stopniowo wyprzedzać, potem nagle pochylić się, ująć kapelusz za rondo i mocno osadzić go na głowie, wdzięcznie uśmiechając się podczas tej gonitwy, jak gdybyśmy sami, jak wszyscy inni, widzieli w tym tak dobry żart.
');
INSERT INTO texts (name, text) VALUES ('tekst39.txt', '
Widok, jaki miał przed oczyma, mógłby zachwycić każdego nawet w mniejszym stopniu zdolnego do uniesień nad wiejską przyrodą. Po lewej stronie wznosił się mur, w wielu miejscach poszczerbiony, ponurą swą masą panując nad zielonymi brzegami rzeki Medway. Zwoje bluszczu smutno wieńczyły czarne blanki, a pęki morskich roślin, zwieszonych na kamieniach, drżały za powiewem wiatru. Poza tymi zwaliskami wznosił się stary zamek, którego wieża bez dachów i walące się mury świadczyły o ubogiej wielkości owych chwil, gdy szczęk broni i donośne śpiewy rozlegały się pod wspaniałymi arkadami.
');
INSERT INTO texts (name, text) VALUES ('tekst40.txt', '
Jak wszyscy ludzie, którzy mają jeden ze zmysłów rozwinięty ponad ludzką potrzebę, ojciec był bardzo nerwowy. I oprócz tego był sentymentalny, i jak wszyscy sentymentalni ludzie potrafił okazywać okrucieństwo i obrażać się na cały świat. Nie miał wiele szczęścia, choć nie zasługiwał na takie pomijanie przez los. Zginął w potrzasku, który sam krótko przedtem pomagał zastawiać. A nim zginął wszyscy po kolei w jakiś sposób go w życiu oszukali. Uczuciowi ludzie są tak często oszukiwani. Nicholas nie mógłby jeszcze napisać historii ojca, chociaż miał zamiar uczynić to w przyszłości. Myślał o ojcu z tego okresu, kiedy był jeszcze małym chłopcem, wdzięcznym za dwie rzeczy: łowienie ryb i polowanie.
');
INSERT INTO texts (name, text) VALUES ('tekst41.txt', '
Radio nie działało zbyt dobrze, dopóki nie zapadł zmrok. Mówiono, iż to dlatego, że w ziemi jest tyle rudy czy też coś tam z górami, ale w każdym razie nie działało dobrze, dopóki na dworze nie zaczęło się ściemniać; natomiast w nocy działało doskonale i kiedy jedna stacja kończyła audycję, można było przesunąć się dalej na zachód i wyszukać następną. Ostatnią, jaką się odbierało, było Seattle w stanie Waszyngton, i kiedy tam przestawali nadawać o czwartej nad ranem, w szpitalu z uwagi na różnicę czasu była piąta rano, a o szóstej mogło się łapać porannych rewelersów z Minneapolis. Pan Frazer wyobrażał sobie, jak wyglądają wysiadając z tramwaju przed świtem i niosąc swoje instrumenty.
');
INSERT INTO texts (name, text) VALUES ('tekst42.txt', '
Asfaltowa szosa urwała się. Droga była teraz wyżwirowana; zostawiwszy za sobą dolinę jechaliśmy pod górę między dwoma wzgórzami. Droga zakręcała i zaczynała piąć się coraz wyżej. Ziemia na wzgórzach była czerwona, bożydrzew rósł tu szarymi kępami, i w miarę jak droga podchodziła wyżej, otwierał się widok nad wzgórzami i nad płaszczyzną doliny aż ku górom. Były teraz już dalej i jeszcze bardziej przypominały Hiszpanię. Droga wiła się i znowu pięła pod górę, a przed nami kilka pardw kąpało się w piasku na drodze. Kiedy podjechaliśmy bliżej, zerwały się, trzepocząc szybko skrzydłami, a potem poszybowały długim skosem i siadły na stoku wzgórza poniżej.
');
INSERT INTO texts (name, text) VALUES ('tekst43.txt', '
Dzień był słoneczny i mroźny. Ziemia pokryta była szronem, tak iż zdawało się, że wszystkie nagie gałęzie drzew, krzaki i poszycie, wszystka trawa, a nawet goła ziemia została zawerniksowana cienką warstwą lodu. Zabrałem młodego irlandzkiego setera na krótki spacer po szosie i wzdłuż zamarzniętej łachy, ale trudno było chodzić, a nawet stać na szklistej powierzchni. Rudy pies ślizgał się i potykał, a ja sam upadłem ciężko dwa razy i raz upuściłem dubeltówkę, która pojechała daleko po błyszczącym lodzie. Spłoszyliśmy stado kuropatw spod wysokiego gliniastego nasypu. Zestrzeliłem dwie, a reszta zniknęła mi z oczu ponad szczytem nasypu.
');
INSERT INTO texts (name, text) VALUES ('tekst44.txt', '
Opowiem wam o szarańczy amerykańskiej. Ta większa, co latając wydaje odgłos trochę przypominający grzechotnika, kiedy grzechocze grzechotkami, taki bardzo suchy dźwięk, ma skrzydełka o żywej barwie. Owady te bywają jasnoczerwone albo żółte, pręgowane czarno, ale skrzydełka rozłażą im się na kawałki w wodzie i przez to nie nadają się na przynętę, podczas gdy ta średnia brązowa jest tłusta, jędrna, soczysta i mogę ją polecić, o ile można polecać coś, z czym panowie prawdopodobnie nigdy się nie spotkają. Muszę jednakże podkreślić, że nie zdołacie uzbierać dostatecznego zapasu tych owadów na cały dzień łowienia, jeżeli będziecie je łapać rękami albo usiłowali trafić kijem.
');
INSERT INTO texts (name, text) VALUES ('tekst45.txt', '
Odpocząłem i powiosłowałem z powrotem. Już się zrobiło późne popołudnie. Jeszcze raz znurkowałem z kluczem, ale nic z tego nie wyszło. Ten klucz był za lekki. Nie warto było nurkować bez porządnego młotka albo czegoś ciężkiego, czym dałoby się coś zrobić. Więc znowu uwiązałem klucz do osęka, patrzyłem przez szkło, grzmociłem i waliłem w szybę, aż klucz się urwał i widziałem go dobrze, wyraźnie przez moje szkiełko, jak zsuwał się w dół po kadłubie statku, a potem wsiąkł w ruchomy piasek i już go nie było. Nie mogłem nic zrobić. Klucz poszedł, chwytak straciłem, więc powiosłowałem z powrotem do łodzi. Nie miałem już siły, żeby wciągnąć składak na łódź, a słońce zniżyło się porządnie.
');
INSERT INTO texts (name, text) VALUES ('tekst46.txt', '
Widziałem wszystko ostro i wyraźnie. Maszt sterczał ukosem z wody, bo statek leżał na boku. Dziób nie był bardzo głęboko. Mogłem stanąć na literach nazwy statku na dziobie i głowę mieć akurat nad wodą. Ale najbliższy iluminator był ze dwanaście stóp głębiej. Ledwie go mogłem sięgnąć osękiem i spróbowałem rozbić szybę, ale nie dałem rady. Szkło było za grube. Więc popłynąłem z powrotem do łodzi, wziąłem klucz francuski, przywiązałem do końca osęka, ale i tym nic nie zrobiłem. No i takem tam patrzał przez szkło na ten liniowiec; wszystko na nim było, ja przypłynąłem pierwszy i ani rusz nie mogłem się do niego dobrać. A musiało na nim być towaru za jakieś pięć milionów dolarów.
');
INSERT INTO texts (name, text) VALUES ('tekst47.txt', '
Płaskie kamienie, którymi był wyłożony dziedziniec, lśniły od czystości, jak posadzka w kościele. Nachylone głowy smoków, którymi kończyły się rynny, wypluwały deszczówkę do cysterny, a gzymsy okien na wszystkich piętrach zdobiły kolorowe doniczki, pełne kwitnących bławatków i heliotropów. Dalej ogrodzenie, zrobione z zaostrzonych pali, zamykało sad, ogród, na którego klombach układano kwiaty w monogramy, szpalery winogradu, wreszcie placyk do gry w kręgle, ulubionej rozrywki paziów. Po drugiej stronie zamku była psiarnia, stajnie, piekarnia, tłocznia i spichrze. Wszystko otaczał szeroki pas łąki przeznaczonej na pastwisko, zamkniętej gęstym i kolczastym żywopłotem.
');
INSERT INTO texts (name, text) VALUES ('tekst48.txt', '
W dali rozległo się pianie kura. Inne mu odpowiedziały. Wstawał dzień i za gajem pomarańcz zobaczył dach pałacu. Odetchnął z ulgą i spostrzegł, że tuż, tuż nad zbożem podlatują czerwone kuropatwy. Zdjął płaszcz i zarzucił na nie jak siatkę. Kiedy go podniósł, znalazł tylko jednego ptaka, od dawna zdechłego i gnijącego.
To rozczarowanie było sroższe od poprzednich. Znowu schwyciła go żądza mordu. W braku zwierząt powyrzynałby chętnie ludzi. Wbiegł z tarasu na taras, uderzeniem pięści otworzył drzwi, ale kiedy był na schodach, obraz umiłowanej żony wzruszył mu serce. Na pewno śpi jeszcze, zrobi jej niespodziankę. Zdjąwszy sandały, obrócił cicho klucz i wszedł.
');
INSERT INTO texts (name, text) VALUES ('tekst49.txt', '
Mały stół, niewygodny stołek, posłanie z suchych liści i trzy gliniane garnki stanowiły cały jego majątek. Dwie dziury w murze służyły za okna. Z jednej strony jałowe rozłogi i rozsiane gdzieniegdzie blade stawy rozpościerały się tak daleko, że wzrok się w nich gubił. Ogromna rzeka toczyła przed chatą zielonawe wody. Na wiosnę zgniłe opary unosiły się z mokrej ziemi. W czasie suszy porywisty wiatr podnosił i pędził tumany kurzu. Kurz przenikał wszędzie, trzeszczał między zębami i woda do picia robiła się błotnista. Później przylatywały roje komarów tnących bezustannie, brzęczących dniem i nocą. Potem chwytały srogie mrozy, nadając przedmiotom twardość granitu.
');
INSERT INTO texts (name, text) VALUES ('tekst50.txt', '
Temperatura w maszynowni doszła do stu siedemnastu stopni. Przez świetlik i przez kratownicę nad kotłownią dochodziły gniewne głosy. Dudniły głucho we wnętrzu, eksplodując ni stąd, ni zowąd, zmieszane z brzękami i zgrzytami metalowymi, jakby tam w dole kłócili się ludzie z żelaza o krtaniach z brązu. Drugi mechanik wsiadł na palaczy, że dopuścili do tego, by ciśnienie pary spadło. Był to siłacz muskularny jak kowal i zwykle bano się go jak ognia. Ale tym razem palacze odpowiadali mu zawzięcie i z furią rozpaczy zatrzaskiwali drzwi palenisk. Potem gwałt ustał nagle i drugi mechanik, ociekając smarem i potem, jak wyciągnięta z komina miotła kominiarza, wychylił się z kotłowni.
');
INSERT INTO texts (name, text) VALUES ('tekst51.txt', '
Tarcza zachodzącego słońca malała, a gasnący brąz jego bezpromiennego żaru sprawiał wrażenie, jak gdyby miliony wieków minęło od poranku do zachodu słońca. Gęsta ławica chmur ukazała się z północnej strony; miała posępny, ciemnooliwkowy kolor, leżała na morzu nisko i nieruchomo, niby namacalna przeszkoda na drodze statku, który szedł ku niej chwiejnie; rzekłbyś, żywe stworzenie wleczone na ubój. Miedziany zmierzch rozproszył się powoli i z zapadnięciem ciemności na niebie wystąpiło mrowie dużych, rozchwianych jak na wietrze gwiazd migocących niezwykle i zdających się wisieć bardzo nisko ponad ziemskim globem.
');
INSERT INTO texts (name, text) VALUES ('tekst52.txt', '
Blade światło błyskawicy zapłonęło dokoła, jak gdyby rzucone do wnętrza jaskini, do czarnego, tajemnego sanktuarium morza mającego, miast posadzki, kipiel z wrzących grzyw piany. Na krótkie, ściskające serce mgnienie w ponurym świetle zamajaczyła masa postrzępionych chmur zawisłych nisko, wydłużona sylwetka parowca w skoku, czarne postacie ludzi uwięzionych na pomoście. A gdy dokoła zapadły ciemności, wówczas dopiero nadeszło prawdziwe uderzenie. Było to coś przeraźliwego i gwałtownego jak rozbicie naczynia z wściekłością. Była to eksplozja dokoła okrętu z porażającym wstrząsem, z grzmotem, pędem wielkich wód, jak gdyby olbrzymia grobla po nawietrznej została wysadzona w powietrze.
');
INSERT INTO texts (name, text) VALUES ('tekst53.txt', '
Po wielu latach wiernej służby mój zegarek zaczął się psuć. Tak, wiem, że mógłbym oddać go do naprawy, ale ponieważ naprawdę jestem najpunktualniejszą osobą na świecie, jak sobie poradzę, kiedy nie będę go miał? Mam korzystać z faz Księżyca? Chodzenie bez zegarka na ręce jest dla mnie gorsze niż chodzenie bez spodni. Oczywiście, że mam zegarek zapasowy. Jest bardzo ładny. Niestety, moje oczy są już tak stare i zużyte, że nie jestem w stanie właściwie odczytać wskazań z jego tarczy. W konsekwencji na zeszłotygodniowe spotkanie z moim dobrym znajomym przybyłem z godzinnym opóźnieniem. To zaś, w moim przekonaniu, jest gorsze od zwymiotowania na niego zaraz po przyjściu.
');
INSERT INTO texts (name, text) VALUES ('tekst54.txt', '
Słuch absolutny budzi szczególne zainteresowanie, gdyż wskazuje na zupełnie swoisty obszar jakości percepcyjnych, którego większość z nas nie jest w stanie nawet sobie wyobrazić; chodzi przy tym o wyizolowaną umiejętność, bez żadnego wyraźnego związku z muzykalnością czy czymkolwiek innym, która pokazuje, w jaki sposób przy jej kształtowaniu geny współpracują z doświadczeniem. Dawne mniej czy bardziej intuicyjne przekonanie, że słuch absolutny częściej zdarza się pośród muzyków niż reszty publiczności, potwierdziły szeroko zakrojone badania. Wśród muzyków słuch absolutny mają najczęściej ci, którzy wcześnie rozpoczęli naukę, chociaż ten związek nie zawsze się potwierdza.
');
INSERT INTO texts (name, text) VALUES ('tekst55.txt', '
Wychowany w atmosferze klasycznej muzyki zachodniej, bez trudu wychwytuję jej stosunkowo proste rytmy i schematy metryczne, ale w stropienie wprawiają mnie bardziej skomplikowane rytmy mamba czy tanga, by już nie mówić o synkopach czy polirytmiczności jazzu i muzyki afrykańskiej. Kultura i warunki, w których ktoś się kształtuje, wpływają też na wrażliwość tonalną. Ktoś taki jak ja będzie skłonny uważać skalę diatoniczną za bardziej "naturalną" od dwudziestodwutonowych skal muzyki hinduskiej. Nie wydaje się jednak, by istniały jakiekolwiek wrodzone preferencje neurologiczne dla jakiegoś typu muzyki, podobnie jak nie ma takich preferencji w odniesieniu do konkretnych języków.
');
INSERT INTO texts (name, text) VALUES ('tekst56.txt', '
Od chwili zderzenia z głównymi siłami huraganu na całym pokładzie nie było gdzie się schronić, więc zgnębieni i ogłuszeni marynarze ukryli się we wnętrzu, w lewoburtowym korytarzu pod pomostem. Drzwi prowadzące na rufę zamknęli za sobą. W korytarzu było zimno, ponuro i ciemno, choć oko wykol. Za każdym gwałtownym rzutem statku w ciemnościach odzywał się chóralny jęk; tony wody przelewały się nad nimi próbując, rzekłbyś, dostać się do wnętrza z góry. Bosman strofował marynarzy, ale bezskutecznie. Skarżył się potem, że zachowywali się, jakby postradali zmysły. Byli w bezpiecznym i dość dogodnym schronieniu i nie kazano im nic robić. Nie przestawali jednak narzekać i złościć się jak chore dzieci.
');
INSERT INTO texts (name, text) VALUES ('tekst57.txt', '
Pisanie na klawiaturze bezwzrokowo i dziesięcioma palcami jest bardzo szybkie i wygodne. Rozpowszechniona metoda "hunt and peck" (pisania z patrzeniem na klawiaturę, zwykle dwoma palcami) pozwala osiągać prędkości podobne jak przy pisaniu długopisem na papierze - około 150 znaków na minutę. Kilka tygodni treningu pisania bezwzrokowego pozwala bez trudu znacznie przekroczyć tą prędkość, a w dalszej perspektywie pisać dwa, lub nawet trzy razy szybciej. Są osoby osiągające prędkości rzędu 500 znaków na minutę i więcej (rekord świata wynosi ponad 1000). Prawidłowa technika bezwzrokowa umożliwia też bardziej równomierny rozkład pracy na poszczególne palce, co zwiększa ergonomię pisania.
');
INSERT INTO texts (name, text) VALUES ('tekst58.txt', '
Niedawno naukowcy podali, że dziecko urodzone w 2030 roku będzie żyło o pięć lat dłużej, niż dziecko urodzone wczoraj. Z tego powodu w połowie obecnego stulecia więcej będzie ludzi pobierających emerytury, niż pracujących. Wpłynie to katastrofalnie na ekonomię, ponieważ proste obliczenia pokazują, że w budżecie zabraknie pieniędzy, by wszystkim tym staruszkom wystarczyło na protezy bioder i karmę dla kotów. W takim razie, co u licha zrobimy? Skłonimy ludzi by oszczędzali więcej i na starość byli samowystarczalni? Zmusimy wszystkich, by mieli więcej dzieci? Czy też wezwiemy na pomoc tysiące imigrantów, którzy będą chcieli uwijać się przy jakiejś konkretnej robocie? Trudna decyzja.
');
INSERT INTO texts (name, text) VALUES ('tekst59.txt', '
W zeszły czwartek dwa rekiny ludojady pożarły osiemnastoletniego australijskiego surfera. Według świadków zdarzenia, rozerwały jego ciało na pół, a następnie spędziły parę minut walcząc o to, któremu z nich przypadnie który kawałek. Jak zwykle w takim przypadku, przeprowadzono wywiady z różnymi ekspertami od przyrody, którzy zgodnie stwierdzili, że rekiny te należy wypuścić na wolność po udzieleniu im pouczenia, częściowo dlatego, że są pod ochroną, a częściowo dlatego, że do takich ataków dochodzi niezwykle rzadko. A jednak to nieprawda. W rzeczywistości nie minął nawet tydzień, a kolejny surfer został pożarty dokładnie przy tym samym odcinku brzegu. Co w takim razie jest grane?
');
INSERT INTO texts (name, text) VALUES ('tekst60.txt', '
Z niewyjaśnionych po dziś dzień przyczyn, zostaliśmy przewiezieni do szpitala, gdzie zacząłem opracowywać przebiegły plan ucieczki. Ponieważ nie miałem pod ręką łyżek, wykluczyłem opcję drążenia tunelu. Chwilę później doznałem olśnienia. Doszedłem do wniosku, że skoro jestem w szpitalu, to okno w ubikacji nie będzie miało krat. Miałem rację. Podczas gdy policjant czekał na zewnątrz kabiny, ja w środku wydawałem niezliczone ilości przekonujących - tak mi się przynajmniej wydawało - odgłosów wymiotowania, które ułatwiły mi otwarcie okna. Nie było ono duże, ale udało mi się wydostać prawie w całości. Wtedy poczułem na moich kostkach krzepkie dłonie policjanta.
');
INSERT INTO texts (name, text) VALUES ('tekst61.txt', '
Przypuszczam, że wszyscy marzymy o dniu, w którym George Clooney zadzwoni do nas, by powiedzieć, że właśnie jest w okolicy i chciałby wpaść do nas na obiad. Fantazjujemy o tym, jak na przystawkę podany solę, i o błyskotliwej konwersacji, którą zaserwujemy do kawy i miętowych czekoladek. I dobrze wiemy, że nigdy się to nie wydarzy. Otóż w zeszłym tygodniu przytrafiło mi się coś w tym stylu. Byłem w moim domku wypoczynkowym nad morzem, kiedy ktoś, kogo zaprosiłem na obiad, zadzwonił, by zapytać, czy mógłby przyjechać ze znajomą, która okazała się być moją najbardziej ulubioną aktorką na świecie. Nie lubię sformułowania "zatkało mnie", ale właśnie tak się stało.
');
INSERT INTO texts (name, text) VALUES ('tekst62.txt', '
Odtwarzanie białego szumu w celi więźnia jest sklasyfikowane jako tortura. Ta praktyka jest zakazana przez wszystkie cywilizowane kraje, bo umysł człowieka nie może sobie poradzić z trwającą w nieskończoność sekwencją przypadkowych dźwięków. W końcu prowadzi ona do obłędu.
Ale dokładnie z tym mamy do czynienia podczas bieżącej kampanii wyborczej. Niekończący się biały szum obietnic, które nie mogą być dotrzymane, statystyk, które nic nie znaczą, i urywków spektakli z osobistymi zniewagami. Dlaczego? No cóż, mówiąc wprost, zrobienie reportażu z kampanii wyborczej kosztuje bardzo niewiele, w przeciwieństwie, dajmy na to, do reportażu z wojny.
');
INSERT INTO texts (name, text) VALUES ('tekst63.txt', '
Całkowicie rozumiem, że w dzisiejszych, pełnych pośpiechu czasach, gdy pracujemy do późna i wiele godzin spędzamy stojąc w korkach, nie zawsze można zdążyć punktualnie na umówione spotkanie. Dlatego właśnie, jeśli mam się zobaczyć z kimś w restauracji, zawsze daję mu 60 sekund łaski, zanim wstanę od stołu i udam się do domu.
Istnieje wiele sposobów na obrażenie człowieka. Można drwiąco prychnąć oglądając zdjęcie jego dzieci albo przerąbać go siekierą na pół. Zawsze jednak byłem zdania, że największą możliwą obrazą jest spóźnić się na spotkanie. Najbardziej boli ukłucie tego subtelnego przekazu, tej dyskretnej sugestii, że wasz czas jest wart więcej, niż czas tej drugiej osoby.
');
INSERT INTO texts (name, text) VALUES ('tekst64.txt', '
Starał się w ogóle nie myśleć i wszystko szło jak najlepiej. Udawał, że nie interesuje go już praca, jaką wykonywał dawniej, skoro przecież i tak już jej wykonywać nie mógł. Ale wmawiał sobie, że kiedyś opisze jeszcze tych wszystkich ludzi, tych bogatych, że w gruncie rzeczy nie jest jednym z nich, lecz szpiegiem w ich krainie, że pewnego dnia opuści ją i zacznie pisać o niej i że będzie to dla odmiany opowieść człowieka, który wie, o czym pisze. Ale przecież wiadomo było, że nie napisze już nic, każdy dzień bowiem spędzony na niepisaniu, w komforcie, w towarzystwie ludzi, którymi pogardzał, osłabiał jego wrażliwość, jego wolę do pracy, w końcu więc zupełnie przestał pracować.
');
INSERT INTO texts (name, text) VALUES ('tekst65.txt', '
Rzeka płynęła cicho; była wartka i gładka. Zanim wspiął się na niewielkie wzniesienie, aby tam rozbić obóz, popatrzał ze skraju łąki na rzekę i wynurzające się pstrągi. Wypływały w pogoni za owadami, które po zachodzie słońca nadleciały tu z moczarów na drugim brzegu. Pstrągi wyskakiwały z wody, aby je chwytać. Nick, idąc wąskim pasmem łąki nad rzeką, widział, jak skakały wysoko. Owady musiały teraz siadać na powierzchni, bo spojrzawszy w dół rzeki widział, że pstrągi żerują na całej jej długości. Jak okiem sięgnąć, wypływały, pozostawiając na wodzie kółka niby padający deszcz.
');
INSERT INTO texts (name, text) VALUES ('tekst66.txt', '
Kiedy się zbudził, słońce już wzeszło i namiot zaczynał się nagrzewać. Nick wypełznął na zewnątrz pod zasłaniającą wyjście moskitierą, ażeby przyjrzeć się porankowi. Kiedy się czołgał niosąc spodnie i buty, czuł pod dłońmi wilgotną trawę. Słońce właśnie wyszło zza wzgórza. Przed sobą miał łąkę, rzekę i bagna. Na zielonych moczarach po drugiej stronie rzeki rosły brzozy.
Był wczesny poranek, rzeka płynęła wartko czysta i gładka. Około dwustu jardów dalej leżały w poprzek niej trzy pnie drzewne. Powyżej woda była lśniąca i głęboka. Kiedy Nick patrzał, wydra przebiegła po kłodach przez rzekę i zniknęła na moczarach.
');
INSERT INTO texts (name, text) VALUES ('tekst67.txt', '
Niekiedy znajdowałem owady na podmokłych łąkach w trawie albo pod paprociami i używałem ich do łowienia. Były to chrząszcze i owady mające nogi podobne do łodyżek trawy, czerwie kryjące się w starych, przegniłych pniach, białe poczwarki o brunatnych, chwytliwych łebkach, które nie trzymały się na haczyku i znikały w zimnej wodzie, kleszcze siedzące pod kłodami, gdzie można było znaleźć glisty, które wwiercały się w ziemię, gdy tylko podniosłem kłodę. Raz użyłem salamandry wydobytej spod starego pnia. Była bardzo mała, zgrabna, żwawa, ładnie ubarwiona. Miała drobne nóżki i próbowała pochwycić nimi haczyk, i potem już więcej nie brałem salamandry, choć znajdowałem je bardzo często.
');
INSERT INTO texts (name, text) VALUES ('tekst68.txt', '
Czasem potok biegł przez otwartą łąkę i wtedy w suchej trawie łapałem koniki polne, których używałem jako przynęt albo chwytałem je i wrzucałem do potoku patrząc, jak unoszą się na wodzie i zataczając koła na powierzchni pływają porwane prądem i nikną, gdy wynurzy się pstrąg. Niekiedy w ciągu nocy łowiłem w czterech lub pięciu różnych potokach, zaczynając możliwie jak najbliżej źródła i idąc z ich biegiem. Jeżeli skończyłem za szybko i jeszcze zostawało mi trochę czasu, łowiłem znowu wzdłuż całego strumienia; zaczynałem od jego ujścia do jeziora i szedłem w górę, usiłując pochwycić te pstrągi, które wymknęły mi się za pierwszym razem.
');
INSERT INTO texts (name, text) VALUES ('tekst69.txt', '
Przez otwarte okno wpadało słońce i prześwietlało stojące na stole butelki. Butelki były do połowy opróżnione. Zebrało się w nich na piwie trochę piany, ale nie dużo, bo piwo było bardzo zimne. Pieniło się, kiedy je lałeś do wysokich kufli. Wyjrzałem przez otwarte okno na białą drogę. Rosnące przy niej drzewa były okryte pyłem. Za drogą było zielone pole i potok. Nad potokiem rosły drzewa i stał tartak z kołem wodnym. Przez otwarty bok tartaku dojrzałem długi drewniany kloc z werżniętą weń piłą, która podnosiła się i opadała. Zdawało się, że nikt jej nie obsługuje. Po zielonym polu łaziły cztery wrony. Jedna siedziała na drzewie i patrzała.
');
INSERT INTO texts (name, text) VALUES ('tekst70.txt', '
Na dworze śnieg sięgał wyżej okna. Słońce wpadało przez okno i oświetlało mapę wiszącą na sosnowych deskach ściany chaty. Słońce było wysoko i światło wpadało do środka ponad wierzchem śniegu. Od strony wejścia przekopano wzdłuż chaty rów i każdego pogodnego dnia ciepło słońca promieniowało od ściany na śnieg i poszerzało rów. Był koniec marca. Major siedział przy stole pod ścianą. Przy drugim stole siedział jego adiutant.
Major miał wokoło oczu dwa białe kręgi od ciemnych okularów, które chroniły jego twarz przed odblaskiem słońca od śniegu. Reszta twarzy najpierw się przypiekła, potem opaliła, a potem znowu przypiekła przez opaleniznę.
');
INSERT INTO texts (name, text) VALUES ('tekst71.txt', '
Zjeżdżaliśmy z przełęczy przez zalesioną okolicę. Przy drodze stały stosy worków z węglem drzewnym, a między drzewami widzieliśmy chaty węglarzy. Była niedziela i droga wznosiła się i opadała, ale wciąż schodziła w dół z wyniosłości przełęczy, prowadząc przez karłowaty las i przez wioski. Wokoło wiosek rozciągały się pola winorośli. Pola były brunatne, winorośle gęste i krzaczaste. Domy były białe, a na ulicach grali w kręgle mężczyźni w niedzielnych ubraniach. Pod ścianami niektórych domów rosły grusze z gałęziami rozpiętymi jak kandelabry na białych murach. Grusze spryskiwano i ściany domów nosiły metaliczne, niebieskozielone ślady pyłu rozpryskiwanej cieczy.
');
INSERT INTO texts (name, text) VALUES ('tekst72.txt', '
Chodziliśmy do szpitala każdego popołudnia i można było tam dojść różnymi drogami przez miasto o zmierzchu. Dwie prowadziły wzdłuż kanałów, ale te były dłuższe. Jednak żeby się dostać do szpitala, trzeba było zawsze przejść przez któryś mostek na kanale. Miało się trzy mostki do wyboru. Na jednym kobieta sprzedawała przypiekane kasztany. Ciepło było stać przed jej węglowym piecykiem, a kasztany były potem ciepłe w kieszeni. Szpital był bardzo stary i bardzo piękny i wchodziło się tam przez bramę, potem przez dziedziniec i wychodziło bramą po drugiej stronie. Za starym szpitalem stały nowe ceglane pawilony i tam spotykaliśmy się każdego popołudnia.
');
INSERT INTO texts (name, text) VALUES ('tekst73.txt', '
Samotny na środku areny byk ciągle stał nieruchomo. Fuentes, wysoki, o płaskich plecach, szedł ku niemu zuchwale, z rozpostartymi rękami, trzymając w palcach jednej i drugiej dłoni cienkie czerwone drążki, kolcami skierowane w przód. Szedł prosto. Za nim, nieco z boku, zbliżał się peon z kapą. Byk spojrzał na niego i poruszył się wreszcie.
Oczy jego śledziły Fuentesa, który teraz przystanął w miejscu. Odchylił się w tył i zawołał coś do byka. Machnął banderillami, a błysk stalowych kolców zwrócił uwagę zwierza.
Byk zadarł ogon i zaszarżował.
');
INSERT INTO texts (name, text) VALUES ('tekst74.txt', '
Wagonik kolejki zachybotał się po raz ostatni i stanął. Nie mógł jechać dalej: śnieg grubą warstwą przysypał tor. Wichura smagająca obnażone stoki góry zbiła śnieg w twardą skorupę. W wagoniku bagażowym Nick smarował narty; potem wsunął buty w żelazne uchwyty i zacisnął klamry wiązań. Bokiem wyskoczył z wagoniku, obrócił się i pochylony, ciągnąc za sobą kijki, pomknął w dół zbocza. Na bieli poniżej zjawiał się, niknął i znów zjawiał się George. Pęd powietrza, raptowny spadek, szalony zjazd falistą stromizną góry zacierały wszystkie myśli. Po całym ciele rozchodziło się tylko cudowne uczucie pędu i żeglowania w powietrzu.
');
INSERT INTO texts (name, text) VALUES ('tekst75.txt', '
Padało. Deszcz ociekał z drzew palmowych. Woda stała kałużami na wyżwirowanych ścieżkach. W hotelu mieszkało tylko dwoje Amerykanów. Nie znali nikogo z ludzi, których mijali na schodach wychodząc czy wracając do swego pokoju. Pokój ten był na pierwszym piętrze, od strony morza. Wychodził też na park i pomnik wojenny. W ogrodzie były wysokie palmy i zielone ławki. W pogodny dzień zawsze był tam jakiś artysta ze sztalugami. Artystom podobały się palmy, które tam rosły, i żywe barwy hoteli stojących naprzeciw ogrodu i morza. Włosi przychodzili z daleka, żeby popatrzeć na pomnik. Był on odlany z brązu i lśnił na deszczu.
');
INSERT INTO texts (name, text) VALUES ('tekst76.txt', '
Pierwszy matador dostał rogiem w tę rękę, w której trzymał szpadę, i tłum go wygwizdał. Drugi matador pośliznął się i byk trafił go w brzuch, i matador uchwycił się rogu jedną ręką, a drugą przycisnął do rany, i byk rąbnął go o ścianę, i róg wylazł, a on upadł na piasek, a potem wstał jak pijany wariat i próbował pobić ludzi, którzy go wynosili, i wołał o szpadę, ale zemdlał. Wtedy wyszedł ten młodziak i musiał zabić pięć byków, bo nie może być więcej niż trzech matadorów, i przy ostatnim byku był już taki zmęczony, że nie mógł wbić szpady. Ledwie mógł podnieść rękę. Próbował pięć razy, a tłum siedział cicho, bo byk był dobry i wyglądało na to, że będzie albo on, albo byk, i w końcu mu się udało.
');
INSERT INTO texts (name, text) VALUES ('tekst77.txt', '
Dzień był strasznie gorący. Zagrodziliśmy most zupełnie doskonałą barykadą. Była po prostu wspaniała. Duża stara krata z kutego żelaza, z frontu jakiegoś domu. Za ciężka, żeby ją podnieść, a można było przez nią strzelać, i tamci musieliby przełazić przez wierzch. Była świetna. Próbowali przez nią przeleźć i ostrzelaliśmy ich z odległości czterdziestu jardów. Rzucili się na nią, a potem przybiegli sami oficerowie i próbowali ją usunąć. To była absolutnie doskonała przeszkoda. Ich oficerowie byli wspaniali. Strasznie się zmartwiliśmy, kiedy przyszła wiadomość, że skrzydło się załamie i że musimy się wycofać.
');
INSERT INTO texts (name, text) VALUES ('tekst78.txt', '
Wozy utknęły na przestrzeni trzydziestu mil na drodze do Karagaczu. Bawoły i inne bydło ciągnęły je przez błoto. Ani początku, ani końca. Tylko wozy wyładowane wszystkim, co ci ludzie posiadali. Starzy mężczyźni i kobiety, przemoczeni na wylot, szli obok popędzając zwierzęta. Marica płynęła wezbrana żółto prawie aż po sam most. Na moście utworzył się zwarty zator wozów, między którymi dreptały wielbłądy. Kawaleria grecka parła wzdłuż tego pochodu. Kobiety i dzieci siedziały na wozach zawalonych materacami, lustrami, maszynami do szycia, tobołkami. Jedna z kobiet rodziła dziecko, a jakaś młoda dziewczyna trzymała nad nią koc i płakała. Deszcz padał przez całą ewakuację.
');
INSERT INTO texts (name, text) VALUES ('tekst79.txt', '
Mój ojciec przechowywał w dolnej szufladzie swego głębokiego biurka starą i piękną mapę naszego miasta. Był to cały wolumen in folio pergaminowych kart, które pierwotnie spojone skrawkami płótna, tworzyły ogromną mapę ścienną w kształcie panoramy z ptasiej perspektywy. Zawieszona na ścianie, zajmowała niemal przestrzeń całego pokoju i otwierała daleki widok na całą dolinę Tyśmienicy, wijącej się falisto bladozłotą wstęgą, na całe pojezierze szeroko rozlanych moczarów i stawów, na pofałdowane przedgórza, ciągnące się ku południowi, naprzód z rzadka, potem coraz tłumniejszymi pasmami, szachownicą okrągławych wzgórzy, coraz mniejszych i coraz bledszych, w miarę jak odchodziły ku złotawej i dymnej mgle horyzontu.
');
INSERT INTO texts (name, text) VALUES ('tekst80.txt', '
Spacerowałem po alei eukaliptusowej gdy wtem zza drzewa wylazła krowa. Przystanąłem i spojrzeliśmy sobie oko w oko. Jej krowiość zaskoczyła do tego stopnia mą ludzkość - ten moment, w którym spojrzenia nasze się spotkały, był tak napięty - że stropiłem się jako człowiek, to jest w moim, ludzkim, gatunku. Uczucie dziwne i bodaj po raz pierwszy przeze mnie doznane - ten wstyd człowieczy wobec zwierzęcia. Pozwoliłem żeby ona spojrzała na mnie i zobaczyła mnie - to nas zrównało - wskutek tego stałem się także zwierzęciem - ale dziwnym, powiedziałbym nawet, niedozwolonym. Poszedłem dalej podejmując przerwany spacer, ale poczułem się nieswojo... w naturze, która osaczała mnie zewsząd i jakby... oglądała mnie.
');
INSERT INTO texts (name, text) VALUES ('tekst81.txt', '
Dzieło, choćby zrodzone z najczystszej kontemplacji, powinno być tak napisane aby zapewnić autorowi przewagę w jego rozgrywce z ludźmi. Styl, który nie umie bronić się przed sądem ludzkim, który wydaje swego twórcę na pastwę byle kretyna, nie spełnia swojego najważniejszego zadania. Lecz obrona przed tymi opiniami jest możliwa tylko wtedy, gdy zdobędziemy się na pokorę i wyznamy, jak dalece są one dla nas ważne - nawet gdy pochodzą od głupca. Dlatego bezbronność sztuki wobec sądów ludzkich jest smutnym następstwem jej dumy: ach, ja jestem wyższy ponad to, ja liczę się tylko ze zdaniem rozumnych!
');
INSERT INTO texts (name, text) VALUES ('tekst82.txt', '
Nie dajcie się zastraszyć. Słowo "ja" jest tak zasadnicze i pierworodne, tak wypełnione najbardziej namacalną a przeto najuczciwszą rzeczywistością, tak nieomylne jako przewodnik i surowe jako probierz, iż zamiast nim gardzić należałoby paść przed nim na kolana. Myślę, że raczej nie jestem jeszcze dość fanatyczny w moim przejęciu się sobą i że nie umiałem - w strachu przed innymi ludźmi - oddać się temu powołaniu-zadaniu z dość kategoryczną bezwzględnością, pchnąć tę sprawę dość daleko. Ja jestem najważniejszym i bodaj jedynym moim problemem: jedynym ze wszystkich moich bohaterów, na którym mi naprawdę zależy.
');
INSERT INTO texts (name, text) VALUES ('tekst83.txt', '
- A ducha dziejów znamy? A ducha cywilizacji helleńskiej? A ducha galijskiej, ducha umiaru i dobrego smaku? A ducha nikomu prócz mnie nie znanego sielankopisarza z XVI wieku, który pierwszy użył wyrażenia "pępek"? A ducha języka? Jak się mówi: "wykonywa", czy też "wykonuje"?
Pytanie zaskoczyło mnie. Sto tysięcy duchów przydusiło nagle mego ducha, bąknąłem, że nie wiem, on zaś spytał, co mi jest wiadomo o duchu Kasprowicza i jaki był stosunek poety do chłopów, po czym zapytał jeszcze o pierwszą miłość Lelewela. Chrząknąłem i rzuciłem ukradkowo wzrokiem na paznokcie - paznokcie były czyste, ściągaczki nie było.
');
INSERT INTO texts (name, text) VALUES ('tekst84.txt', '
Szyld oberży przedstawiał przedmiot bardzo zwyczajny w dziedzinie sztuk pięknych, ale niezmiernie rzadko spotykany w naturze, a mianowicie niebieskiego lwa z trzema łapami w powietrzu, kołyszącego się na środkowym pazurze czwartej łapy. W pobliżu widać było biuro towarzystwa ubezpieczeń od pożarów i lombard, magazyny handlarza zbożem i handlarza płótnem, sklep siodlarza, handlarza wódek, korzennika i sklep z obuwiem. Ten ostatni jednocześnie zaopatrywał mieszkańców w kapelusze, czapki, wszelką odzież, bawełniane parasole i rozmaite pożyteczne wiadomości. Stał tu prócz tego mały dom z czerwonej cegły, z niewielkim brukowanym podwórzem, o którym każdy wiedział, że należy do adwokata.
');
INSERT INTO texts (name, text) VALUES ('tekst85.txt', '
W Pythonie wartości, a nie zmienne, posiadają typ - tak więc Python jest językiem z typami dynamicznymi, podobnie jak Lisp, a w przeciwieństwie do Javy. Wszystkie wartości przekazywane są przez referencję. W porównaniu z innymi językami z typami dynamicznymi Python sprawdza typy w umiarkowanym stopniu. Nie jest ani tak liberalny, jak Perl, ani tak restrykcyjny jak Caml. Dla typów numerycznych zdefiniowana jest automatyczna konwersja, tak więc możliwe jest np. mnożenie liczby zespolonej przez liczbę całkowitą typu long bez rzutowania. Jednak w przeciwieństwie do Perla nie ma np. automatycznej konwersji pomiędzy napisami i liczbami; liczba nie jest prawidłowym argumentem dla operacji napisowej.
');
INSERT INTO texts (name, text) VALUES ('tekst86.txt', '
Luke Skywalker szedł przez szary, stalowy korytarz "Gwiazdy Śmierci". Miał na sobie matowo czarny kombinezon porucznika floty imperialnej. Prawie całe jego wyposażenie: przebranie, fałszywy identyfikator oraz kilka niepozornych urządzeń zawieszonych na pasie, zostało dostarczone przez rebeliancki wywiad. Jedyną jego bronią był miecz świetlny schowany w kaburze. Do tej pory wszystko szło doskonale, mundur i dokumenty umożliwiły mu w miarę bezproblemowe dostanie się na stację w roli zastępcy dowódcy szwadronu nowych myśliwców Tie Defender. Od teraz jednak musiał zachowywać ostrożność - w sektorze, w którym się znajdował, obecność pilota była wysoce podejrzana.
');
INSERT INTO texts (name, text) VALUES ('tekst87.txt', '
Obserwując te krople dochodzę do wniosku, że ich życie jest tak samo pełne niespodzianek jak życie każdego człowieka. Zdawałoby się, że one same wybierają kierunek, w którym chcą płynąć. To jednak są tylko pozory, zupełnie jak w ludzkim życiu. Możliwe, że część z nich chciałaby płynąć właśnie środkiem szyby. Możliwe, że chciałyby płynąć wspólnie właśnie z tą kroplą, z którą się połączyły. Wystarczy jednak jedna, mała nierówność na szybie, może jakiś przyczepiony, milimetrowych rozmiarów paproszek i ich drogi się rozchodzą. Nagle jedna z nich spływa całkiem po krawędzi. Płynie szybko, bez przerwy a druga płynie powoli i nierówno, jakby nie potrafiła się odnaleźć w tej nowej sytuacji.
');
