INSERT INTO texts (name, text) VALUES ('tekst01.txt', '
Chêtnie by mia³ jedn± z nich. Ale nie by³o warto. By³y tak ³adnie szablonowe. Podoba³ mu siê ten szablon. By³ podniecaj±cy. Ale Krebs nie mia³ ochoty przechodziæ przez to ca³e gadanie. Nie mia³ do¶æ silnej ochoty na dziewczynê. Mimo to lubi³ na nie patrzeæ. Tylko ¿e nie by³o warto. Szczególnie teraz, kiedy wszystko zaczyna³o siê znowu dobrze uk³adaæ. Siedzia³ na ganku i czyta³ ksi±¿kê o wojnie. By³a to praca historyczna i czyta³ o wszystkich walkach, w których bra³ udzia³. Uwa¿a³, ¿e to najciekawsza lektura, jak± dot±d mia³. ¯a³owa³, ¿e nie ma tam wiêcej map. Z przyjemno¶ci± zapatrywa³ siê na przeczytanie wszystkich naprawdê dobrych prac historycznych, kiedy uka¿± siê z dobrymi, szczegó³owymi mapami. Teraz naprawdê dowiadywa³ siê czego¶ o wojnie. W swoim czasie by³ dobrym ¿o³nierzem. A to by³o wa¿ne.
');
INSERT INTO texts (name, text) VALUES ('tekst02.txt', '
Nie chcia³ te¿ ¿adnej konsekwencji. Nie chcia³ nigdy wiêcej jakichkolwiek konsekwencji. Chcia³ sobie ¿yæ bez nich. Poza tym w gruncie rzeczy nie potrzebowa³ dziewczyny. Tego nauczy³o go wojsko. Mo¿na by³o pozowaæ na to, ¿e musi siê mieæ dziewczynê. Prawie ka¿dy to robi³. Ale to nie by³a prawda. Nie potrzebowa³o siê dziewczyny. To w³a¶nie naj¶mieszniejsze. Najpierw kto¶ siê przechwala³, ¿e dziewczyny nic dla niego nie znacz±, ¿e nigdy o nich nie my¶li, ¿e wcale go nie obchodz±. Potem przechwala³ siê, ¿e nie mo¿e sobie daæ rady bez dziewczyn, ¿e musi je mieæ stale, ¿e nie mo¿e bez nich zasn±æ. To wszystko by³o k³amstwo. K³amstwem by³o i jedno i drugie. Nie potrzebowa³e¶ dziewczyny, je¶li o niej nie my¶la³e¶. Tego nauczy³ siê w wojsku.
');
INSERT INTO texts (name, text) VALUES ('tekst03.txt', '
Min±³ nas du¿y samochód jad±cy bardzo szybko i p³achta b³otnistej wody chlusnê³a na nasz± ch³odnicê i przedni± szybê. Automatyczne wycieraczki zaczê³y poruszaæ siê tam i z powrotem, rozprowadzaj±c jej warstwê na szybie. Zatrzymali¶my siê w Sestri na obiad. Restauracja nie by³a ogrzewana i siedzieli¶my w paltach i kapeluszach. Przez okno widzieli¶my nasz wóz. By³ pokryty b³otem i sta³ przy jakich¶ ³odziach, które wci±gniêto na brzeg poza zasiêg fal. W restauracji widzia³o siê parê w³asnego oddechu. Pasta asciutta by³a dobra; wino mia³o posmak a³unu i dolali¶my do niego wody. Pó¼niej kelner przyniós³ befsztyki z przysma¿anymi kartoflami.
');
INSERT INTO texts (name, text) VALUES ('tekst04.txt', '
Doktor powiedzia³ mi, ¿e ¿ona majora, która by³a bardzo m³oda i z któr± o¿eni³ siê dopiero wtedy, gdy jako inwalida zosta³ ostatecznie wyeliminowany z wojny, umar³a na zapalenie p³uc. Chorowa³a tylko kilka dni. Nikt siê nie spodziewa³, ¿e umrze. Major przez trzy dni nie przychodzi³ do szpitala. Potem zjawi³ siê o zwyk³ej godzinie, z czarn± opask± na rêkawie munduru. Kiedy wróci³, na ¶cianach wisia³y du¿e oprawione fotografie przedstawiaj±ce wszelkie rodzaje ran przed i po leczeniu za pomoc± aparatów. Przed tym aparatem, którego u¿ywa³ major, by³y trzy fotografie kompletnie wyleczonych r±k, takich jak jego rêka. Nie wiem, sk±d doktor je wzi±³. Zawsze s³ysza³em, ¿e my pierwsi u¿ywali¶my tych aparatów. Fotografie nie zrobi³y wiêkszego wra¿enia na majorze, bo tylko spogl±da³ przez okno.
');
INSERT INTO texts (name, text) VALUES ('tekst05b.txt', '
Jego twarz pokry³a maska ca³kowitej, ostatecznej rozpaczy wynikaj±cej z wiedzy, która przysz³a za pó¼no. Wielkie ko³o hamulcowe znajdowa³o siê na swoim miejscu, po drugiej stronie wagonu, lecz nie trzyma³a go niczyja rêka. Zamiast niego, rêka ¶ciska³a otwart± Bibliê, le¿±c± grzbietem do góry na pod³odze. Sam Devlin, tak¿e grzbietem do góry, le¿a³ obok swego prowizorycznego pos³ania. Miêdzy jego chudymi ³opatkami stercza³a rêkoje¶æ no¿a. Bellew odwróci³ napiêt± twarz i wpatrzy³ siê têpo w o¶nie¿one sosny na poboczu toru, mijaj±ce go ze ¶wistem z prêdko¶ci± stu mil na godzinê. Prze¿egna³ siê, choæ nie robi³ tego od dzieciñstwa, i strach znikn±³ z jego twarzy. Zast±pi³a go rezygnacja - sier¿ant pogodzi³ siê z nieuchronn± ¶mierci±.
');
INSERT INTO texts (name, text) VALUES ('tekst05.txt', '
Bellew dotar³ do drzwi z ty³u wagonu i rozpaczliwie szarpn±³ za klamkê. Bez skutku - te drzwi równie¿ by³y zamkniête na klucz. Wyci±gn±³ colta i strzeli³, mierz±c tu¿ powy¿ej i nieco z boku zamka. Strzeli³ cztery razy, nie przejmuj±c siê dwoma potencjalnie ¶mierciono¶nymi rykoszetami, które z gwizdem przelecia³y przez wagon - teraz grozi³o im ju¿ wiêksze niebezpieczeñstwo. Po czwartym strzale drzwi ust±pi³y pod rozpaczliwym naciskiem jego d³oni. Wyskoczy³ na tylny pomost. Natychmiast odrzuci³ go podmuch wiatru, który osi±gn±³ bez ma³a si³ê huraganu, oraz wyj±tkowo gwa³towny przechy³ wagonu. W ostatniej chwili obur±cz przytrzyma³ siê porêczy. Colt, którego ¶ciska³ w prawej rêce, wylecia³ na pobocze, kozio³kuj±c w powietrzu. Sier¿ant zdecydowa³ siê na samobójcze ryzyko, lecz miêdzy samobójstwem a nag³± ¶mierci± z innych powodów nie ma istotnej ró¿nicy.
');
INSERT INTO texts (name, text) VALUES ('tekst06.txt', '
Pu³kownik Claremont, którego wybuchowy temperament czêsto dawa³ o sobie znaæ, heroicznie stara³ siê utrzymaæ go na wodzy. By³a to jednak z góry przegrana walka. Pedantyczny i skrupulatny oficer, dla którego rozkaz i porz±dek dzienny by³y rzecz± ¶wiêt±, nie znosi³, kiedy co¶ mu zak³óca³o, a tym bardziej niweczy³o raz powziête plany. Dodaj±c za¶ do tego skrajn± nietolerancjê wobec g³upoty i nieudolno¶ci, trudno siê dziwiæ, ¿e nie potrafi³ on znale¼æ jakiego¶ wentyla bezpieczeñstwa, przez który móg³by dawaæ upust swojej jedynej wadzie, niegodnej tak oficera, jak mê¿czyzny. Stopniowe uwalnianie albo sublimacja gwa³townego - i gwa³townie narastaj±cego - gniewu wywo³anego frustracj± w jego wypadku nie wchodzi³y w rachubê, mimo i¿ oscyluj±ca wokó³ punktu wrzenia w¶ciek³o¶æ nie wp³ywa³a najlepiej na jego ci¶nienie.
');
INSERT INTO texts (name, text) VALUES ('tekst07b.txt', '
A jednak kolejny paradoks sprawi³, ¿e uratowa³y go potencjalnie ¶mierciono¶ne wentylatory. Bez namys³u, instynktownie, wyci±gn±³ rêkê i z³apa³ za jeden z nich. Odniós³ wra¿enie, ¿e co¶ wyrwa³o mu prawe ramiê z barku, wentylator brutalnie wydar³ siê z jego u¶cisku, lecz szybko¶æ, z jak± sun±³, wyra¼nie siê zmniejszy³a. Ponownie wyci±gn±³ rêkê. Znów przeszy³ go dojmuj±cy ból, ale teraz ju¿ ¶lizga³ siê w tempie nieomal spacerowym. Zobaczy³, ¿e zbli¿a siê trzeci i ostatni wentylator. Tym razem obj±³ go obur±cz i zacisn±³ lew± rêkê na prawym nadgarstku. Czu³, ¿e jaka¶ potê¿na si³a znowu wyrywa mu prawe ramiê, czy¿by odros³o mu nowe? Ale trzyma³ siê twardo. Zatoczy³ szeroki ³uk, wypadaj±c nogami poza dach. Ale trzyma³ siê dalej. Wiedzia³, ¿e musi co¶ zrobiæ, bo si³y go opuszczaj±. Powoli, zmagaj±c siê z bólem, podci±gn±³ siê na ¶rodek dachu, doczo³ga³ na ty³ wagonu i nie tyle zszed³, co spad³ na pomost.
');
INSERT INTO texts (name, text) VALUES ('tekst07.txt', '
Widz±c zbli¿aj±c± siê ga³±¼ sosny, nie waha³ siê ani chwili. Wiedzia³, ¿e je¿eli nie zrobi tego teraz, prawdopodobnie nie zdobêdzie siê po raz drugi na tak samobójczy krok. ¯eby z³agodziæ skutki zderzenia, cofn±³ siê szybko, rozk³adaj±c szeroko rêce na wysoko¶ci piersi. Z³apa³ ga³±¼ obur±cz i z przera¿eniem stwierdzi³, ¿e jest o wiele cieñsza ni¿ przypuszcza³ - zmyli³a go gruba warstwa ¶niegu. Ga³±¼ ugiê³a siê. Desperacko zarzuci³ na ni± nogi i wisz±c w ten sposób, szybowa³ pó³ metra nad dachem. Zerkn±³ w dó³. Nie¶wiadom niczego Carlos mign±³ mu zaledwie trzydzie¶ci centymetrów pod plecami i znikn±³ z widoku. Deakin opu¶ci³ nogi i ¿³obi±c obcasami podwójny ¶lad na oblodzonym dachu, spogl±da³ do ty³u. Nagle pu¶ci³ ga³±¼, wiedz±c doskonale, ¿e który¶ ze stercz±cych wentylatorów mo¿e mu wypruæ wnêtrzno¶ci.
');
INSERT INTO texts (name, text) VALUES ('tekst08.txt', '
Jestem przekonany, ¿e wszystkie te dobre uczynki mam do zawdziêczenia mojej taktyce niestosowania przemocy. Gdybym zabiega³ o ponowne przyjêcie mnie do kasty, usi³owa³ j± rozbiæ na poszczególne obozy lub zachowa³ siê prowokacyjnie wobec jej cz³onków, ci z pewno¶ci± odwzajemniliby siê w podobny sposób i zamiast szczê¶liwie unikn±æ burzy po przybyciu z Anglii, wpad³bym w sam wir rozagitowania, kto wie, czy nie uprawianego czê¶ciowo za moimi plecami. Mój stosunek do ¿ony wci±¿ jeszcze nie by³ taki, jakiego pragn±³em. Nawet pobyt w Anglii nie uleczy³ mnie z zazdro¶ci. By³em w dalszym ci±gu drobnostkowy i zazdrosny o byle co, a wszystkie moje najbardziej utajone pragnienia zostawa³y nie zaspokojone.
');
INSERT INTO texts (name, text) VALUES ('tekst09.txt', '
Którego¶ dnia do kuwety stoj±cej w ciemni fotograficznej wpu¶ci³em karpia. Wrzaski niczego nie podejrzewaj±cej dziewczyny rozleg³y siê na ca³± szko³ê. Ten niewinny ¿arcik poci±gn±³ za sob± ¶ledztwo na wielk± skalê. Re¿yserowa³em te¿ bardziej wyrafinowane skecze. Pewnego razu zaaran¿owa³em gwa³town± sprzeczkê z Majewskim. K³óc±c siê zawziêcie, zapomniawszy na pozór o bo¿ym ¶wiecie, przeszli¶my korytarzem, nastêpnie schodami w dó³, a¿ dotarli¶my do gabinetu, gdzie urzêdowa³a u³omna sekretarka rektora, Nina. Grupa kolegów, których wtajemniczyli¶my w sprawê, usi³owa³a nas rozdzieliæ, ale bez skutku.
');
INSERT INTO texts (name, text) VALUES ('tekst10.txt', '
Pary¿ jest miastem stworzonym dla spacerów. Podczas której¶ z naszych nocnych przechadzek - wcze¶niej wkrêcili¶my na studenck± zabawê w Akademii Sztuk Piêknych - zabra³em Gesê, ¿eby pokazaæ jej Hale. Zaledwie o kilka minut od Luwru zapu¶cili¶my siê w w±skie uliczki, zas³ane li¶æmi kapusty i odpadkami wszelkiego rodzaju jarzyn. Widz±c niewielkie na pozór, st³oczone stragany, sklepy i magazyny, trudno by³o uwierzyæ, ¿e st±d rozprowadza siê niemal ca³± ¿ywno¶æ dla Pary¿a i pó³nocnej Francji. Kierowca, który dotrze noc± w g³±b Hal, mo¿e uwa¿aæ siê za szczê¶ciarza, je¶li przed ¶witem uda mu siê wydostaæ z labiryntu ciê¿arówek wioz±cych wszelkiego rodzaju bogactwa: od po³ci wo³owiny do homarów i krêgów ¿ó³tego sera.
');
INSERT INTO texts (name, text) VALUES ('tekst11.txt', '
Pod jednym wzglêdem ksi±¿ka nie odpowiada³a mi: by³em agnostykiem - w równym stopniu nie wierzy³em w szatana jako wcielenie z³a, co w uosobienie Boga. Ca³y pomys³ "Dziecka Rosemary" k³óci³ siê z moj± racjonaln± wizj± ¶wiata. Aby wiêc film sta³ siê wiarygodny, postanowi³em zastosowaæ pewien wybieg: dopu¶ciæ interpretacjê, ¿e nadprzyrodzone prze¿ycia Rosemary s± wytworem jej wyobra¼ni. Ca³a historia ogl±dana z jej punktu widzenia mog³a wydawaæ siê jedynie ci±giem koszmarnych zbiegów okoliczno¶ci, produktem rozgor±czkowanej wyobra¼ni bohaterki. Knowania s±siadów, sabat czarownic, w czasie którego, w obecno¶ci mê¿a, szatan bierze j± przemoc± oraz koñcowa scena przy ko³ysce musia³y mieæ racjonalne wyt³umaczenie. Oto dlaczego przez ca³y film rozmy¶lnie przewija siê niæ dwuznaczno¶ci.
');
INSERT INTO texts (name, text) VALUES ('tekst12b.txt', '
Kiedy ju¿ by³o po wszystkim, ja i moja partnerka ubrali¶my siê i siedz±c na dwóch taboretach, gwarzyli¶my dopijaj±c szampana. Tymczasem sala opustosza³a. Opuszczono kurtynê, ostatni klienci wyszli, a obs³uga ustawia³a krzes³a na stolikach. Orkiestra usadowi³a siê wówczas tu¿ pod nasz± lo¿± i muzycy zagrali wiedeñskiego walca, ¶l±c w nasz± stronê têskne spojrzenia. "Król Pralni" nonszalancko siêgn±³ do kieszeni, wyci±gn±³ gruby plik stuszylingowych banknotów i rozrzuci³ je dostojnym gestem siewcy. Poszybowa³y ku muzykom, jak jesienne li¶cie. Zbierali je dyskretnie, nie uroniwszy ani jednej nuty.
');
INSERT INTO texts (name, text) VALUES ('tekst12.txt', '
Po odkorkowaniu szampana osobnik dyskretnie siê wycofa³. Wówczas dziewczyna zrzuci³a z siebie ubranie i zosta³a tylko w pantoflach na wysokim obcasie, czarnych siatkowych poñczochach i podwi±zkach: wygl±da³a jak postaæ z rysunku Kokoschki. Kiedy mnie rozbiera³a, zerkn±³em, co siê dzieje na dole. Prestidigator z niezwyk³± zrêczno¶ci± prezentowa³ swój numer. Panienka z równ± wpraw± wyczarowa³a prezerwatywê i szybko mi j± na³o¿y³a. Potem goln±wszy sobie szampana siad³a na mnie okrakiem i zabra³a siê do roboty. Zu¿yt± prezerwatywê wrzuci³a do kube³ka z szampanem. Zachowa³em gdzie¶ w pamiêci mglisty obraz nagiego Sama goni±cego po lo¿ach równie nag± dziewczynê.
');
INSERT INTO texts (name, text) VALUES ('tekst13.txt', '
Coraz bardziej nienawidzi³ tego Pope. Cz³owiek mo¿e siê u¶miechaæ, a byæ ³ajdakiem. Bezlitosnym, zdradliwym, wszetecznym, zepsutym ³ajdakiem. Co w³a¶ciwie znacz± te s³owa? Mia³ tylko niejasne pojêcie. Ale ich czar by³ silny, szumia³y mu w g³owie, i zda³o mu siê, ¿e dotychczas nie czu³ do Pope prawdziwej nienawi¶ci; nigdy dot±d nie nienawidzi³ go tak naprawdê, bo nigdy dot±d nie umia³ wypowiedzieæ, jak bardzo go nienawidzi. A teraz mia³ ju¿ te s³owa, s³owa jak bêbny, jak ¶piew i zaklêcia. Te s³owa i dziwna, dziwna opowie¶æ, z której pochodzi³y (nie potrafi³ zebraæ jej w ca³o¶æ, ale i tak by³a cudowna, cudowna), pozwoli³y mu nienawidziæ Pope; uczyni³y tê nienawi¶æ bardziej realn±; nawet samego Pope uczyni³y bardziej realnym.
');
INSERT INTO texts (name, text) VALUES ('tekst14.txt', '
Z³apa³em znów za plazmówkê i bez ceregieli wbi³em mu widelcowate zakoñczenie lufy prosto w serce (to znaczy tam, gdzie wydawa³o mi siê, ¿e ono jest). Aby dobiæ go zupe³nie, wystrzeli³em. Tym razem zaskoczy³ mnie ca³kowicie; zamiast osun±æ siê martwym na ziemiê, zacz±³ miotaæ siê na wszystkie strony jak szaleniec. Z¿eraj±ca go od ¶rodka plazma wydawa³a jakby zagêszczony d¼wiêk ton zgniatanego papieru. W pewnym momencie pomy¶la³em nawet, ¿e wybuchnie i jakie¿ by³o moje zdziwienie, gdy tak w³a¶nie siê sta³o: powietrze przeszy³ g³o¶ny huk, i ca³a górna czê¶æ jego cia³a znik³a w k³êbach ¿ó³tego py³u. Dolna pad³a na ziemiê jak kawa³ czarnego p³ótna. Ci±gn±c za sob± warkocz dymu, co¶ zwêglonego spad³o tu¿ pod moje stopy i poturla³o siê jeszcze przez kilka metrów. To musia³a byæ jego czaszka.
');
INSERT INTO texts (name, text) VALUES ('tekst15.txt', '
Liu Kang wraca³ pó¼nym wieczorem do mieszkania po³o¿onego na przedmie¶ciu Nowego Jorku. Wybra³ tê okolicê specjalnie po to, aby w wolnych chwilach móc bez obaw poæwiczyæ. Nie wszyscy s±siedzi lubi± facetów ubranych w same spodnie, lataj±cych z jednego koñca ogródka na drugi z nogami wysuniêtymi do przodu i wrzeszcz±cych przy tym niemi³osiernie. W momencie, gdy Kang otwiera³ furtkê, wiedzia³ ju¿, ¿e pope³ni³ b³±d. U³amek sekundy pó¼niej upad³ twarz± na chodnik po silnym kopniêciu. Jednak klasztor Szaolin wyrobi³ w nim pewne zachowania które prawdopodobnie uratowa³y mu ¿ycie. B³yskawicznie poderwa³ siê na nogi unikaj±c tym samym mia¿d¿±cego buta. Jeszcze w tej samej sekundzie wyprowadzi³ dwa szybkie ciosy lew± nog± prosto w gard³o pozbawiaj±c przeciwnika oddechu, a chwilê pó¼niej ¿ycia.
');
INSERT INTO texts (name, text) VALUES ('tekst16b.txt', '
Rozejrza³ siê. Woko³o by³ tylko las i droga. Las. Postanowi³, ¿e ukryje siê miêdzy drzewami i poczeka na roboty. Wprawdzie przeciwko trzem mia³ ma³e szanse, ale mia³ nadziejê, ¿e mo¿e siê rozdziel±. Wszed³ g³êbiej w las. Dotychczas roboty trzyma³y siê bezb³êdnie jego ¶ladów. Liczy³, ¿e miêdzy drzewami trochê siê pogubi± i ofiara zamieni siê w my¶liwego. W pewnym momencie zamajaczy³o mu w oddali migaj±ce ¶wiate³ko. Ruszy³ w tamt± stronê. ¦wiate³ko okaza³o siê ma³ym ogniskiem, przy którym siedzia³o dwoje ludzi. A on zna³ tych ludzi.
');
INSERT INTO texts (name, text) VALUES ('tekst16.txt', '
Ucieka³ ju¿ mniej wiêcej dwie godziny. Zaczyna³o mu brakowaæ oddechu. Podczas biegu zastanawia³ siê, jak go znale¼li. Ju¿ wcze¶niej ukry³ siê poza miastem, gdy¿ przewidzia³, ¿e mo¿e zostaæ zdradzony. Teraz gonili go jego dawni przyjaciele. Chcieli go zabiæ. Wszystko by³o dobrze do czasu, gdy w laboratorium opracowano nowy model cyborga, który by³ lepszym wojownikiem ni¿ ludzie. Po tym wszystkim sta³ siê on niepotrzebny. A poniewa¿ za du¿o wiedzia³, chciano go zlikwidowaæ. Trzy wys³ane za nim roboty wpad³y na trop dopiero dwie godziny temu. Od tego czasu zacz±³ siê szaleñczy wy¶cig cz³owieka z maszynami. Przystan±³ i obejrza³ siê za siebie. Za nim rozci±ga³a siê pusta ulica. Ogóln± ciemno¶æ rozja¶nia³y postawione tu i ówdzie latarnie. Wzi±³ g³êbszy oddech i pobieg³ dalej, ale po kilku minutach zatrzyma³ siê ponownie. Zadecydowa³, ¿e najwy¿szy czas przej¶æ do ofensywy.
');
INSERT INTO texts (name, text) VALUES ('tekst17.txt', '
Gdy powiedzia³, ¿e j± kocha, zapyta³a, czy prêdko siê pobior±. Wówczas on o¶wiadczy³, ¿e niestety, ale jest ¿onaty. By³a tym tak zgnêbiona, ¿e chcia³a zaraz i¶æ do domu, a on nie pu¶ci³ jej, dopóki nie obieca³a, ¿e jutro przyjdzie. Nie przysz³a jednak wiêcej, a to dlatego, ¿e zwierzy³a siê nazajutrz kole¿ance z siódmej klasy, pannie Jó¼wiñskiej, ta za¶ wyt³umaczy³a Magdzie wiele rzeczy, o których Magda dotychczas pojêcia nie mia³a. Drug± mi³o¶ci± by³ w³a¶nie brat Toli Jó¼wiñskiej. Zaprzyja¼ni³y siê po tych zwierzeniach i Tola zaprasza³a j± do siebie na potañcówki. Pan Jó¼wiñski by³ bardzo bogatym adwokatem, a Karol studiowa³ na politechnice, mia³ motocykl z wózkiem i kilka razy zabiera³ Magdê a¿ za Wilanów.
');
INSERT INTO texts (name, text) VALUES ('tekst18b.txt', '
Kilkakrotnie odbywano wycieczki do lasów, le¿±cych na Dalekim Zachodzie. Koloni¶ci nie obawiali siê zbyt wysokiej temperatury, bo promienie s³oneczne zaledwie gdzieniegdzie zdo³a³y siê przedrzeæ przez nadzwyczaj gêste sklepienie lasu. Zwiedzili ca³y lewy brzeg Rzeki Mi³osierdzia. Wybieraj±c siê na te wycieczki, zawsze dobrze siê uzbrajali, gdy¿ czêsto zachodzi³y im drogê dziki nadzwyczaj zuchwa³e, z którymi musieli staczaæ uparte walki.
W tej tak¿e porze roku Gedeon i Harbert rozpoczêli straszn± wojnê z jaguarami. Obaj my¶liwi uzupe³niali siê wzajemnie. Harbert by³ nadzwyczaj odwa¿ny, reporter odznacza³ siê zimn± krwi± i przezorno¶ci±. Dziêki tym zapalonym my¶liwym ju¿ przesz³o dwadzie¶cia prze¶licznych skór jaguarów zdobi³o ¶ciany wielkiej sali Granitowego Pa³acu, z czego mo¿na by³o wnosiæ, ¿e potrafi± osi±gn±æ zamierzony cel i oczyszcz± wyspê z tych niebezpiecznych zwierz±t.
');
INSERT INTO texts (name, text) VALUES ('tekst18.txt', '
12 lutego ca³a instalacja by³a ju¿ wykoñczona, i zaraz Cyrus zapyta³ Ayrtona, czy co z³ego nie zasz³o w owczarni; w kilka minut odebra³ zadowalaj±c± odpowied¼. Penkroff nie posiada³ siê z rado¶ci i codziennie rano i wieczór wysy³a³ telegramy do owczarni, na które zawsze odbiera³ ¿±dane odpowiedzi.
Urz±dzenie telegrafu zapewnia³o podwójn± korzy¶æ: po pierwsze mogli zawsze wiedzieæ, czy Ayrton nie opu¶ci³ chaty, a po wtóre, nie pozwalali mu zostawaæ w zupe³nym odosobnieniu. Oprócz tego Cyrus odwiedza³ go regularnie przynajmniej raz na tydzieñ, a ilekroæ Ayrton przybywa³ do Granitowego Pa³acu, przyjmowano go ¿yczliwie.
');
INSERT INTO texts (name, text) VALUES ('tekst19.txt', '
Powrócili wszyscy do niej, aby przyjrzeæ siê lepiej. Mia³a piêæ stóp d³ugo¶ci, a trzy szeroko¶ci; by³a starannie zamkniêta i pokryta grub± skór±, przybit± mosiê¿nymi gwo¼dziami; dwie pró¿ne beczu³ki, szczelnie zaszpuntowane, przywi±zane by³y do jej boków mocnymi powrozami. Nie znaæ na niej by³o ¿adnego uszkodzenia, co mo¿na by przypisaæ temu, ¿e morze wyrzuci³o j± na piasek, a nie miêdzy ska³y. Nadto, przyjrzawszy siê jej bacznie, trudno by³o nie poznaæ, ¿e nied³ugo przebywa³a w morzu i niedawno osiad³a na piasku.
Morze tymczasem przybiera³o ci±gle i woda dochodzi³a ju¿ do skrzyni. Nab i Penkroff odrzucili obsypuj±cy j± piasek i wkrótce ³ódka, ci±gn±c za sob± skrzyniê, oddali³a siê od w±skiego pasa ziemi, który nazwano Cyplem Skrzyni.
');
INSERT INTO texts (name, text) VALUES ('tekst20b.txt', '
Bardzo mo¿liwe, ¿e w Gedeonie odezwa³a siê ¿y³ka dziennikarska i pragn±³ wys³aæ w ¶wiat krótki artykulik streszczaj±cy przygody kolonistów Wyspy Lincolna przewiduj±c, jak wielkiego tam narobi rozg³osu. Opisa³ wszystko, co siê sta³o, tre¶ciwie na æwiartce papieru, i do³±czy³ usiln± pro¶bê, aby ktokolwiek znajdzie to pismo, przes³a³ je natychmiast do redakcji New York Heralda. Nastêpnie w³o¿y³ karteczkê do ma³ego woreczka z gumowego p³ótna i przywi±za³ go nie do nogi, lecz do szyi albatrosa, gdy¿ te ptaki odpoczywaj± zwykle na powierzchni morza. Gdy wreszcie wypu¶cili powietrznego goñca, z widocznym wzruszeniem patrzyli, dopóki nie znikn±³ im z oczu, lec±c ku zachodowi.
');
INSERT INTO texts (name, text) VALUES ('tekst20.txt', '
W tym czasie koloni¶ci po raz pierwszy spróbowali porozumieæ siê z lud¼mi. Gedeon Spilett od dawna nosi³ siê z tym, aby powierzyæ ma³± karteczkê go³êbiowi lub w zakorkowanej dobrze butelce rzuciæ j± w morze. Zaniecha³ jednak tego zwa¿ywszy, ¿e niepodobna by³o przypu¶ciæ, aby go³±b lub butelka mog³y przebyæ odleg³o¶æ tysi±ca dwustu mil, które oddziela³y wyspê od zamieszkanej ziemi. W ostatnim dniu czerwca uda³o siê Harbertowi schwytaæ albatrosa, którego przedtem zrani³ w nogê strza³em z fuzji. By³ to wielki ptak, którego rozpostarte skrzyd³a mia³y dziesiêæ stóp d³ugo¶ci, móg³ wiêc przebyæ Ocean Spokojny.
');
INSERT INTO texts (name, text) VALUES ('tekst21.txt', '
Ca³a robota zajê³a dwadzie¶cia cztery godziny. Po wielu próbach uda³o im siê porobiæ knoty z w³ókien ro¶linnych, które umoczone w roztopionej stearynie, utworzy³y ¶wiece; brak³o im tylko wybielania i politury. Wprawdzie nie dorównywa³y one ¶wiecom, których knoty nasycone s± kwasem borny, spalaj± siê w miarê topienia stearyny i dlatego nie potrzebuj± obcinania, ale Cyrus Smith zrobi³ dobre szczypce i ¶wiece te bardzo by³y u¿yteczne podczas d³ugich wieczorów.
Przez ca³y ten miesi±c pracowali gorliwie w nowym mieszkaniu. Stolarskiej roboty nie zabrak³o, a oprócz tego udoskonalano i uzupe³niano narzêdzia.
Mogli ju¿ zrobiæ sobie no¿yczki i poobcinaæ w³osy, spadaj±ce prawie na ramiona. Nab i Harbert nie mieli zarostu, lecz towarzysze ich wygl±dali okropnie, wiêc teraz mogli przynajmniej skróciæ brody, w±sy i faworyty.
');
INSERT INTO texts (name, text) VALUES ('tekst22.txt', '
O jedenastej przed po³udniem ¿eglarze byli ju¿ tylko o dwie mile od wyspy, czy raczej wysepki, jak j± nazwa³ Harbert, przypatrzywszy siê jej lepiej, i mogli ju¿ rozró¿niæ grupy rozmaitych drzew. Dziwi³o ich, ¿e nie dostrzegli nigdzie dymu, a na wybrze¿u ¿adnego sygna³u pozwalaj±cego wnosiæ, ¿e cz³owiek tu siê znajduje i wzywa pomocy przep³ywaj±cych statków. Dokument znaleziony w butelce nie pozwala³ jednak w±tpiæ o tym.
Statek przesuwa³ siê ostro¿nie przez w±skie przesmyki miêdzy ska³ami, które Penkroff ¶ledzi³ bacznie, stoj±c na dziobie statku, gdy tymczasem Harbert zastêpowa³ go przy sterze. Na koniec oko³o po³udnia zbli¿ono siê do piaszczystego wybrze¿a, zwiniêto ¿agiel i rzucono kotwicê.
');
INSERT INTO texts (name, text) VALUES ('tekst23.txt', '
Trzy dni pó¼niej wielki, czarny lincoln continental sun±³ zat³oczonymi ulicami Waszyngtonu. Na tylnym siedzeniu, oddzielonym od kierowcy szyb±, siedzia³ starszy, dystyngowany pan o starannie zaczesanych, srebrzystoszarych w³osach. O takim odcieniu mówi siê "salt and pepper". Obok niego na siedzeniu spoczywa³a aktówka z czarnej, cielêcej skóry. By³y w niej trzy kartki papieru, egzemplarz gazety z zakre¶lonym flamastrem komunikatem umieszczonym u do³u drugiej strony oraz przypiête spinaczem t³umaczenie tekstu na jêzyk angielski. Jego tre¶æ sprawia³a, ¿e starszy pan my¶la³ intensywnie, a nie by³y to my¶li weso³e.
');
INSERT INTO texts (name, text) VALUES ('tekst24b.txt', '
Dzieñ by³ ³adny, wiêc po ¶niadaniu poszed³ na spacer, ciesz±c siê niepowtarzaln± atmosfer±, jaka zawsze panuje tam, dok±d przybywa parê tysiêcy m³odych ludzi ze wszystkich stron ¶wiata. Kto¶ wpad³ na pomys³ znakomicie rozwi±zuj±cy problem poruszania siê po rozleg³ym terenie wioski, wprowadzaj±c ma³e rowerki. Od razu cieszy³y siê olbrzymim powodzeniem. By³o ich w wiosce tysi±ce i w niektórych miejscach trzeba by³o uwa¿aæ, by nie zostaæ staranowanym przez ho¿± dziewojê, pêdz±c± na z³amanie karku. Niektórzy zreszt± specjalnie wystawali w takich miejscach.
Polscy floreci¶ci wymy¶lili zabawê w pi³kê rowerowo-no¿n± na trawie i odt±d na placyku przed gmachem, gdzie mieszkali zbiera³a siê coraz liczniejsza grupka kibiców nowego sportu. Jerzy wzi±³ raz tylko udzia³ w takim meczu, ale st³uk³ piszczel i od tego czasu postanowi³ udzielaæ siê wy³±cznie jako sympatyk tego sportu.
');
INSERT INTO texts (name, text) VALUES ('tekst24.txt', '
W¶ród u¶miechów, poklepywañ i gratulacji, czu³, ¿e jeszcze jest co¶ wart, on i jego ambicja. Pojawiaj±ce siê od czasu do czasu na horyzoncie widmo Padwy stawa³o siê coraz bardziej zwiewne i wyblak³e. Stosunki z Dropakiem by³y zimne, lecz poprawne. ¯aden nie ryzykowa³ ostatecznej rozgrywki. Nie stwarza³o to najlepszej atmosfery nawet tu, w Tokio, ale na szczê¶cie gor±czka przedstartowa zepchnê³a wszystko na dalszy plan.
Uspokoiwszy siê nieco poszed³ do mikroskopijnej ³azienki, wzi±³ tusz, po czym u³o¿y³ siê na kozetce i momentalnie zapad³ w sen.
Ranek przyniós³ wyja¶nienie wczorajszych niepokojów. Okaza³o siê, ¿e prze¿y³ pierwsze w ¿yciu trzêsienie ziemi. Nie by³o to silne, gazety po¶wiêca³y mu zaledwie kilkuwierszowe wzmianki.
');
INSERT INTO texts (name, text) VALUES ('tekst25b.txt', '
W ekipie s± przekonani, ¿e ma zapewnione ju¿ miejsce w finale, gdy¿ ostatni± przeszkod± jest W³och Cesare Salwadore, zawodnik zdecydowanie s³abszy.
Ale kto mo¿e byæ pewny czego¶ w sporcie do koñca? Gdy wywo³uj± ich walkê, Paw³owski jest trochê zmêczony, natomiast W³och - jakby chcia³ zmieniæ niepochlebn± opiniê o sobie - atakuje z furi± i trafia. Jerzy szybko przezwyciê¿a kryzys i zaskoczenie, ale impet W³ocha dzia³a deprymuj±co. Pierwsz± walkê wygra³ zaledwie jednym trafieniem, drug± przegra³ do trzech i o wszystkim ma zadecydowaæ ostatnia, trzecia walka.
W³osi ju¿ szalej± z rado¶ci. Im w ogóle niewiele trzeba, ca³± grup± masuj± Salwadoremu nogi, ha³as czyni± niemo¿liwy, a jego przeciwnik...
');
INSERT INTO texts (name, text) VALUES ('tekst25.txt', '
Tu ju¿ zaczynaj± siê problemy. Co prawda system ten daje jeszcze szansê w repasa¿ach, ale przecie¿ wiadomo, ¿e je¿eli nie wyeliminuje swych rywali, to sam odpadnie. ¯ona jest pierwszy raz z nim na mistrzostwach ¶wiata i od rana nie opuszcza hali. Trochê to przeszkadza, ale z drugiej strony...
Do rundy ósemkowej wchodzi bez problemu. Dawno ju¿ mu siê tak dobrze nie walczy³o. Jakby znik³y gdzie¶ k³opoty i zmory, zw³aszcza jedna z nich. Jakby nie spêdzi³ setek godzin na treningach, jakby nie by³o tych trudnych momentów, kiedy siê ma wszystkiego do¶æ, chce siê rzuciæ z rozmachem, a¿ zajêczy, szablê i maskê i pój¶æ gdzie¶ przed siebie.
');
INSERT INTO texts (name, text) VALUES ('tekst26b.txt', '
Z przera¿eniem czeka³ na szczêk metalu, na wybuch i wdarcie siê wody, na potwierdzenie tej strasznej pewno¶ci, ¿e znalaz³ siê w pu³apce, ¿e woda go zadusi, zanim zd±¿y ruszyæ siê z miejsca.
Której¶ nocy uda³o mu siê zasn±æ, mimo ¿e ostrzegano o grupie okrêtów podwodnych gdzie¶ w pobli¿u. Zapad³ w drzemkê po godzinie napiêtej czujno¶ci i w³a¶nie wtedy, pomiêdzy snem a jaw±, us³ysza³ potworny wybuch, jak gdyby w samym wnêtrzu okrêtu. Kiedy wyskoczy³ z koi, rozleg³ siê klakson na alarm i zaraz potem pospieszny tupot nóg. Pêdzi³ co si³ do trapu, do otwartego nieba. Czu³, jak zalewa go fala ¶lepego strachu.
');
INSERT INTO texts (name, text) VALUES ('tekst26.txt', '
Móg³ zej¶æ na dó³ i spaæ w swej kabinie bez przerwy a¿ do rana. Nigdy jednak z tego nie korzysta³, chyba na samym pocz±tku i na koñcu rejsu, kiedy p³ynêli po wodach spokojnych i bezpiecznych. Ju¿ w samym fakcie uk³adania siê do snu poni¿ej linii wodnej by³o co¶, co drêczy³o jego wyobra¼niê. Zdawa³o mu siê zupe³nie wykluczone, aby w ci±gu tej nocy torpeda mog³a nie trafiæ w korwetê. A je¶li trafi, to wedrze siê na pewno a¿ tu, do jego kabiny... W bezsenne noce na otwartym bezkresnym Atlantyku wraca³y koszmarne my¶li. Okrêt stale ko³ysa³ siê i stêka³, a woda przep³ywa³a o kilka cali od jego pos³ania. Poci³ siê z lêku, wpatrywa³ siê w gród¼ i w nity, które trzyma³y razem cienkie blachy poszycia. Tylko to poszycie dzieli³o go od ciemnej wody.
');
INSERT INTO texts (name, text) VALUES ('tekst27b.txt', '
Tomlinson czu³ siê lepiej obs³uguj±c pospiesznie klientów, którzy ¿±dali gor±cych pasztecików lub suchej kie³basy (wy³±cznie za gotówkê, bez ¿adnych reklamacji!), ni¿ w wytworniejszym ¶wiecie mesy oficerskiej. Poniewa¿ jednak Lockhart dawnym zwyczajem zasiada³ do swych samotnych posi³ków z ksi±¿k± w rêku, nie dra¿ni³y go ani niedba³a obs³uga, ani bezbarwne jedzenie.
Korweta by³a przycumowana tu¿ obok "Viperous", na którym tak¿e czyszczono kot³y. Po raz pierwszy Lockhart mia³ mo¿no¶æ z bliska ogl±daæ niszczyciela. Korzystaj±c z tego s±siedztwa, odwiedza³ do¶æ czêsto kolegê na bratnim okrêcie. By³ nim podporucznik ze s³u¿by zawodowej, pozostawiony równie¿ na dy¿urze, gdy inni poszli na urlop.
');
INSERT INTO texts (name, text) VALUES ('tekst27.txt', '
Lockhart wyci±gn±³ los, ¿e zostanie jako dy¿urny oficer na okrêcie. Jego kolej na urlop mia³a przyj¶æ nastêpnym razem. Nie uwa¿a³ siê wcale za skrzywdzonego. Ostatnio dosta³ awans na porucznika. Dodatkowy z³ocisty pasek b³yszcza³ na rêkawie, potêguj±c poczucie odpowiedzialno¶ci. Poza tym móg³ za¿yæ odpoczynku, jakiego potrzebowa³. Wolne chwile spêdza³ na urlopie - czyta³ i s³ucha³ radia, rozpl±tywa³ skomplikowany wêze³ ostatnich miesiêcy. Na "Compass Rose" wygaszono kot³y, wentylatory nie dzia³a³y, by³o ch³odno i cicho. Dziwne wra¿enie sprawia³a korweta, przedtem zawsze aktywna i ruchliwa, a teraz zawieszona w mg³awicy lenistwa, jak on sam. Mia³ bardzo ma³o do roboty, a ju¿ zupe³nie nic takiego, co wymaga³oby skupienia. Po ¶niadaniu robi³ przegl±d za³ogi i zapowiada³ Phillipsowi, co trzeba w tym dniu sprz±tn±æ i co pomalowaæ.
');
INSERT INTO texts (name, text) VALUES ('tekst28b.txt', '
Wci±¿ siê mylili, spó¼niali, robota nie wychodzi³a. Dziwili siê, kiedy co¶ posz³o g³adko, a gdy siê nie uda³o, spogl±dali posêpnie, obojêtnie. Pozostawiony sam sobie, Ferraby pewnie by okrzep³ i stopniowo doprowadzi³ swój dzia³ do stanu sprawno¶ci. Lecz Bennett cel ³atwiejszy od Lockharta. £azi³ wiêc bez ustanku na pok³ad nad ruf± i przechyliwszy siê przez reling, zasypywa³ m³odszego oficera mnóstwem uwag i sprzecznych rozkazów, kruszy³ na proch tê odrobinê ufno¶ci w swe si³y, jak± Ferraby zdo³a³ odbudowaæ. Dosz³o do tego, ¿e Ferraby ze strachem rozpoczyna³ æwiczenia, które musia³ prowadziæ co dzieñ w czasie ca³ego postoju w porcie.
');
INSERT INTO texts (name, text) VALUES ('tekst28.txt', '
Ferraby, odosobniony na rufie wraz ze swoimi bombami, nie móg³ siê pochwaliæ sukcesem w podci±gniêciu swych ludzi do jakiego¶ zno¶nego poziomu. Obydwu starszym marynarzom trudno by³o cokolwiek zarzuciæ - obaj byli zupe³nie pewni i energiczni. Torpedysta Wainwright odbezpiecza³ i nastawia³ bomby, a tak¿e sam je wyrzuca³. Starszy marynarz Tonbridge sta³ na czele ca³ej obs³ugi wyrzutni. Lecz reszta ludzi by³a w wiêkszo¶ci poni¿ej przeciêtnego poziomu. Praca ich polega³a na szybkim wk³adaniu bomb do opró¿nionych przedzia³ów. Wymaga³o to zgranego wspó³dzia³ania zespo³u ludzi. Ferraby rozporz±dza³ do¶æ przypadkowym kompletem marynarzy z maszyny, którzy nie mieli wachty, oraz radiotelegrafistów nie kwapi±cych siê zbytnio do pracy na pok³adzie, gdzie wiatr przewiewa³ cz³owieka na wylot.
');
INSERT INTO texts (name, text) VALUES ('tekst29b.txt', '
Starszy marynarz Tonbridge mia³ dwadzie¶cia trzy lata, by³ dzieckiem londyñskich slumsów i mia³ za sob± siedem lat s³u¿by w Royal Navy. Fakt, ¿e nie uciek³ od tej próby, ¿e potrafi³ okazaæ sprawno¶æ w dzia³aniu, wykracza³ swoj± tre¶ci± poza wszelkie normalne pochwa³y.
Robili, co tylko mogli. Wios³owali w ciemno¶ci, kieruj±c siê wo³aniem, przera¿eni do szpiku ko¶ci zduszonym krzykiem ludzi, którzy tonêli, zanim zdo³ali podp³yn±æ. Ze wszystkich si³ starali siê ratowaæ i pomagaæ. Wyci±gnêli czternastu ludzi: jeden ju¿ nie ¿y³, drugi by³ konaj±cy, o¶miu rannych, a pozostali oszo³omieni wstrz±sem i ca³kowicie wyczerpani. Niewiele brakowa³o, a by³oby piêtnastu.
');
INSERT INTO texts (name, text) VALUES ('tekst29.txt', '
Gdy Tonbridge uj±³ za rumpel i spojrza³ w jego kierunku chc±c wzi±æ w³a¶ciwy kurs, rozleg³ siê ponad wod± zgrzyt rozdzieranej stali i statek zacz±³ siê pogr±¿aæ. Tonbridge patrzy³, wstrz±¶niêty do g³êbi groz± i lêkiem. Nigdy nie widzia³ czego¶ podobnego, nigdy nie powierzono mu jeszcze takiego zadania. Nie³atwo bêdzie je spe³niæ jak nale¿y. Wystarczy³o, ¿e odeszli od "Compass Rose" w sam ¶rodek ciemno¶ci, ¿e widzieli, jak ich okrêt rozp³ywa siê w mroku, ¿e konwój tak¿e znik³ w oddali, oni za¶ byli sami w maleñkiej ³odzi pod niebem pe³nym gwiazd, po¶ród wielkiego, nieprzyjaznego oceanu. Ale to, na co musieli patrzeæ teraz, podobne by³o raczej do zmory sennej ni¿ do jawy: storpedowany statek zanurza³ siê w ich oczach, ludzie, miotaj±c siê w wodzie, krzyczeli rozpaczliwie, dusz±cy zapach ropy niós³ siê ciê¿k± fal± w powietrzu.
');
INSERT INTO texts (name, text) VALUES ('tekst30b.txt', '
Potworny zgie³k sk³êbiony nad konwojem osi±gn±³ punkt kulminacyjny w chwili, gdy samolot zrzuci³ dwie bomby na czo³o ¶rodkowej kolumny: jedna upad³a w morze, wzbijaj±c ogromny, pierzasty s³up wody, po³yskuj±cy w po¶wiecie ksiê¿yca; druga trafi³a w cel. Trzasnê³a z metalicznym szczêkiem w statek, którego nie mogli dojrzeæ i którego na pewno ju¿ nigdy nie zobacz±. Bo zaraz po pierwszym wybuchu rozleg³ siê drugi. Potê¿na pomarañczowa ³una o¶wietli³a widmowym blaskiem konwój i ca³e niebo nad konwojem. Pod takim ciosem ka¿dy statek, obojêtne - ma³y czy du¿y, musia³ natychmiast rozlecieæ siê w drzazgi. Wyrzucone w powietrze szcz±tki statku z pluskiem spada³y znów do morza w promieniu pó³ mili od miejsca eksplozji.
');
INSERT INTO texts (name, text) VALUES ('tekst30.txt', '
Atakuj±cy samolot lecia³ nisko nad ¶rodkiem konwoju, ¶cigany i smagany ogniem dzia³ przeciwlotniczych z kilkudziesiêciu statków równocze¶nie. Samolotu nie by³o widaæ, lecz jego drogê znaczy³y p³on±ce wstêgi pocisków ¶wietlnych, rozwijaj±ce siê w olbrzymi wachlarz nad czo³em konwoju. Powsta³ straszliwy zgie³k - warkot samolotu dr±¿y³ ciemno¶æ, hucza³y setki dzia³ naraz, na kilku statkach rycza³y syreny alarmowe. Prawdziwym piek³em musia³ byæ ¶rodek konwoju, gdzie ze wszystkich statków prano w nisko lec±cy samolot, nie troszcz±c siê o to, co znajdzie siê na linii celu. Stali na rufie, tu¿ nad wod± umykaj±c± wartkim strumieniem spod ¶ruby, i patrzyli, czekali, usi³owali przewidzieæ, w któr± stronê poleci samolot po skoñczonym ataku. Nad nimi, na platformie 47-milimetrowego dzia³a, marynarze z obs³ugi stali w he³mach na g³owie, nieruchomi na tle ciemnego nieba, gotowi do oddania strza³u, gdy przyjdzie ich kolej. Ale nie przysz³a ich kolej, gotowe do u¿ycia ta¶my pocisków nie zosta³y u¿yte.
');
INSERT INTO texts (name, text) VALUES ('tekst31.txt', '
Teoria narastaj±cych defektów opiera siê na innym za³o¿eniu - stopniowym zu¿ywaniu komórek, spowodowanym ci±g³ym przeprowadzaniem przez nie niezbêdnych do ¿ycia reakcji chemicznych, które powoli zatruwaj± ich mechanizmy. Mechanizmy obronne komórki po prostu po pewnym czasie siê wyczerpuj± i zaczyna ona siê starzeæ a¿ w koñcu umiera. Najbardziej prawdopodobn± przyczyn± tak szybkiego zu¿ywania siê komórek s± tzw. wolne rodniki, grupa zwi±zków chemicznych, bêd±cych produktem ubocznym procesów przemian niektórych zwi±zków. Te zwi±zki chemiczne kiedy ju¿ zostan± uwolnione w komórce, uszkadzaj± cz±steczki niezbêdne do jej naprawy.
');
INSERT INTO texts (name, text) VALUES ('tekst32.txt', '
Do tej chwili wyk³ad Golema nie odbiega wiele od rewelacji wspó³czesnych genetyków, jest te¿, co ciekawe, zadziwiaj±co zbie¿ny z g³o¶n±, a powsta³± niezale¿nie i w zbli¿onym czasie ksi±¿k± Richarda Dawkinsa Samolubny gen. W±tek nowy pojawi siê w momencie, gdy Lem, g³osem komputera, pocznie dywagowaæ nad kwesti± uwik³ania Rozumu w drabinê ewoluuj±cych gatunków. Powie nam wówczas, ¿e Rozum nie tyle jest ukoronowaniem doskonal±cych siê funkcji organicznych, ile ko³em ratowniczym rzuconym zdefektowanym, niedoskona³ym w³a¶nie, produktom pó¼nych etapów biologicznej kreacji.
');
INSERT INTO texts (name, text) VALUES ('tekst33.txt', '
Ju¿ chcia³em skierowaæ siê na powrót w bezmiar przestrzeni, gdy dostrzeg³em, ¿e jaka¶ malutka postaæ daje mi z do³u znaki. Zamkn±wszy silnik, splanowa³em szybko i osadzi³em wehiku³ w pobli¿u grupy malowniczych ska³, na których wznosi³ siê spory budynek z ciosanego kamienia. Na moje spotkanie bieg³ polem ros³y starzec w bia³ym habicie dominikanina. By³ to, jak siê okaza³o, ojciec Lacymon, prze³o¿ony wszystkich misji dzia³aj±cych na obszarach pobliskich gwiazdozbiorów w promieniu sze¶ciuset lat ¶wietlnych. Okolica ta liczy oko³o piêciu milionów planet, w tym dwa miliony czterysta tysiêcy zamieszkanych. Ojciec Lacymon, dowiedziawszy siê o przyczynie, która sprowadzi³a mnie w te strony, wyrazi³ wspó³czucie, zarazem za¶ rado¶æ z mego przybycia, bo jak mi rzek³, jestem pierwszym cz³owiekiem, jakiego widzi od siedmiu miesiêcy.
');
INSERT INTO texts (name, text) VALUES ('tekst34.txt', '
Pytanie, które zosta³o pomy¶lane nie doczeka³o siê pomy¶lnej odpowiedzi, a to zaowocowa³o podejrzeniem w stosunku do le¿±cego przede mn± kalafiora. Postanowi³em rozkroiæ go na pó³ aby przyjrzeæ siê mu od ¶rodka. Tak te¿ zrobi³em. W ¶rodku kalafiora by³... najzwyklejszy ¶rodek kalafiora, nic szczególnego. Znaczy³o to zapewne, ¿e ten kalafior by³ najzupe³niej zdrowy - przynajmniej od ¶rodka. No to sekcja ugotowanego kalafiora zrobiona, ale co to za czarne ma³e drobinki?? Czy to aby jest normalne u takiego ugotowanego kalafiora? Przed skonsumowaniem tej ro¶liny postanowi³em zaistnia³± sytuacjê zbadaæ osobi¶cie.
');
INSERT INTO texts (name, text) VALUES ('tekst35.txt', '
Otó¿ pisarz to w gruncie rzeczy ¶winia. Ostatni cham. Nie, to zbyt ³agodne okre¶lenia. To kat. Morderca. Spójrzcie - tworzy ¶wiaty, zapala s³oñca, ziszcza ludzi - zupe³nie jak Pan Bóg. Tylko, ¿e on je potem niszczy. Pomy¶lcie, ile ksi±¿ek nie powsta³o dla jednego opowiadania, ile¿ dzie³ zosta³o zamordowanych w zarodku, by mog³o powstaæ jedno. To ju¿ znamy, gdzie¶ zapewne s³yszeli¶my. Ale to nie jest jeszcze najgorsze. Mo¿na to z³o¿yæ na karby po¶wiêcenia, musi zgin±æ jeden, by móg³ ¿yæ inny, nie ma tutaj mowy o ¿adnej niehumanitarno¶ci. Lecz czy nie pomy¶leli¶cie nigdy, ¿e pisarz mo¿e sobie tworzyæ ¶wiaty dla samej zabawy i potem je sobie obserwowaæ, a¿ sczezn± - z jego winy.
');
INSERT INTO texts (name, text) VALUES ('tekst36.txt', '
Klawiatura to taka wspania³a, przydatna i wygodna rzecz. Dlaczego w takim razie, siedz±c przed ni± kilka godzin, nie jestem w stanie napisaæ ani jednego sensownego zdania? Zlecenie jest, termin oddania te¿, wiem nawet, jakie bêdzie honorarium. Nie bêdzie zbyt wysokie, ale zawsze co¶. Zreszt± nie piszê dla zarobku. Robiê to tylko dlatego, ¿e lubiê. Mimo wszystko, tylko siedzê i patrzê w okno. Szukam pomys³ów, gdzie tylko mogê. Patrzê na deszcz, widzê jak jego krople bardzo powoli sp³ywaj± po szybie. £±cz± siê z innymi i odp³ywaj± dalej, w tylko sobie znanym kierunku. Przypomina to trochê ludzkie ¿ycie. To znaczy, te krople deszczu, one s± jak ludzie.
');
INSERT INTO texts (name, text) VALUES ('tekst37.txt', '
By³ przeciêtn± m³od± osob±, chodzi³ do przeciêtnej szko³y ¶redniej, przeciêtnie siê uczy³, przeciêtnie wygl±da³. ¯y³ w przeciêtno¶ci i razem z ni±. Nic nie m±ci³o mu spokoju, mia³ swoje ¿ycie, ze zwyk³ymi problemami. Wiedzia³, ¿e jest jak wszyscy, ale wcale mu to nie przeszkadza³o. Nie lubi³ siê wyró¿niaæ, to mog³o przynie¶æ wy³±cznie k³opoty. Mia³ kolegów i kole¿anki, normaln± rodzinê, dobre widoki na przysz³o¶æ. Lubi³ ogl±daæ telewizjê, graæ na komputerze. Robili to przecie¿ wszyscy. Czu³ siê bezpiecznie. S±dzi³, ¿e trudno o lepsze szczê¶cie. Myli³ siê.
');
INSERT INTO texts (name, text) VALUES ('tekst38.txt', '
Ma³o jest chwil w ¿yciu, w których by cz³owiek doznawa³ wiêkszej przykro¶ci, nie zjednywaj±c sobie przy tym ¿adnego wspó³czucia, jak wówczas, gdy odbywa polowanie na swój w³asny kapelusz. Trzeba mieæ wielki zasób zimnej krwi i zdolno¶æ do szybkiej decyzji, by go z³owiæ. Najlepsza metoda polega na tym, by biec równolegle do przedmiotu naszych zabiegów, zachowaæ najwiêksz± przezorno¶æ, umieæ skorzystaæ ze sposobnej chwili, stopniowo wyprzedzaæ, potem nagle pochyliæ siê, uj±æ kapelusz za rondo i mocno osadziæ go na g³owie, wdziêcznie u¶miechaj±c siê podczas tej gonitwy, jak gdyby¶my sami, jak wszyscy inni, widzieli w tym tak dobry ¿art.
');
INSERT INTO texts (name, text) VALUES ('tekst39.txt', '
Widok, jaki mia³ przed oczyma, móg³by zachwyciæ ka¿dego nawet w mniejszym stopniu zdolnego do uniesieñ nad wiejsk± przyrod±. Po lewej stronie wznosi³ siê mur, w wielu miejscach poszczerbiony, ponur± sw± mas± panuj±c nad zielonymi brzegami rzeki Medway. Zwoje bluszczu smutno wieñczy³y czarne blanki, a pêki morskich ro¶lin, zwieszonych na kamieniach, dr¿a³y za powiewem wiatru. Poza tymi zwaliskami wznosi³ siê stary zamek, którego wie¿a bez dachów i wal±ce siê mury ¶wiadczy³y o ubogiej wielko¶ci owych chwil, gdy szczêk broni i dono¶ne ¶piewy rozlega³y siê pod wspania³ymi arkadami.
');
INSERT INTO texts (name, text) VALUES ('tekst40.txt', '
Jak wszyscy ludzie, którzy maj± jeden ze zmys³ów rozwiniêty ponad ludzk± potrzebê, ojciec by³ bardzo nerwowy. I oprócz tego by³ sentymentalny, i jak wszyscy sentymentalni ludzie potrafi³ okazywaæ okrucieñstwo i obra¿aæ siê na ca³y ¶wiat. Nie mia³ wiele szczê¶cia, choæ nie zas³ugiwa³ na takie pomijanie przez los. Zgin±³ w potrzasku, który sam krótko przedtem pomaga³ zastawiaæ. A nim zgin±³ wszyscy po kolei w jaki¶ sposób go w ¿yciu oszukali. Uczuciowi ludzie s± tak czêsto oszukiwani. Nicholas nie móg³by jeszcze napisaæ historii ojca, chocia¿ mia³ zamiar uczyniæ to w przysz³o¶ci. My¶la³ o ojcu z tego okresu, kiedy by³ jeszcze ma³ym ch³opcem, wdziêcznym za dwie rzeczy: ³owienie ryb i polowanie.
');
INSERT INTO texts (name, text) VALUES ('tekst41.txt', '
Radio nie dzia³a³o zbyt dobrze, dopóki nie zapad³ zmrok. Mówiono, i¿ to dlatego, ¿e w ziemi jest tyle rudy czy te¿ co¶ tam z górami, ale w ka¿dym razie nie dzia³a³o dobrze, dopóki na dworze nie zaczê³o siê ¶ciemniaæ; natomiast w nocy dzia³a³o doskonale i kiedy jedna stacja koñczy³a audycjê, mo¿na by³o przesun±æ siê dalej na zachód i wyszukaæ nastêpn±. Ostatni±, jak± siê odbiera³o, by³o Seattle w stanie Waszyngton, i kiedy tam przestawali nadawaæ o czwartej nad ranem, w szpitalu z uwagi na ró¿nicê czasu by³a pi±ta rano, a o szóstej mog³o siê ³apaæ porannych rewelersów z Minneapolis. Pan Frazer wyobra¿a³ sobie, jak wygl±daj± wysiadaj±c z tramwaju przed ¶witem i nios±c swoje instrumenty.
');
INSERT INTO texts (name, text) VALUES ('tekst42.txt', '
Asfaltowa szosa urwa³a siê. Droga by³a teraz wy¿wirowana; zostawiwszy za sob± dolinê jechali¶my pod górê miêdzy dwoma wzgórzami. Droga zakrêca³a i zaczyna³a pi±æ siê coraz wy¿ej. Ziemia na wzgórzach by³a czerwona, bo¿ydrzew rós³ tu szarymi kêpami, i w miarê jak droga podchodzi³a wy¿ej, otwiera³ siê widok nad wzgórzami i nad p³aszczyzn± doliny a¿ ku górom. By³y teraz ju¿ dalej i jeszcze bardziej przypomina³y Hiszpaniê. Droga wi³a siê i znowu piê³a pod górê, a przed nami kilka pardw k±pa³o siê w piasku na drodze. Kiedy podjechali¶my bli¿ej, zerwa³y siê, trzepocz±c szybko skrzyd³ami, a potem poszybowa³y d³ugim skosem i siad³y na stoku wzgórza poni¿ej.
');
INSERT INTO texts (name, text) VALUES ('tekst43.txt', '
Dzieñ by³ s³oneczny i mro¼ny. Ziemia pokryta by³a szronem, tak i¿ zdawa³o siê, ¿e wszystkie nagie ga³êzie drzew, krzaki i poszycie, wszystka trawa, a nawet go³a ziemia zosta³a zawerniksowana cienk± warstw± lodu. Zabra³em m³odego irlandzkiego setera na krótki spacer po szosie i wzd³u¿ zamarzniêtej ³achy, ale trudno by³o chodziæ, a nawet staæ na szklistej powierzchni. Rudy pies ¶lizga³ siê i potyka³, a ja sam upad³em ciê¿ko dwa razy i raz upu¶ci³em dubeltówkê, która pojecha³a daleko po b³yszcz±cym lodzie. Sp³oszyli¶my stado kuropatw spod wysokiego gliniastego nasypu. Zestrzeli³em dwie, a reszta zniknê³a mi z oczu ponad szczytem nasypu.
');
INSERT INTO texts (name, text) VALUES ('tekst44.txt', '
Opowiem wam o szarañczy amerykañskiej. Ta wiêksza, co lataj±c wydaje odg³os trochê przypominaj±cy grzechotnika, kiedy grzechocze grzechotkami, taki bardzo suchy d¼wiêk, ma skrzyde³ka o ¿ywej barwie. Owady te bywaj± jasnoczerwone albo ¿ó³te, prêgowane czarno, ale skrzyde³ka roz³a¿± im siê na kawa³ki w wodzie i przez to nie nadaj± siê na przynêtê, podczas gdy ta ¶rednia br±zowa jest t³usta, jêdrna, soczysta i mogê j± poleciæ, o ile mo¿na polecaæ co¶, z czym panowie prawdopodobnie nigdy siê nie spotkaj±. Muszê jednak¿e podkre¶liæ, ¿e nie zdo³acie uzbieraæ dostatecznego zapasu tych owadów na ca³y dzieñ ³owienia, je¿eli bêdziecie je ³apaæ rêkami albo usi³owali trafiæ kijem.
');
INSERT INTO texts (name, text) VALUES ('tekst45.txt', '
Odpocz±³em i powios³owa³em z powrotem. Ju¿ siê zrobi³o pó¼ne popo³udnie. Jeszcze raz znurkowa³em z kluczem, ale nic z tego nie wysz³o. Ten klucz by³ za lekki. Nie warto by³o nurkowaæ bez porz±dnego m³otka albo czego¶ ciê¿kiego, czym da³oby siê co¶ zrobiæ. Wiêc znowu uwi±za³em klucz do osêka, patrzy³em przez szk³o, grzmoci³em i wali³em w szybê, a¿ klucz siê urwa³ i widzia³em go dobrze, wyra¼nie przez moje szkie³ko, jak zsuwa³ siê w dó³ po kad³ubie statku, a potem wsi±k³ w ruchomy piasek i ju¿ go nie by³o. Nie mog³em nic zrobiæ. Klucz poszed³, chwytak straci³em, wiêc powios³owa³em z powrotem do ³odzi. Nie mia³em ju¿ si³y, ¿eby wci±gn±æ sk³adak na ³ód¼, a s³oñce zni¿y³o siê porz±dnie.
');
INSERT INTO texts (name, text) VALUES ('tekst46.txt', '
Widzia³em wszystko ostro i wyra¼nie. Maszt stercza³ ukosem z wody, bo statek le¿a³ na boku. Dziób nie by³ bardzo g³êboko. Mog³em stan±æ na literach nazwy statku na dziobie i g³owê mieæ akurat nad wod±. Ale najbli¿szy iluminator by³ ze dwana¶cie stóp g³êbiej. Ledwie go mog³em siêgn±æ osêkiem i spróbowa³em rozbiæ szybê, ale nie da³em rady. Szk³o by³o za grube. Wiêc pop³yn±³em z powrotem do ³odzi, wzi±³em klucz francuski, przywi±za³em do koñca osêka, ale i tym nic nie zrobi³em. No i takem tam patrza³ przez szk³o na ten liniowiec; wszystko na nim by³o, ja przyp³yn±³em pierwszy i ani rusz nie mog³em siê do niego dobraæ. A musia³o na nim byæ towaru za jakie¶ piêæ milionów dolarów.
');
INSERT INTO texts (name, text) VALUES ('tekst47.txt', '
P³askie kamienie, którymi by³ wy³o¿ony dziedziniec, l¶ni³y od czysto¶ci, jak posadzka w ko¶ciele. Nachylone g³owy smoków, którymi koñczy³y siê rynny, wypluwa³y deszczówkê do cysterny, a gzymsy okien na wszystkich piêtrach zdobi³y kolorowe doniczki, pe³ne kwitn±cych b³awatków i heliotropów. Dalej ogrodzenie, zrobione z zaostrzonych pali, zamyka³o sad, ogród, na którego klombach uk³adano kwiaty w monogramy, szpalery winogradu, wreszcie placyk do gry w krêgle, ulubionej rozrywki paziów. Po drugiej stronie zamku by³a psiarnia, stajnie, piekarnia, t³ocznia i spichrze. Wszystko otacza³ szeroki pas ³±ki przeznaczonej na pastwisko, zamkniêtej gêstym i kolczastym ¿ywop³otem.
');
INSERT INTO texts (name, text) VALUES ('tekst48.txt', '
W dali rozleg³o siê pianie kura. Inne mu odpowiedzia³y. Wstawa³ dzieñ i za gajem pomarañcz zobaczy³ dach pa³acu. Odetchn±³ z ulg± i spostrzeg³, ¿e tu¿, tu¿ nad zbo¿em podlatuj± czerwone kuropatwy. Zdj±³ p³aszcz i zarzuci³ na nie jak siatkê. Kiedy go podniós³, znalaz³ tylko jednego ptaka, od dawna zdech³ego i gnij±cego.
To rozczarowanie by³o sro¿sze od poprzednich. Znowu schwyci³a go ¿±dza mordu. W braku zwierz±t powyrzyna³by chêtnie ludzi. Wbieg³ z tarasu na taras, uderzeniem piê¶ci otworzy³ drzwi, ale kiedy by³ na schodach, obraz umi³owanej ¿ony wzruszy³ mu serce. Na pewno ¶pi jeszcze, zrobi jej niespodziankê. Zdj±wszy sanda³y, obróci³ cicho klucz i wszed³.
');
INSERT INTO texts (name, text) VALUES ('tekst49.txt', '
Ma³y stó³, niewygodny sto³ek, pos³anie z suchych li¶ci i trzy gliniane garnki stanowi³y ca³y jego maj±tek. Dwie dziury w murze s³u¿y³y za okna. Z jednej strony ja³owe roz³ogi i rozsiane gdzieniegdzie blade stawy rozpo¶ciera³y siê tak daleko, ¿e wzrok siê w nich gubi³. Ogromna rzeka toczy³a przed chat± zielonawe wody. Na wiosnê zgni³e opary unosi³y siê z mokrej ziemi. W czasie suszy porywisty wiatr podnosi³ i pêdzi³ tumany kurzu. Kurz przenika³ wszêdzie, trzeszcza³ miêdzy zêbami i woda do picia robi³a siê b³otnista. Pó¼niej przylatywa³y roje komarów tn±cych bezustannie, brzêcz±cych dniem i noc±. Potem chwyta³y srogie mrozy, nadaj±c przedmiotom twardo¶æ granitu.
');
INSERT INTO texts (name, text) VALUES ('tekst50.txt', '
Temperatura w maszynowni dosz³a do stu siedemnastu stopni. Przez ¶wietlik i przez kratownicê nad kot³owni± dochodzi³y gniewne g³osy. Dudni³y g³ucho we wnêtrzu, eksploduj±c ni st±d, ni zow±d, zmieszane z brzêkami i zgrzytami metalowymi, jakby tam w dole k³ócili siê ludzie z ¿elaza o krtaniach z br±zu. Drugi mechanik wsiad³ na palaczy, ¿e dopu¶cili do tego, by ci¶nienie pary spad³o. By³ to si³acz muskularny jak kowal i zwykle bano siê go jak ognia. Ale tym razem palacze odpowiadali mu zawziêcie i z furi± rozpaczy zatrzaskiwali drzwi palenisk. Potem gwa³t usta³ nagle i drugi mechanik, ociekaj±c smarem i potem, jak wyci±gniêta z komina miot³a kominiarza, wychyli³ siê z kot³owni.
');
INSERT INTO texts (name, text) VALUES ('tekst51.txt', '
Tarcza zachodz±cego s³oñca mala³a, a gasn±cy br±z jego bezpromiennego ¿aru sprawia³ wra¿enie, jak gdyby miliony wieków minê³o od poranku do zachodu s³oñca. Gêsta ³awica chmur ukaza³a siê z pó³nocnej strony; mia³a posêpny, ciemnooliwkowy kolor, le¿a³a na morzu nisko i nieruchomo, niby namacalna przeszkoda na drodze statku, który szed³ ku niej chwiejnie; rzek³by¶, ¿ywe stworzenie wleczone na ubój. Miedziany zmierzch rozproszy³ siê powoli i z zapadniêciem ciemno¶ci na niebie wyst±pi³o mrowie du¿ych, rozchwianych jak na wietrze gwiazd migoc±cych niezwykle i zdaj±cych siê wisieæ bardzo nisko ponad ziemskim globem.
');
INSERT INTO texts (name, text) VALUES ('tekst52.txt', '
Blade ¶wiat³o b³yskawicy zap³onê³o doko³a, jak gdyby rzucone do wnêtrza jaskini, do czarnego, tajemnego sanktuarium morza maj±cego, miast posadzki, kipiel z wrz±cych grzyw piany. Na krótkie, ¶ciskaj±ce serce mgnienie w ponurym ¶wietle zamajaczy³a masa postrzêpionych chmur zawis³ych nisko, wyd³u¿ona sylwetka parowca w skoku, czarne postacie ludzi uwiêzionych na pomo¶cie. A gdy doko³a zapad³y ciemno¶ci, wówczas dopiero nadesz³o prawdziwe uderzenie. By³o to co¶ przera¼liwego i gwa³townego jak rozbicie naczynia z w¶ciek³o¶ci±. By³a to eksplozja doko³a okrêtu z pora¿aj±cym wstrz±sem, z grzmotem, pêdem wielkich wód, jak gdyby olbrzymia grobla po nawietrznej zosta³a wysadzona w powietrze.
');
INSERT INTO texts (name, text) VALUES ('tekst53.txt', '
Po wielu latach wiernej s³u¿by mój zegarek zacz±³ siê psuæ. Tak, wiem, ¿e móg³bym oddaæ go do naprawy, ale poniewa¿ naprawdê jestem najpunktualniejsz± osob± na ¶wiecie, jak sobie poradzê, kiedy nie bêdê go mia³? Mam korzystaæ z faz Ksiê¿yca? Chodzenie bez zegarka na rêce jest dla mnie gorsze ni¿ chodzenie bez spodni. Oczywi¶cie, ¿e mam zegarek zapasowy. Jest bardzo ³adny. Niestety, moje oczy s± ju¿ tak stare i zu¿yte, ¿e nie jestem w stanie w³a¶ciwie odczytaæ wskazañ z jego tarczy. W konsekwencji na zesz³otygodniowe spotkanie z moim dobrym znajomym przyby³em z godzinnym opó¼nieniem. To za¶, w moim przekonaniu, jest gorsze od zwymiotowania na niego zaraz po przyj¶ciu.
');
INSERT INTO texts (name, text) VALUES ('tekst54.txt', '
S³uch absolutny budzi szczególne zainteresowanie, gdy¿ wskazuje na zupe³nie swoisty obszar jako¶ci percepcyjnych, którego wiêkszo¶æ z nas nie jest w stanie nawet sobie wyobraziæ; chodzi przy tym o wyizolowan± umiejêtno¶æ, bez ¿adnego wyra¼nego zwi±zku z muzykalno¶ci± czy czymkolwiek innym, która pokazuje, w jaki sposób przy jej kszta³towaniu geny wspó³pracuj± z do¶wiadczeniem. Dawne mniej czy bardziej intuicyjne przekonanie, ¿e s³uch absolutny czê¶ciej zdarza siê po¶ród muzyków ni¿ reszty publiczno¶ci, potwierdzi³y szeroko zakrojone badania. W¶ród muzyków s³uch absolutny maj± najczê¶ciej ci, którzy wcze¶nie rozpoczêli naukê, chocia¿ ten zwi±zek nie zawsze siê potwierdza.
');
INSERT INTO texts (name, text) VALUES ('tekst55.txt', '
Wychowany w atmosferze klasycznej muzyki zachodniej, bez trudu wychwytujê jej stosunkowo proste rytmy i schematy metryczne, ale w stropienie wprawiaj± mnie bardziej skomplikowane rytmy mamba czy tanga, by ju¿ nie mówiæ o synkopach czy polirytmiczno¶ci jazzu i muzyki afrykañskiej. Kultura i warunki, w których kto¶ siê kszta³tuje, wp³ywaj± te¿ na wra¿liwo¶æ tonaln±. Kto¶ taki jak ja bêdzie sk³onny uwa¿aæ skalê diatoniczn± za bardziej "naturaln±" od dwudziestodwutonowych skal muzyki hinduskiej. Nie wydaje siê jednak, by istnia³y jakiekolwiek wrodzone preferencje neurologiczne dla jakiego¶ typu muzyki, podobnie jak nie ma takich preferencji w odniesieniu do konkretnych jêzyków.
');
INSERT INTO texts (name, text) VALUES ('tekst56.txt', '
Od chwili zderzenia z g³ównymi si³ami huraganu na ca³ym pok³adzie nie by³o gdzie siê schroniæ, wiêc zgnêbieni i og³uszeni marynarze ukryli siê we wnêtrzu, w lewoburtowym korytarzu pod pomostem. Drzwi prowadz±ce na rufê zamknêli za sob±. W korytarzu by³o zimno, ponuro i ciemno, choæ oko wykol. Za ka¿dym gwa³townym rzutem statku w ciemno¶ciach odzywa³ siê chóralny jêk; tony wody przelewa³y siê nad nimi próbuj±c, rzek³by¶, dostaæ siê do wnêtrza z góry. Bosman strofowa³ marynarzy, ale bezskutecznie. Skar¿y³ siê potem, ¿e zachowywali siê, jakby postradali zmys³y. Byli w bezpiecznym i do¶æ dogodnym schronieniu i nie kazano im nic robiæ. Nie przestawali jednak narzekaæ i z³o¶ciæ siê jak chore dzieci.
');
INSERT INTO texts (name, text) VALUES ('tekst57.txt', '
Pisanie na klawiaturze bezwzrokowo i dziesiêcioma palcami jest bardzo szybkie i wygodne. Rozpowszechniona metoda "hunt and peck" (pisania z patrzeniem na klawiaturê, zwykle dwoma palcami) pozwala osi±gaæ prêdko¶ci podobne jak przy pisaniu d³ugopisem na papierze - oko³o 150 znaków na minutê. Kilka tygodni treningu pisania bezwzrokowego pozwala bez trudu znacznie przekroczyæ t± prêdko¶æ, a w dalszej perspektywie pisaæ dwa, lub nawet trzy razy szybciej. S± osoby osi±gaj±ce prêdko¶ci rzêdu 500 znaków na minutê i wiêcej (rekord ¶wiata wynosi ponad 1000). Prawid³owa technika bezwzrokowa umo¿liwia te¿ bardziej równomierny rozk³ad pracy na poszczególne palce, co zwiêksza ergonomiê pisania.
');
INSERT INTO texts (name, text) VALUES ('tekst58.txt', '
Niedawno naukowcy podali, ¿e dziecko urodzone w 2030 roku bêdzie ¿y³o o piêæ lat d³u¿ej, ni¿ dziecko urodzone wczoraj. Z tego powodu w po³owie obecnego stulecia wiêcej bêdzie ludzi pobieraj±cych emerytury, ni¿ pracuj±cych. Wp³ynie to katastrofalnie na ekonomiê, poniewa¿ proste obliczenia pokazuj±, ¿e w bud¿ecie zabraknie pieniêdzy, by wszystkim tym staruszkom wystarczy³o na protezy bioder i karmê dla kotów. W takim razie, co u licha zrobimy? Sk³onimy ludzi by oszczêdzali wiêcej i na staro¶æ byli samowystarczalni? Zmusimy wszystkich, by mieli wiêcej dzieci? Czy te¿ wezwiemy na pomoc tysi±ce imigrantów, którzy bêd± chcieli uwijaæ siê przy jakiej¶ konkretnej robocie? Trudna decyzja.
');
INSERT INTO texts (name, text) VALUES ('tekst59.txt', '
W zesz³y czwartek dwa rekiny ludojady po¿ar³y osiemnastoletniego australijskiego surfera. Wed³ug ¶wiadków zdarzenia, rozerwa³y jego cia³o na pó³, a nastêpnie spêdzi³y parê minut walcz±c o to, któremu z nich przypadnie który kawa³ek. Jak zwykle w takim przypadku, przeprowadzono wywiady z ró¿nymi ekspertami od przyrody, którzy zgodnie stwierdzili, ¿e rekiny te nale¿y wypu¶ciæ na wolno¶æ po udzieleniu im pouczenia, czê¶ciowo dlatego, ¿e s± pod ochron±, a czê¶ciowo dlatego, ¿e do takich ataków dochodzi niezwykle rzadko. A jednak to nieprawda. W rzeczywisto¶ci nie min±³ nawet tydzieñ, a kolejny surfer zosta³ po¿arty dok³adnie przy tym samym odcinku brzegu. Co w takim razie jest grane?
');
INSERT INTO texts (name, text) VALUES ('tekst60.txt', '
Z niewyja¶nionych po dzi¶ dzieñ przyczyn, zostali¶my przewiezieni do szpitala, gdzie zacz±³em opracowywaæ przebieg³y plan ucieczki. Poniewa¿ nie mia³em pod rêk± ³y¿ek, wykluczy³em opcjê dr±¿enia tunelu. Chwilê pó¼niej dozna³em ol¶nienia. Doszed³em do wniosku, ¿e skoro jestem w szpitalu, to okno w ubikacji nie bêdzie mia³o krat. Mia³em racjê. Podczas gdy policjant czeka³ na zewn±trz kabiny, ja w ¶rodku wydawa³em niezliczone ilo¶ci przekonuj±cych - tak mi siê przynajmniej wydawa³o - odg³osów wymiotowania, które u³atwi³y mi otwarcie okna. Nie by³o ono du¿e, ale uda³o mi siê wydostaæ prawie w ca³o¶ci. Wtedy poczu³em na moich kostkach krzepkie d³onie policjanta.
');
INSERT INTO texts (name, text) VALUES ('tekst61.txt', '
Przypuszczam, ¿e wszyscy marzymy o dniu, w którym George Clooney zadzwoni do nas, by powiedzieæ, ¿e w³a¶nie jest w okolicy i chcia³by wpa¶æ do nas na obiad. Fantazjujemy o tym, jak na przystawkê podamy solê, i o b³yskotliwej konwersacji, któr± zaserwujemy do kawy i miêtowych czekoladek. I dobrze wiemy, ¿e nigdy siê to nie wydarzy. Otó¿ w zesz³ym tygodniu przytrafi³o mi siê co¶ w tym stylu. By³em w moim domku wypoczynkowym nad morzem, kiedy kto¶, kogo zaprosi³em na obiad, zadzwoni³, by zapytaæ, czy móg³by przyjechaæ ze znajom±, która okaza³a siê byæ moj± najbardziej ulubion± aktork± na ¶wiecie. Nie lubiê sformu³owania "zatka³o mnie", ale w³a¶nie tak siê sta³o.
');
INSERT INTO texts (name, text) VALUES ('tekst62.txt', '
Odtwarzanie bia³ego szumu w celi wiê¼nia jest sklasyfikowane jako tortura. Ta praktyka jest zakazana przez wszystkie cywilizowane kraje, bo umys³ cz³owieka nie mo¿e sobie poradziæ z trwaj±c± w nieskoñczono¶æ sekwencj± przypadkowych d¼wiêków. W koñcu prowadzi ona do ob³êdu.
Ale dok³adnie z tym mamy do czynienia podczas bie¿±cej kampanii wyborczej. Niekoñcz±cy siê bia³y szum obietnic, które nie mog± byæ dotrzymane, statystyk, które nic nie znacz±, i urywków spektakli z osobistymi zniewagami. Dlaczego? No có¿, mówi±c wprost, zrobienie reporta¿u z kampanii wyborczej kosztuje bardzo niewiele, w przeciwieñstwie, dajmy na to, do reporta¿u z wojny.
');
INSERT INTO texts (name, text) VALUES ('tekst63.txt', '
Ca³kowicie rozumiem, ¿e w dzisiejszych, pe³nych po¶piechu czasach, gdy pracujemy do pó¼na i wiele godzin spêdzamy stoj±c w korkach, nie zawsze mo¿na zd±¿yæ punktualnie na umówione spotkanie. Dlatego w³a¶nie, je¶li mam siê zobaczyæ z kim¶ w restauracji, zawsze dajê mu 60 sekund ³aski, zanim wstanê od sto³u i udam siê do domu.
Istnieje wiele sposobów na obra¿enie cz³owieka. Mo¿na drwi±co prychn±æ ogl±daj±c zdjêcie jego dzieci albo przer±baæ go siekier± na pó³. Zawsze jednak by³em zdania, ¿e najwiêksz± mo¿liw± obraz± jest spó¼niæ siê na spotkanie. Najbardziej boli uk³ucie tego subtelnego przekazu, tej dyskretnej sugestii, ¿e wasz czas jest wart wiêcej, ni¿ czas tej drugiej osoby.
');
INSERT INTO texts (name, text) VALUES ('tekst64.txt', '
Stara³ siê w ogóle nie my¶leæ i wszystko sz³o jak najlepiej. Udawa³, ¿e nie interesuje go ju¿ praca, jak± wykonywa³ dawniej, skoro przecie¿ i tak ju¿ jej wykonywaæ nie móg³. Ale wmawia³ sobie, ¿e kiedy¶ opisze jeszcze tych wszystkich ludzi, tych bogatych, ¿e w gruncie rzeczy nie jest jednym z nich, lecz szpiegiem w ich krainie, ¿e pewnego dnia opu¶ci j± i zacznie pisaæ o niej i ¿e bêdzie to dla odmiany opowie¶æ cz³owieka, który wie, o czym pisze. Ale przecie¿ wiadomo by³o, ¿e nie napisze ju¿ nic, ka¿dy dzieñ bowiem spêdzony na niepisaniu, w komforcie, w towarzystwie ludzi, którymi pogardza³, os³abia³ jego wra¿liwo¶æ, jego wolê do pracy, w koñcu wiêc zupe³nie przesta³ pracowaæ.
');
INSERT INTO texts (name, text) VALUES ('tekst65.txt', '
Rzeka p³ynê³a cicho; by³a wartka i g³adka. Zanim wspi±³ siê na niewielkie wzniesienie, aby tam rozbiæ obóz, popatrza³ ze skraju ³±ki na rzekê i wynurzaj±ce siê pstr±gi. Wyp³ywa³y w pogoni za owadami, które po zachodzie s³oñca nadlecia³y tu z moczarów na drugim brzegu. Pstr±gi wyskakiwa³y z wody, aby je chwytaæ. Nick, id±c w±skim pasmem ³±ki nad rzek±, widzia³, jak skaka³y wysoko. Owady musia³y teraz siadaæ na powierzchni, bo spojrzawszy w dó³ rzeki widzia³, ¿e pstr±gi ¿eruj± na ca³ej jej d³ugo¶ci. Jak okiem siêgn±æ, wyp³ywa³y, pozostawiaj±c na wodzie kó³ka niby padaj±cy deszcz.
');
INSERT INTO texts (name, text) VALUES ('tekst66.txt', '
Kiedy siê zbudzi³, s³oñce ju¿ wzesz³o i namiot zaczyna³ siê nagrzewaæ. Nick wype³zn±³ na zewn±trz pod zas³aniaj±c± wyj¶cie moskitier±, a¿eby przyjrzeæ siê porankowi. Kiedy siê czo³ga³ nios±c spodnie i buty, czu³ pod d³oñmi wilgotn± trawê. S³oñce w³a¶nie wysz³o zza wzgórza. Przed sob± mia³ ³±kê, rzekê i bagna. Na zielonych moczarach po drugiej stronie rzeki ros³y brzozy.
By³ wczesny poranek, rzeka p³ynê³a wartko czysta i g³adka. Oko³o dwustu jardów dalej le¿a³y w poprzek niej trzy pnie drzewne. Powy¿ej woda by³a l¶ni±ca i g³êboka. Kiedy Nick patrza³, wydra przebieg³a po k³odach przez rzekê i zniknê³a na moczarach.
');
INSERT INTO texts (name, text) VALUES ('tekst67.txt', '
Niekiedy znajdowa³em owady na podmok³ych ³±kach w trawie albo pod paprociami i u¿ywa³em ich do ³owienia. By³y to chrz±szcze i owady maj±ce nogi podobne do ³ody¿ek trawy, czerwie kryj±ce siê w starych, przegni³ych pniach, bia³e poczwarki o brunatnych, chwytliwych ³ebkach, które nie trzyma³y siê na haczyku i znika³y w zimnej wodzie, kleszcze siedz±ce pod k³odami, gdzie mo¿na by³o znale¼æ glisty, które wwierca³y siê w ziemiê, gdy tylko podnios³em k³odê. Raz u¿y³em salamandry wydobytej spod starego pnia. By³a bardzo ma³a, zgrabna, ¿wawa, ³adnie ubarwiona. Mia³a drobne nó¿ki i próbowa³a pochwyciæ nimi haczyk, i potem ju¿ wiêcej nie bra³em salamandry, choæ znajdowa³em je bardzo czêsto.
');
INSERT INTO texts (name, text) VALUES ('tekst68.txt', '
Czasem potok bieg³ przez otwart± ³±kê i wtedy w suchej trawie ³apa³em koniki polne, których u¿ywa³em jako przynêt albo chwyta³em je i wrzuca³em do potoku patrz±c, jak unosz± siê na wodzie i zataczaj±c ko³a na powierzchni p³ywaj± porwane pr±dem i nikn±, gdy wynurzy siê pstr±g. Niekiedy w ci±gu nocy ³owi³em w czterech lub piêciu ró¿nych potokach, zaczynaj±c mo¿liwie jak najbli¿ej ¼ród³a i id±c z ich biegiem. Je¿eli skoñczy³em za szybko i jeszcze zostawa³o mi trochê czasu, ³owi³em znowu wzd³u¿ ca³ego strumienia; zaczyna³em od jego uj¶cia do jeziora i szed³em w górê, usi³uj±c pochwyciæ te pstr±gi, które wymknê³y mi siê za pierwszym razem.
');
INSERT INTO texts (name, text) VALUES ('tekst69.txt', '
Przez otwarte okno wpada³o s³oñce i prze¶wietla³o stoj±ce na stole butelki. Butelki by³y do po³owy opró¿nione. Zebra³o siê w nich na piwie trochê piany, ale nie du¿o, bo piwo by³o bardzo zimne. Pieni³o siê, kiedy je la³e¶ do wysokich kufli. Wyjrza³em przez otwarte okno na bia³± drogê. Rosn±ce przy niej drzewa by³y okryte py³em. Za drog± by³o zielone pole i potok. Nad potokiem ros³y drzewa i sta³ tartak z ko³em wodnym. Przez otwarty bok tartaku dojrza³em d³ugi drewniany kloc z wer¿niêt± weñ pi³±, która podnosi³a siê i opada³a. Zdawa³o siê, ¿e nikt jej nie obs³uguje. Po zielonym polu ³azi³y cztery wrony. Jedna siedzia³a na drzewie i patrza³a.
');
INSERT INTO texts (name, text) VALUES ('tekst70.txt', '
Na dworze ¶nieg siêga³ wy¿ej okna. S³oñce wpada³o przez okno i o¶wietla³o mapê wisz±c± na sosnowych deskach ¶ciany chaty. S³oñce by³o wysoko i ¶wiat³o wpada³o do ¶rodka ponad wierzchem ¶niegu. Od strony wej¶cia przekopano wzd³u¿ chaty rów i ka¿dego pogodnego dnia ciep³o s³oñca promieniowa³o od ¶ciany na ¶nieg i poszerza³o rów. By³ koniec marca. Major siedzia³ przy stole pod ¶cian±. Przy drugim stole siedzia³ jego adiutant.
Major mia³ woko³o oczu dwa bia³e krêgi od ciemnych okularów, które chroni³y jego twarz przed odblaskiem s³oñca od ¶niegu. Reszta twarzy najpierw siê przypiek³a, potem opali³a, a potem znowu przypiek³a przez opaleniznê.
');
INSERT INTO texts (name, text) VALUES ('tekst71.txt', '
Zje¿d¿ali¶my z prze³êczy przez zalesion± okolicê. Przy drodze sta³y stosy worków z wêglem drzewnym, a miêdzy drzewami widzieli¶my chaty wêglarzy. By³a niedziela i droga wznosi³a siê i opada³a, ale wci±¿ schodzi³a w dó³ z wynios³o¶ci prze³êczy, prowadz±c przez kar³owaty las i przez wioski. Woko³o wiosek rozci±ga³y siê pola winoro¶li. Pola by³y brunatne, winoro¶le gêste i krzaczaste. Domy by³y bia³e, a na ulicach grali w krêgle mê¿czy¼ni w niedzielnych ubraniach. Pod ¶cianami niektórych domów ros³y grusze z ga³êziami rozpiêtymi jak kandelabry na bia³ych murach. Grusze spryskiwano i ¶ciany domów nosi³y metaliczne, niebieskozielone ¶lady py³u rozpryskiwanej cieczy.
');
INSERT INTO texts (name, text) VALUES ('tekst72.txt', '
Chodzili¶my do szpitala ka¿dego popo³udnia i mo¿na by³o tam doj¶æ ró¿nymi drogami przez miasto o zmierzchu. Dwie prowadzi³y wzd³u¿ kana³ów, ale te by³y d³u¿sze. Jednak ¿eby siê dostaæ do szpitala, trzeba by³o zawsze przej¶æ przez który¶ mostek na kanale. Mia³o siê trzy mostki do wyboru. Na jednym kobieta sprzedawa³a przypiekane kasztany. Ciep³o by³o staæ przed jej wêglowym piecykiem, a kasztany by³y potem ciep³e w kieszeni. Szpital by³ bardzo stary i bardzo piêkny i wchodzi³o siê tam przez bramê, potem przez dziedziniec i wychodzi³o bram± po drugiej stronie. Za starym szpitalem sta³y nowe ceglane pawilony i tam spotykali¶my siê ka¿dego popo³udnia.
');
INSERT INTO texts (name, text) VALUES ('tekst73.txt', '
Samotny na ¶rodku areny byk ci±gle sta³ nieruchomo. Fuentes, wysoki, o p³askich plecach, szed³ ku niemu zuchwale, z rozpostartymi rêkami, trzymaj±c w palcach jednej i drugiej d³oni cienkie czerwone dr±¿ki, kolcami skierowane w przód. Szed³ prosto. Za nim, nieco z boku, zbli¿a³ siê peon z kap±. Byk spojrza³ na niego i poruszy³ siê wreszcie.
Oczy jego ¶ledzi³y Fuentesa, który teraz przystan±³ w miejscu. Odchyli³ siê w ty³ i zawo³a³ co¶ do byka. Machn±³ banderillami, a b³ysk stalowych kolców zwróci³ uwagê zwierza.
Byk zadar³ ogon i zaszar¿owa³.
');
INSERT INTO texts (name, text) VALUES ('tekst74.txt', '
Wagonik kolejki zachybota³ siê po raz ostatni i stan±³. Nie móg³ jechaæ dalej: ¶nieg grub± warstw± przysypa³ tor. Wichura smagaj±ca obna¿one stoki góry zbi³a ¶nieg w tward± skorupê. W wagoniku baga¿owym Nick smarowa³ narty; potem wsun±³ buty w ¿elazne uchwyty i zacisn±³ klamry wi±zañ. Bokiem wyskoczy³ z wagoniku, obróci³ siê i pochylony, ci±gn±c za sob± kijki, pomkn±³ w dó³ zbocza. Na bieli poni¿ej zjawia³ siê, nikn±³ i znów zjawia³ siê George. Pêd powietrza, raptowny spadek, szalony zjazd falist± stromizn± góry zaciera³y wszystkie my¶li. Po ca³ym ciele rozchodzi³o siê tylko cudowne uczucie pêdu i ¿eglowania w powietrzu.
');
INSERT INTO texts (name, text) VALUES ('tekst75.txt', '
Pada³o. Deszcz ocieka³ z drzew palmowych. Woda sta³a ka³u¿ami na wy¿wirowanych ¶cie¿kach. W hotelu mieszka³o tylko dwoje Amerykanów. Nie znali nikogo z ludzi, których mijali na schodach wychodz±c czy wracaj±c do swego pokoju. Pokój ten by³ na pierwszym piêtrze, od strony morza. Wychodzi³ te¿ na park i pomnik wojenny. W ogrodzie by³y wysokie palmy i zielone ³awki. W pogodny dzieñ zawsze by³ tam jaki¶ artysta ze sztalugami. Artystom podoba³y siê palmy, które tam ros³y, i ¿ywe barwy hoteli stoj±cych naprzeciw ogrodu i morza. W³osi przychodzili z daleka, ¿eby popatrzeæ na pomnik. By³ on odlany z br±zu i l¶ni³ na deszczu.
');
INSERT INTO texts (name, text) VALUES ('tekst76.txt', '
Pierwszy matador dosta³ rogiem w tê rêkê, w której trzyma³ szpadê, i t³um go wygwizda³. Drugi matador po¶lizn±³ siê i byk trafi³ go w brzuch, i matador uchwyci³ siê rogu jedn± rêk±, a drug± przycisn±³ do rany, i byk r±bn±³ go o ¶cianê, i róg wylaz³, a on upad³ na piasek, a potem wsta³ jak pijany wariat i próbowa³ pobiæ ludzi, którzy go wynosili, i wo³a³ o szpadê, ale zemdla³. Wtedy wyszed³ ten m³odziak i musia³ zabiæ piêæ byków, bo nie mo¿e byæ wiêcej ni¿ trzech matadorów, i przy ostatnim byku by³ ju¿ taki zmêczony, ¿e nie móg³ wbiæ szpady. Ledwie móg³ podnie¶æ rêkê. Próbowa³ piêæ razy, a t³um siedzia³ cicho, bo byk by³ dobry i wygl±da³o na to, ¿e bêdzie albo on, albo byk, i w koñcu mu siê uda³o.
');
INSERT INTO texts (name, text) VALUES ('tekst77.txt', '
Dzieñ by³ strasznie gor±cy. Zagrodzili¶my most zupe³nie doskona³± barykad±. By³a po prostu wspania³a. Du¿a stara krata z kutego ¿elaza, z frontu jakiego¶ domu. Za ciê¿ka, ¿eby j± podnie¶æ, a mo¿na by³o przez ni± strzelaæ, i tamci musieliby prze³aziæ przez wierzch. By³a ¶wietna. Próbowali przez ni± przele¼æ i ostrzelali¶my ich z odleg³o¶ci czterdziestu jardów. Rzucili siê na ni±, a potem przybiegli sami oficerowie i próbowali j± usun±æ. To by³a absolutnie doskona³a przeszkoda. Ich oficerowie byli wspaniali. Strasznie siê zmartwili¶my, kiedy przysz³a wiadomo¶æ, ¿e skrzyd³o siê za³amie i ¿e musimy siê wycofaæ.
');
INSERT INTO texts (name, text) VALUES ('tekst78.txt', '
Wozy utknê³y na przestrzeni trzydziestu mil na drodze do Karagaczu. Bawo³y i inne byd³o ci±gnê³y je przez b³oto. Ani pocz±tku, ani koñca. Tylko wozy wy³adowane wszystkim, co ci ludzie posiadali. Starzy mê¿czy¼ni i kobiety, przemoczeni na wylot, szli obok popêdzaj±c zwierzêta. Marica p³ynê³a wezbrana ¿ó³to prawie a¿ po sam most. Na mo¶cie utworzy³ siê zwarty zator wozów, miêdzy którymi drepta³y wielb³±dy. Kawaleria grecka par³a wzd³u¿ tego pochodu. Kobiety i dzieci siedzia³y na wozach zawalonych materacami, lustrami, maszynami do szycia, tobo³kami. Jedna z kobiet rodzi³a dziecko, a jaka¶ m³oda dziewczyna trzyma³a nad ni± koc i p³aka³a. Deszcz pada³ przez ca³± ewakuacjê.
');
INSERT INTO texts (name, text) VALUES ('tekst79.txt', '
Mój ojciec przechowywa³ w dolnej szufladzie swego g³êbokiego biurka star± i piêkn± mapê naszego miasta. By³ to ca³y wolumen in folio pergaminowych kart, które pierwotnie spojone skrawkami p³ótna, tworzy³y ogromn± mapê ¶cienn± w kszta³cie panoramy z ptasiej perspektywy. Zawieszona na ¶cianie, zajmowa³a niemal przestrzeñ ca³ego pokoju i otwiera³a daleki widok na ca³± dolinê Ty¶mienicy, wij±cej siê falisto bladoz³ot± wstêg±, na ca³e pojezierze szeroko rozlanych moczarów i stawów, na pofa³dowane przedgórza, ci±gn±ce siê ku po³udniowi, naprzód z rzadka, potem coraz t³umniejszymi pasmami, szachownic± okr±g³awych wzgórzy, coraz mniejszych i coraz bledszych, w miarê jak odchodzi³y ku z³otawej i dymnej mgle horyzontu.
');
INSERT INTO texts (name, text) VALUES ('tekst80.txt', '
Spacerowa³em po alei eukaliptusowej gdy wtem zza drzewa wylaz³a krowa. Przystan±³em i spojrzeli¶my sobie oko w oko. Jej krowio¶æ zaskoczy³a do tego stopnia m± ludzko¶æ - ten moment, w którym spojrzenia nasze siê spotka³y, by³ tak napiêty - ¿e stropi³em siê jako cz³owiek, to jest w moim, ludzkim, gatunku. Uczucie dziwne i bodaj po raz pierwszy przeze mnie doznane - ten wstyd cz³owieczy wobec zwierzêcia. Pozwoli³em ¿eby ona spojrza³a na mnie i zobaczy³a mnie - to nas zrówna³o - wskutek tego sta³em siê tak¿e zwierzêciem - ale dziwnym, powiedzia³bym nawet, niedozwolonym. Poszed³em dalej podejmuj±c przerwany spacer, ale poczu³em siê nieswojo... w naturze, która osacza³a mnie zewsz±d i jakby... ogl±da³a mnie.
');
INSERT INTO texts (name, text) VALUES ('tekst81.txt', '
Dzie³o, choæby zrodzone z najczystszej kontemplacji, powinno byæ tak napisane aby zapewniæ autorowi przewagê w jego rozgrywce z lud¼mi. Styl, który nie umie broniæ siê przed s±dem ludzkim, który wydaje swego twórcê na pastwê byle kretyna, nie spe³nia swojego najwa¿niejszego zadania. Lecz obrona przed tymi opiniami jest mo¿liwa tylko wtedy, gdy zdobêdziemy siê na pokorê i wyznamy, jak dalece s± one dla nas wa¿ne - nawet gdy pochodz± od g³upca. Dlatego bezbronno¶æ sztuki wobec s±dów ludzkich jest smutnym nastêpstwem jej dumy: ach, ja jestem wy¿szy ponad to, ja liczê siê tylko ze zdaniem rozumnych!
');
INSERT INTO texts (name, text) VALUES ('tekst82.txt', '
Nie dajcie siê zastraszyæ. S³owo "ja" jest tak zasadnicze i pierworodne, tak wype³nione najbardziej namacaln± a przeto najuczciwsz± rzeczywisto¶ci±, tak nieomylne jako przewodnik i surowe jako probierz, i¿ zamiast nim gardziæ nale¿a³oby pa¶æ przed nim na kolana. My¶lê, ¿e raczej nie jestem jeszcze do¶æ fanatyczny w moim przejêciu siê sob± i ¿e nie umia³em - w strachu przed innymi lud¼mi - oddaæ siê temu powo³aniu-zadaniu z do¶æ kategoryczn± bezwzglêdno¶ci±, pchn±æ tê sprawê do¶æ daleko. Ja jestem najwa¿niejszym i bodaj jedynym moim problemem: jedynym ze wszystkich moich bohaterów, na którym mi naprawdê zale¿y.
');
INSERT INTO texts (name, text) VALUES ('tekst83.txt', '
- A ducha dziejów znamy? A ducha cywilizacji helleñskiej? A ducha galijskiej, ducha umiaru i dobrego smaku? A ducha nikomu prócz mnie nie znanego sielankopisarza z XVI wieku, który pierwszy u¿y³ wyra¿enia "pêpek"? A ducha jêzyka? Jak siê mówi: "wykonywa", czy te¿ "wykonuje"?
Pytanie zaskoczy³o mnie. Sto tysiêcy duchów przydusi³o nagle mego ducha, b±kn±³em, ¿e nie wiem, on za¶ spyta³, co mi jest wiadomo o duchu Kasprowicza i jaki by³ stosunek poety do ch³opów, po czym zapyta³ jeszcze o pierwsz± mi³o¶æ Lelewela. Chrz±kn±³em i rzuci³em ukradkowo wzrokiem na paznokcie - paznokcie by³y czyste, ¶ci±gaczki nie by³o.
');
INSERT INTO texts (name, text) VALUES ('tekst84.txt', '
Szyld ober¿y przedstawia³ przedmiot bardzo zwyczajny w dziedzinie sztuk piêknych, ale niezmiernie rzadko spotykany w naturze, a mianowicie niebieskiego lwa z trzema ³apami w powietrzu, ko³ysz±cego siê na ¶rodkowym pazurze czwartej ³apy. W pobli¿u widaæ by³o biuro towarzystwa ubezpieczeñ od po¿arów i lombard, magazyny handlarza zbo¿em i handlarza p³ótnem, sklep siodlarza, handlarza wódek, korzennika i sklep z obuwiem. Ten ostatni jednocze¶nie zaopatrywa³ mieszkañców w kapelusze, czapki, wszelk± odzie¿, bawe³niane parasole i rozmaite po¿yteczne wiadomo¶ci. Sta³ tu prócz tego ma³y dom z czerwonej ceg³y, z niewielkim brukowanym podwórzem, o którym ka¿dy wiedzia³, ¿e nale¿y do adwokata.
');
INSERT INTO texts (name, text) VALUES ('tekst85.txt', '
W Pythonie warto¶ci, a nie zmienne, posiadaj± typ - tak wiêc Python jest jêzykiem z typami dynamicznymi, podobnie jak Lisp, a w przeciwieñstwie do Javy. Wszystkie warto¶ci przekazywane s± przez referencjê. W porównaniu z innymi jêzykami z typami dynamicznymi Python sprawdza typy w umiarkowanym stopniu. Nie jest ani tak liberalny, jak Perl, ani tak restrykcyjny jak Caml. Dla typów numerycznych zdefiniowana jest automatyczna konwersja, tak wiêc mo¿liwe jest np. mno¿enie liczby zespolonej przez liczbê ca³kowit± typu long bez rzutowania. Jednak w przeciwieñstwie do Perla nie ma np. automatycznej konwersji pomiêdzy napisami i liczbami; liczba nie jest prawid³owym argumentem dla operacji napisowej.
');
INSERT INTO texts (name, text) VALUES ('tekst86.txt', '
Luke Skywalker szed³ przez szary, stalowy korytarz "Gwiazdy ¦mierci". Mia³ na sobie matowo czarny kombinezon porucznika floty imperialnej. Prawie ca³e jego wyposa¿enie: przebranie, fa³szywy identyfikator oraz kilka niepozornych urz±dzeñ zawieszonych na pasie, zosta³o dostarczone przez rebeliancki wywiad. Jedyn± jego broni± by³ miecz ¶wietlny schowany w kaburze. Do tej pory wszystko sz³o doskonale, mundur i dokumenty umo¿liwi³y mu w miarê bezproblemowe dostanie siê na stacjê w roli zastêpcy dowódcy szwadronu nowych my¶liwców Tie Defender. Od teraz jednak musia³ zachowywaæ ostro¿no¶æ - w sektorze, w którym siê znajdowa³, obecno¶æ pilota by³a wysoce podejrzana.
');
INSERT INTO texts (name, text) VALUES ('tekst87.txt', '
Obserwuj±c te krople dochodzê do wniosku, ¿e ich ¿ycie jest tak samo pe³ne niespodzianek jak ¿ycie ka¿dego cz³owieka. Zdawa³oby siê, ¿e one same wybieraj± kierunek, w którym chc± p³yn±æ. To jednak s± tylko pozory, zupe³nie jak w ludzkim ¿yciu. Mo¿liwe, ¿e czê¶æ z nich chcia³aby p³yn±æ w³a¶nie ¶rodkiem szyby. Mo¿liwe, ¿e chcia³yby p³yn±æ wspólnie w³a¶nie z t± kropl±, z któr± siê po³±czy³y. Wystarczy jednak jedna, ma³a nierówno¶æ na szybie, mo¿e jaki¶ przyczepiony, milimetrowych rozmiarów paproszek i ich drogi siê rozchodz±. Nagle jedna z nich sp³ywa ca³kiem po krawêdzi. P³ynie szybko, bez przerwy a druga p³ynie powoli i nierówno, jakby nie potrafi³a siê odnale¼æ w tej nowej sytuacji.
');

INSERT INTO texts (name, text) VALUES ('tekst88.txt', '
Trudny i niebezpieczny jest zawód przemytnika. Lecz czu³em, ¿e porzuciæ go by³oby mi trudno. Przyci±ga mnie jak kokaina. Wabi± mnie nasze tajemnicze, nocne podró¿e. Poci±ga gra nerwów, igranie ze ¶mierci± i niebezpieczeñstwem. Lubiê powroty z dalekich, trudnych wycieczek. A potem wódka, ¶piew, harmonia, weso³e twarze ch³opaków i dziewczyny, kochaj±ce nas nie za nasze pieni±dze, a za ¶mia³o¶æ, weso³o¶æ, rozhulanie i pogardê dla forsy. Nic nie czytamy. Polityka nas nie interesuje. Gazety nie widzia³em od kilku miesiêcy. Wszystkie nasze my¶li obracaj± siê woko³o jednego tematu. Granica. A uczucia doko³a kilku innych, zale¿nie od temperamentu: wódka, muzyka, gra w karty, kobiety.
');
INSERT INTO texts (name, text) VALUES ('tekst89.txt', '
Nie mog³em zrozumieæ, co siê ze mn± sta³o. Czu³em tylko, ¿e duszê siê, ¿e do ust s±czy siê lepka, gêsta ciecz. Szarpa³em siê rozpaczliwie w prawo, w lewo, w górê. Wreszcie ukl±k³em. Odetchn±³em. Poczu³em, ¿e do p³uc wchodzi mi powietrze. D³ugo trwa³em nieruchomo. Tu³ów mia³em zanurzony w b³ocie, a g³owê na wierzchu. Wydosta³em z b³ota rêce. Otar³em d³oñmi twarz i oczy z lepkiej, gêstej mazi. Zobaczy³em o kilkaset kroków od siebie d³ugi rz±d l¶ni±cych ¿ó³tawo ogni. By³ to poci±g, który zatrzymano wkrótce po moim skoku z wagonu. Spostrzeg³em, ¿e wzd³u¿ toru kolejowego poruszaj± siê inne ¶wiat³a, mniejsze lecz jaskrawsze. By³y to latarnie w rêkach szukaj±cych mnie w pobli¿u toru ludzi.
');
INSERT INTO texts (name, text) VALUES ('tekst90.txt', '
Wilno pocz±tkowo sprawia³o na mnie niezwyk³e wra¿enie. By³em po prostu oszo³omiony. Dra¿ni³ mnie ruch uliczny. Og³usza³ ha³as. Przesz³o dwa lata ¿ycia na wilczej stopie nie minê³o bez ¶ladu. Mnóstwo nieprzespanych nocy, sta³e przeszywanie mroków oczami, ci±g³e chodzenie pod kulami, ustawiczna czujno¶æ zrobi³y ze mnie innego cz³owieka. Zmieni³em siê nawet fizycznie. Od dawna nie widzia³em siebie w du¿ym lustrze. Gdy teraz, ubrany od stóp do g³owy we wszystko nowe, spojrza³em na siebie w du¿ym lustrze, by³em zdumiony. Zobaczy³em obcego mi cz³owieka. Szczególnie dziwna by³a twarz i oczy, zimne, b³êdne, a w nich zagadkowe g³êbie, których nie by³o dawniej.
');
INSERT INTO texts (name, text) VALUES ('tekst91.txt', '
Znale¼li¶my siê na olbrzymim, jak okiem siêgn±æ zastawionym wozami placu. ¦rodek rynku zajmowa³ du¿y prostok±t sklepów. Po brzegach placu by³y równie¿ ¿ydowskie sklepy, herbaciarnie, zajazdy i restauracje. W pobli¿u sklepów ustawione by³y stragany wêdrownych kramarzy i szewców. Z trudno¶ci± torowali¶my sobie drogê w gêstym t³umie. Nad placem mo¿na by zawiesiæ olbrzymi± chor±giew Bachusa. Pili wszyscy. Pili wszêdzie. Pili stoj±c, le¿±c, siedz±c. Pili na wozach, miêdzy wozami i pod wozami. Pili mê¿czy¼ni i kobiety. Matki poi³y ma³e dzieci, ¿eby i one siê zabawi³y na kiermaszu, poi³y i niemowlêta, aby nie p³aka³y. Widzia³em nawet jak pijany ch³op zadar³ koniowi pysk i wlewa³ mu do gard³a wódkê z butelki. Chcia³ wracaæ do domu i zamierza³ popisaæ siê przed ¶wiatem szybk± jazd±.
');
INSERT INTO texts (name, text) VALUES ('tekst92.txt', '
Gdzie¶ pad³ strza³ karabinowy. Potem przebrzmia³o kilkana¶cie wystrza³ów, budz±c echa w pobliskich w±wozach i lasach. Pewnie dzicy przeszli granicê. Obejrza³em siê woko³o. Cisza. Pustka. Ksiê¿yc leje na pograniczu blade, zimne promienie. Gwiazdy l¶ni± mg³awo. Gór± przekradaj± siê chmury. Ukradkiem przemykam siê przez nieznane ludziom ostêpy. A na pó³nocnym zachodzie cudnie l¶ni, klejnotami ¶licznych gwiazd, wspania³a wielka Nied¼wiedzica. Otuli³y j± pieszczotliwie lekkie, puszyste, ¶nie¿nobia³e ob³oki. By³ to koniec mojego trzeciego sezonu. By³a to rocznica ¶mierci Saszki Weblina, niekoronowanego króla granicy. By³a to moja ostatnia noc na pograniczu.
');
INSERT INTO texts (name, text) VALUES ('tekst93.txt', '
Dos³ownie w ostatniej chwili, gdy car wsiad³ ju¿ do wagonu, stary admira³ zdo³a³ przepchn±æ siê przez t³um konwojentów i gapiów, i ze ³zami w oczach przypad³ do rêki swego monarchy. Znalaz³ siê jednak monarchista, jeden jedyny, ale siê objawi³. W komentarzach pisano potem zgry¼liwie o jego lokajskiej mentalno¶ci. Wstyd by³o patrzeæ na takie dogryzanie cz³owiekowi, który zawini³ w³a¶ciwie tylko przyzwoito¶ci±. Zrobi³o mi siê nieswojo. Zd±¿y³em ju¿ nabraæ pogardy dla monarchistów, dla ich nikczemno¶ci i g³upoty, kompletnej ich nêdzy w dniach rewolucji. Z poczuciem wy¿szo¶ci mog³em mówiæ o tych b±d¼ co b±d¼ doros³ych ludziach, ¿e s± draniami, durniami i tchórzami. I oto jeden z nich robi rzecz imponuj±c±, na któr± nie ka¿dy by siê zdoby³. Zastanawia³em siê czy ja bym tak móg³.
');
INSERT INTO texts (name, text) VALUES ('tekst94.txt', '
Dopiero gdy nad moj± g³ow±, od wylotu Sadowej, ockn±³ siê i za³omota³ karabin maszynowy, oficer rzuci³ po czesku komendê i oni, zerwawszy z ramion broñ, przemknêli w furiackim ataku na bagnety, zda³em sobie sprawê z tej wyzywaj±cej i straszliwej brawury. Jej ryzyko i grozê wyja¶ni³ mi stary dwornik nieco pó¼niej, gdy sta³em w t³umie gapiów nad pobojowiskiem, przy karabinie maszynowym na rogu Sadowej. Ten dozorca t³umaczy³ mi, ¿e najstraszniejszy to w³a¶nie taki atak w milczeniu i przepisowym ordynku, z hamowan± pasj±. Mo¿na przy tym du¿o ludzi potraciæ, ale jak ju¿ dopadn± wroga, to choæby zosta³a ich garstka, roznios± wszystko na bagnetach i nikomu nie daruj±.
');
INSERT INTO texts (name, text) VALUES ('tekst95.txt', '
Wszyscy trzej posuwali siê zgodnie, koncentrycznie, a za nimi misje wojskowe. Angielska, francuska, japoñska, amerykañska, nie zabrak³o i Turków, którzy przyszli na Kaukaz ani Polaków, którzy wyl±dowali w Murmañsku. Posêpne ptactwo siada³o w podskokach, wykrakuj±c bliski krach. Pier¶cieñ bia³ych zaciska³ siê i dusi³, a wewn±trz hula³a anarchia. Przez Moskwê po zmroku nie mo¿na by³o przej¶æ ani przejechaæ, nawet Lenina zatrzymano pewnego razu i zabrano mu auto. Czarne flagi powiewa³y wokó³ Kremla ur±gaj±c w³adzy komisarzy ludowych, uzbrojeni po zêby anarchi¶ci pozajmowali najokazalsze rezydencje i pa³ace. Robili co chcieli i brali co chcieli.
');
INSERT INTO texts (name, text) VALUES ('tekst96.txt', '
Z t± nasz± m³odzieñcz± skwapliwo¶ci± brania rzeczy dos³ownie wpada³o siê oczywi¶cie w skrajno¶ci absurdalne b±d¼ ¶mieszne. Pos³yszawszy co nieco o zadaniach sztuki proletariackiej, lizn±wszy nowych kryteriów oceny dzie³a literackiego, zabrali¶my siê w Symbirsku do przebadania lektury szkolnej. I co siê okaza³o? Borysie Walentinowiczu - o¶wiadczyli¶my na lekcji - komórka komsomolska uwa¿a, ¿e powinni¶my przerwaæ przerabianie "Eugeniusza Oniegina", w ogóle Puszkina nale¿y zredukowaæ do czê¶ci postêpowych. Prosimy nasz wniosek przedyskutowaæ. Profesor oniemia³, szk³a mu spotnia³y i zacz±³ je przecieraæ. Nie rozumia³, o co nam chodzi.
');
INSERT INTO texts (name, text) VALUES ('tekst97.txt', '
Wkrótce potem rozsta³em siê z go¶cinnym domem Wo³osatowa. Podoba³ mi siê, prosty i ¿yczliwy, nieco zamkniêty w sobie, bez absolutnie ¿adnej zarozumia³o¶ci, ¶wiadomy braków w swym wykszta³ceniu. Bohater naszych czasów, wiejski ch³opak w wojsku carskim. Doznania, trudy, przygody wojny ¶wiatowej, rewolucji, wojny domowej, przemiany woko³o i w nim samym, wszystko to wtenczas atakowa³o wyobra¼niê, by³o tematem ¶wie¿ym i ponêtnym. Du¿o pracowa³ nad sob± w domu, gdzie czu³o siê rêkê i obecno¶æ m³odej inteligentnej kobiety, dyskretn± obecno¶æ. Nie lubi³a pokazywaæ siê ani odgrywaæ jakiejkolwiek roli w jego ¶rodowisku.
');
INSERT INTO texts (name, text) VALUES ('tekst98.txt', '
Tom wydosta³ z zamkniêtego biurka butelkê whisky. Tylko dwa razy w ¿yciu zdarzy³o mi siê upiæ, drugi raz w³a¶nie tego popo³udnia. Dlatego te¿ wszystko, co siê dzia³o, okryte jest w mojej pamiêci niejasnym, mglistym oparem, chocia¿ mieszkanie a¿ do godziny ósmej wype³nia³ pogodny blask s³oñca. Pani Wilson, siedz±c na kolanach Toma, dzwoni³a do ró¿nych ludzi, potem zabrak³o papierosów i poszed³em do najbli¿szego sklepiku na rogu ulicy. Kiedy wróci³em, oboje gdzie¶ zniknêli, wiêc usiad³em dyskretnie w saloniku i przeczyta³em rozdzia³ ksi±¿ki. Albo to by³ stek bzdur, albo te¿ dzia³a³ wypity alkohol, bo jako¶ niczego nie mog³em zrozumieæ.
');
INSERT INTO texts (name, text) VALUES ('tekst99.txt', '
W letnie noce z domu mojego s±siada nios³a siê muzyka. W jego b³êkitnych ogrodach mê¿czy¼ni i kobiety zjawiali siê i znikali jak æmy, w¶ród szeptów i szampana, i gwiazd. W czasie przyp³ywu, po po³udniu, widzia³em jego go¶ci nurkuj±cych z wie¿y na przystani albo opalaj±cych siê na gor±cym piasku pla¿y, podczas gdy dwie jego motorówki ciê³y powierzchniê cie¶niny, ci±gn±c za sob± katarakty piany. W soboty i niedziele jego samochód stawa³ siê omnibusem, który od dziewi±tej rano a¿ do pó¼nych godzin nocy przywozi³ towarzystwo z miasta i odwozi³ je z powrotem, a ma³a furgonetka niczym ¿wawy cytrynowy ¿uk pomyka³a na stacjê do ka¿dego poci±gu.
');
INSERT INTO texts (name, text) VALUES ('tekst100.txt', '
W³o¿y³em garnitur z bia³ej flaneli i parê minut po siódmej by³em w jego ogrodzie, gdzie czu³em siê raczej nieswojo w gêstniej±cym wirze obcych ludzi, choæ tu i ówdzie mignê³a mi twarz, któr± pamiêta³em z podmiejskiego poci±gu. Uderzy³a mnie od razu ilo¶æ m³odych Anglików, rozsianych w tym t³umie. Wszyscy dobrze ubrani, wszyscy jakby trochê g³odni, cicho i powa¿nie rozmawiali z budz±cymi zaufanie, bogatymi Amerykanami. Na pewno chcieli im co¶ sprzedaæ. Akcje albo polisy ubezpieczeniowe, albo samochody. W ka¿dym razie widaæ by³o, ¿e wij± siê w mêkach czuj±c blisko¶æ du¿ych pieniêdzy, przekonani, ¿e mogliby je mieæ za kilka trafnie dobranych s³ów.
');
INSERT INTO texts (name, text) VALUES ('tekst101.txt', '
Najpierw spotkasz Syreny, które czaruj± wszystkich, którzy do nich przychodz±. Kto nie¶wiadom zbli¿y siê i pos³ucha g³osu Syren, temu ju¿ nie bêdzie dane wróciæ do domu, zobaczyæ ¿onê i dzieci, id±ce naprzeciw z rado¶ci±, bo go Syreny uwiod± sw± dzwonn± pie¶ni±. Siedz± na ³±ce, a na wybrze¿u pe³no jest ko¶ci tych, co s³uchali ich g³osu, pe³no butwiej±cych skór. Trzeba ci je min±æ. Ugnieæ wosk ¿ó³ty jak miód i pozalepiaj uszy towarzyszy, by nikt z nich nie s³ysza³. Sam mo¿esz s³uchaæ je¶li chcesz, lecz niechaj ci zwi±¿± rêce i nogi, i przytwierdz± linami do masztu, póki siê nie nacieszysz pie¶ni± Syren. A gdyby¶ b³aga³ towarzyszy, gdyby¶ im rozkazywa³ odwi±zaæ siê, niech ciê zwi±¿± jeszcze mocniej.
');
