INSERT INTO texts (name, text) VALUES ('tekst01.txt', '
Chêtnie by mia³ jedn± z nich. Ale nie by³o warto. By³y tak ³adnie szablonowe. Podoba³ mu siê ten szablon. By³ podniecaj±cy. Ale Krebs nie mia³ ochoty przechodziæ przez to ca³e gadanie. Nie mia³ do¶æ silnej ochoty na dziewczynê. Mimo to lubi³ na nie patrzeæ. Tylko ¿e nie by³o warto. Szczególnie teraz, kiedy wszystko zaczyna³o siê znowu dobrze uk³adaæ. Siedzia³ na ganku i czyta³ ksi±¿kê o wojnie. By³a to praca historyczna i czyta³ o wszystkich walkach, w których bra³ udzia³. Uwa¿a³, ¿e to najciekawsza lektura, jak± dot±d mia³. ¯a³owa³, ¿e nie ma tam wiêcej map. Z przyjemno¶ci± zapatrywa³ siê na przeczytanie wszystkich naprawdê dobrych prac historycznych, kiedy uka¿± siê z dobrymi, szczegó³owymi mapami. Teraz naprawdê dowiadywa³ siê czego¶ o wojnie. W swoim czasie by³ dobrym ¿o³nierzem. A to by³o wa¿ne.
');
INSERT INTO texts (name, text) VALUES ('tekst02.txt', '
Nie chcia³ te¿ ¿adnej konsekwencji. Nie chcia³ nigdy wiêcej jakichkolwiek konsekwencji. Chcia³ sobie ¿yæ bez nich. Poza tym w gruncie rzeczy nie potrzebowa³ dziewczyny. Tego nauczy³o go wojsko. Mo¿na by³o pozowaæ na to, ¿e musi siê mieæ dziewczynê. Prawie ka¿dy to robi³. Ale to nie by³a prawda. Nie potrzebowa³o siê dziewczyny. To w³a¶nie naj¶mieszniejsze. Najpierw kto¶ siê przechwala³, ¿e dziewczyny nic dla niego nie znacz±, ¿e nigdy o nich nie my¶li, ¿e wcale go nie obchodz±. Potem przechwala³ siê, ¿e nie mo¿e sobie daæ rady bez dziewczyn, ¿e musi je mieæ stale, ¿e nie mo¿e bez nich zasn±æ. To wszystko by³o k³amstwo. K³amstwem by³o i jedno i drugie. Nie potrzebowa³e¶ dziewczyny, je¶li o niej nie my¶la³e¶. Tego nauczy³ siê w wojsku.
');
INSERT INTO texts (name, text) VALUES ('tekst03.txt', '
Min±³ nas du¿y samochód jad±cy bardzo szybko i p³achta b³otnistej wody chlusnê³a na nasz± ch³odnicê i przedni± szybê. Automatyczne wycieraczki zaczê³y poruszaæ siê tam i z powrotem, rozprowadzaj±c jej warstwê na szybie. Zatrzymali¶my siê w Sestri na obiad. Restauracja nie by³a ogrzewana i siedzieli¶my w paltach i kapeluszach. Przez okno widzieli¶my nasz wóz. By³ pokryty b³otem i sta³ przy jakich¶ ³odziach, które wci±gniêto na brzeg poza zasiêg fal. W restauracji widzia³o siê parê w³asnego oddechu. Pasta asciutta by³a dobra; wino mia³o posmak a³unu i dolali¶my do niego wody. Pó¼niej kelner przyniós³ befsztyki z przysma¿anymi kartoflami.
');
INSERT INTO texts (name, text) VALUES ('tekst04.txt', '
Doktor powiedzia³ mi, ¿e ¿ona majora, która by³a bardzo m³oda i z któr± o¿eni³ siê dopiero wtedy, gdy jako inwalida zosta³ ostatecznie wyeliminowany z wojny, umar³a na zapalenie p³uc. Chorowa³a tylko kilka dni. Nikt siê nie spodziewa³, ¿e umrze. Major przez trzy dni nie przychodzi³ do szpitala. Potem zjawi³ siê o zwyk³ej godzinie, z czarn± opask± na rêkawie munduru. Kiedy wróci³, na ¶cianach wisia³y du¿e oprawione fotografie przedstawiaj±ce wszelkie rodzaje ran przed i po leczeniu za pomoc± aparatów. Przed tym aparatem, którego u¿ywa³ major, by³y trzy fotografie kompletnie wyleczonych r±k, takich jak jego rêka. Nie wiem, sk±d doktor je wzi±³. Zawsze s³ysza³em, ¿e my pierwsi u¿ywali¶my tych aparatów. Fotografie nie zrobi³y wiêkszego wra¿enia na majorze, bo tylko spogl±da³ przez okno.
');
INSERT INTO texts (name, text) VALUES ('tekst05b.txt', '
Jego twarz pokry³a maska ca³kowitej, ostatecznej rozpaczy wynikaj±cej z wiedzy, która przysz³a za pó¼no. Wielkie ko³o hamulcowe znajdowa³o siê na swoim miejscu, po drugiej stronie wagonu, lecz nie trzyma³a go niczyja rêka. Zamiast niego, rêka ¶ciska³a otwart± Bibliê, le¿±c± grzbietem do góry na pod³odze. Sam Devlin, tak¿e grzbietem do góry, le¿a³ obok swego prowizorycznego pos³ania. Miêdzy jego chudymi ³opatkami stercza³a rêkoje¶æ no¿a. Bellew odwróci³ napiêt± twarz i wpatrzy³ siê têpo w o¶nie¿one sosny na poboczu toru, mijaj±ce go ze ¶wistem z prêdko¶ci± stu mil na godzinê. Prze¿egna³ siê, choæ nie robi³ tego od dzieciñstwa, i strach znikn±³ z jego twarzy. Zast±pi³a go rezygnacja - sier¿ant pogodzi³ siê z nieuchronn± ¶mierci±.
');
INSERT INTO texts (name, text) VALUES ('tekst05.txt', '
Bellew dotar³ do drzwi z ty³u wagonu i rozpaczliwie szarpn±³ za klamkê. Bez skutku - te drzwi równie¿ by³y zamkniête na klucz. Wyci±gn±³ colta i strzeli³, mierz±c tu¿ powy¿ej i nieco z boku zamka. Strzeli³ cztery razy, nie przejmuj±c siê dwoma potencjalnie ¶mierciono¶nymi rykoszetami, które z gwizdem przelecia³y przez wagon - teraz grozi³o im ju¿ wiêksze niebezpieczeñstwo. Po czwartym strzale drzwi ust±pi³y pod rozpaczliwym naciskiem jego d³oni. Wyskoczy³ na tylny pomost. Natychmiast odrzuci³ go podmuch wiatru, który osi±gn±³ bez ma³a si³ê huraganu, oraz wyj±tkowo gwa³towny przechy³ wagonu. W ostatniej chwili obur±cz przytrzyma³ siê porêczy. Colt, którego ¶ciska³ w prawej rêce, wylecia³ na pobocze, kozio³kuj±c w powietrzu. Sier¿ant zdecydowa³ siê na samobójcze ryzyko, lecz miêdzy samobójstwem a nag³± ¶mierci± z innych powodów nie ma istotnej ró¿nicy.
');
INSERT INTO texts (name, text) VALUES ('tekst06.txt', '
Pu³kownik Claremont, którego wybuchowy temperament czêsto dawa³ o sobie znaæ, heroicznie stara³ siê utrzymaæ go na wodzy. By³a to jednak z góry przegrana walka. Pedantyczny i skrupulatny oficer, dla którego rozkaz i porz±dek dzienny by³y rzecz± ¶wiêt±, nie znosi³, kiedy co¶ mu zak³óca³o, a tym bardziej niweczy³o raz powziête plany. Dodaj±c za¶ do tego skrajn± nietolerancjê wobec g³upoty i nieudolno¶ci, trudno siê dziwiæ, ¿e nie potrafi³ on znale¼æ jakiego¶ wentyla bezpieczeñstwa, przez który móg³by dawaæ upust swojej jedynej wadzie, niegodnej tak oficera, jak mê¿czyzny. Stopniowe uwalnianie albo sublimacja gwa³townego - i gwa³townie narastaj±cego - gniewu wywo³anego frustracj± w jego wypadku nie wchodzi³y w rachubê, mimo i¿ oscyluj±ca wokó³ punktu wrzenia w¶ciek³o¶æ nie wp³ywa³a najlepiej na jego ci¶nienie.
');
INSERT INTO texts (name, text) VALUES ('tekst07b.txt', '
A jednak kolejny paradoks sprawi³, ¿e uratowa³y go potencjalnie ¶mierciono¶ne wentylatory. Bez namys³u, instynktownie, wyci±gn±³ rêkê i z³apa³ za jeden z nich. Odniós³ wra¿enie, ¿e co¶ wyrwa³o mu prawe ramiê z barku, wentylator brutalnie wydar³ siê z jego u¶cisku, lecz szybko¶æ, z jak± sun±³, wyra¼nie siê zmniejszy³a. Ponownie wyci±gn±³ rêkê. Znów przeszy³ go dojmuj±cy ból, ale teraz ju¿ ¶lizga³ siê w tempie nieomal spacerowym. Zobaczy³, ¿e zbli¿a siê trzecie i ostatni wentylator. Tym razem obj±³ go obur±cz i zacisn±³ lew± rêkê na prawym nadgarstku. Czu³, ¿e jaka¶ potê¿na si³a znowu wyrywa mu prawe ramiê, czy¿by odros³o mu nowe? Ale trzyma³ siê twardo. Zatoczy³ szeroki ³uk, wypadaj±c nogami poza dach. Ale trzyma³ siê dalej. Wiedzia³, ¿e musi co¶ zrobiæ, bo si³y go opuszczaj±. Powoli, zmagaj±c siê z bólem, podci±gn±³ siê na ¶rodek dachu, doczo³ga³ na ty³ wagonu i nie tyle zszed³, co spad³ na pomost.
');
INSERT INTO texts (name, text) VALUES ('tekst07.txt', '
Widz±c zbli¿aj±c± siê ga³±¼ sosny, nie waha³ siê ani chwili. Wiedzia³, ¿e je¿eli nie zrobi tego teraz, prawdopodobnie nie zdobêdzie siê po raz drugi na tak samobójczy krok. ¯eby z³agodziæ skutki zderzenia, cofn±³ siê szybko, rozk³adaj±c szeroko rêce na wysoko¶ci piersi. Z³apa³ ga³±¼ obur±cz i z przera¿eniem stwierdzi³, ¿e jest o wiele cieñsza ni¿ przypuszcza³ - zmyli³a go gruba warstwa ¶niegu. Ga³±¼ ugiê³a siê. Desperacko zarzuci³ na ni± nogi i wisz±c w ten sposób, szybowa³ pó³ metra nad dachem. Zerkn±³ w dó³. Nie¶wiadom niczego Carlos mign±³ mu zaledwie trzydzie¶ci centymetrów pod plecami i znikn±³ z widoku. Deakin opu¶ci³ nogi i ¿³obi±c obcasami podwójny ¶lad na oblodzonym dachu, spogl±da³ do ty³u. Nagle pu¶ci³ ga³±¼, wiedz±c doskonale, ¿e który¶ ze stercz±cych wentylatorów mo¿e mu wypruæ wnêtrzno¶ci.
');
INSERT INTO texts (name, text) VALUES ('tekst08.txt', '
Jestem przekonany, ¿e wszystkie te dobre uczynki mam do zawdziêczenia mojej taktyce niestosowania przemocy. Gdybym zabiega³ o ponowne przyjêcie mnie do kasty, usi³owa³ j± rozbiæ na poszczególne obozy lub zachowa³ siê prowokacyjnie wobec jej cz³onków, ci z pewno¶ci± odwzajemniliby siê w podobny sposób i zamiast szczê¶liwie unikn±æ burzy po przybyciu z Anglii, wpad³bym w sam wir rozagitowania, kto wie, czy nie uprawianego czê¶ciowo za moimi plecami. Mój stosunek do ¿ony wci±¿ jeszcze nie by³ taki, jakiego pragn±³em. Nawet pobyt w Anglii nie uleczy³ mnie z zazdro¶ci. By³em w dalszym ci±gu drobnostkowy i zazdrosny o byle co, a wszystkie moje najbardziej utajone pragnienia zostawa³y nie zaspokojone.
');
INSERT INTO texts (name, text) VALUES ('tekst09.txt', '
Którego¶ dnia do kuwety stoj±cej w ciemni fotograficznej wpu¶ci³em karpia. Wrzaski niczego nie podejrzewaj±cej dziewczyny rozleg³y siê na ca³± szko³ê. Ten niewinny ¿arcik poci±gn±³ za sob± ¶ledztwo na wielk± skalê. Re¿yserowa³em te¿ bardziej wyrafinowane skecze. Pewnego razu zaaran¿owa³em gwa³town± sprzeczkê z Majewskim. K³óc±c siê zawziêcie, zapomniawszy na pozór o bo¿ym ¶wiecie, przeszli¶my korytarzem, nastêpnie schodami w dó³, a¿ dotarli¶my do gabinetu, gdzie urzêdowa³a u³omna sekretarka rektora, Nina. Grupa kolegów, których wtajemniczyli¶my w sprawê, usi³owa³a nas rozdzieliæ, ale bez skutku.
');
INSERT INTO texts (name, text) VALUES ('tekst10.txt', '
Pary¿ jest miastem stworzonym dla spacerów. Podczas której¶ z naszych nocnych przechadzek - wcze¶niej wkrêcili¶my na studenck± zabawê w Akademii Sztuk Piêknych - zabra³em Gesê, ¿eby pokazaæ jej Hale. Zaledwie o kilka minut od Luwru zapu¶cili¶my siê w w±skie uliczki, zas³ane li¶æmi kapusty i odpadkami wszelkiego rodzaju jarzyn. Widz±c niewielkie na pozór, st³oczone stragany, sklepy i magazyny, trudno by³o uwierzyæ, ¿e st±d rozprowadza siê niemal ca³± ¿ywno¶æ dla Pary¿a i pó³nocnej Francji. Kierowca, który dotrze noc± w g³±b Hal, mo¿e uwa¿aæ siê za szczê¶ciarza, je¶li przed ¶witem uda mu siê wydostaæ z labiryntu ciê¿arówek wioz±cych wszelkiego rodzaju bogactwa: od po³ci wo³owiny do homarów i krêgów ¿ó³tego sera.
');
INSERT INTO texts (name, text) VALUES ('tekst11.txt', '
Pod jednym wzglêdem ksi±¿ka nie odpowiada³a mi: by³em agnostykiem - w równym stopniu nie wierzy³em w szatana jako wcielenie z³a, co w uosobienie Boga. Ca³y pomys³ "Dziecka Rosemary" k³óci³ siê z moj± racjonaln± wizj± ¶wiata. Aby wiêc film sta³ siê wiarygodny, postanowi³em zastosowaæ pewien wybieg: dopu¶ciæ interpretacjê, ¿e nadprzyrodzone prze¿ycia Rosemary s± wytworem jej wyobra¼ni. Ca³a historia ogl±dana z jej punktu widzenia mog³a wydawaæ siê jedynie ci±giem koszmarnych zbiegów okoliczno¶ci, produktem rozgor±czkowanej wyobra¼ni bohaterki. Knowania s±siadów, sabat czarownic, w czasie którego, w obecno¶ci mê¿a, szatan bierze j± przemoc± oraz koñcowa scena przy ko³ysce musia³y mieæ racjonalne wyt³umaczenie. Oto dlaczego przez ca³y film rozmy¶lnie przewija siê niæ dwuznaczno¶ci.
');
INSERT INTO texts (name, text) VALUES ('tekst12b.txt', '
Kiedy ju¿ by³o po wszystkim, ja i moja partnerka ubrali¶my siê i siedz±c na dwóch taboretach, gwarzyli¶my dopijaj±c szampana. Tymczasem sala opustosza³a. Opuszczono kurtynê, ostatni klienci wyszli, a obs³uga ustawia³a krzes³a na stolikach. Orkiestra usadowi³a siê wówczas tu¿ pod nasz± lo¿± i muzycy zagrali wiedeñskiego walca, ¶l±c w nasz± stronê têskne spojrzenia. "Król Pralni" nonszalancko siêgn±³ do kieszeni, wyci±gn±³ gruby plik stuszylingowych banknotów i rozrzuci³ je dostojnym gestem siewcy. Poszybowa³y ku muzykom, jak jesienne li¶cie. Zbierali je dyskretnie, nie uroniwszy ani jednej nuty.
');
INSERT INTO texts (name, text) VALUES ('tekst12.txt', '
Po odkorkowaniu szampana osobnik dyskretnie siê wycofa³. Wówczas dziewczyna zrzuci³a z siebie ubranie i zosta³a tylko w pantoflach na wysokim obcasie, czarnych siatkowych poñczochach i podwi±zkach: wygl±da³a jak postaæ z rysunku Kokoschki. Kiedy mnie rozbiera³a, zerkn±³em, co siê dzieje na dole. Prestidigator z niezwyk³± zrêczno¶ci± prezentowa³ swój numer. Panienka z równ± wpraw± wyczarowa³a prezerwatywê i szybko mi j± na³o¿y³a. Potem goln±wszy sobie szampana siad³a na mnie okrakiem i zabra³a siê do roboty. Zu¿yt± prezerwatywê wrzuci³a do kube³ka z szampanem. Zachowa³em gdzie¶ w pamiêci mglisty obraz nagiego Sama goni±cego po lo¿ach równie nag± dziewczynê.
');
INSERT INTO texts (name, text) VALUES ('tekst13.txt', '
Coraz bardziej nienawidzi³ tego Pope. Cz³owiek mo¿e siê u¶miechaæ, a byæ ³ajdakiem. Bezlitosnym, zdradliwym, wszetecznym, zepsutym ³ajdakiem. Co w³a¶ciwie znacz± te s³owa? Mia³ tylko niejasne pojêcie. Ale ich czar by³ silny, szumia³y mu w g³owie, i zda³o mu siê, ¿e dotychczas nie czu³ do Pope prawdziwej nienawi¶ci; nigdy dot±d nie nienawidzi³ go tak naprawdê, bo nigdy dot±d nie umia³ wypowiedzieæ, jak bardzo go nienawidzi. A teraz mia³ ju¿ te s³owa, s³owa jak bêbny, jak ¶piew i zaklêcia. Te s³owa i dziwna, dziwna opowie¶æ, z której pochodzi³y (nie potrafi³ zebraæ jej w ca³o¶æ, ale i tak by³a cudowna, cudowna), pozwoli³y mu nienawidziæ Pope; uczyni³y tê nienawi¶æ bardziej realn±; nawet samego Pope uczyni³y bardziej realnym.
');
INSERT INTO texts (name, text) VALUES ('tekst14.txt', '
Z³apa³em znów za plazmówkê i bez ceregieli wbi³em mu widelcowate zakoñczenie lufy prosto w serce (to znaczy tam, gdzie wydawa³o mi siê, ¿e ono jest). Aby dobiæ go zupe³nie, wystrzeli³em. Tym razem zaskoczy³ mnie ca³kowicie; zamiast osun±æ siê martwym na ziemiê, zacz±³ miotaæ siê na wszystkie strony jak szaleniec. Z¿eraj±ca go od ¶rodka plazma wydawa³a jakby zagêszczony d¼wiêk ton zgniatanego papieru. W pewnym momencie pomy¶la³em nawet, ¿e wybuchnie i jakie¿ by³o moje zdziwienie, gdy tak w³a¶nie siê sta³o: powietrze przeszy³ g³o¶ny huk, i ca³a górna czê¶æ jego cia³a znik³a w k³êbach ¿ó³tego py³u. Dolna pad³a na ziemiê jak kawa³ czarnego p³ótna. Ci±gn±c za sob± warkocz dymu, co¶ zwêglonego spad³o tu¿ pod moje stopy i poturla³o siê jeszcze przez kilka metrów. To musia³a byæ jego czaszka.
');
INSERT INTO texts (name, text) VALUES ('tekst15.txt', '
Liu Kang wraca³ pó¼nym wieczorem do mieszkania po³o¿onego na przedmie¶ciu Nowego Jorku. Wybra³ tê okolicê specjalnie po to, aby w wolnych chwilach móc bez obaw poæwiczyæ. Nie wszyscy s±siedzi lubi± facetów ubranych w same spodnie, lataj±cych z jednego koñca ogródka na drugi z nogami wysuniêtymi do przodu i wrzeszcz±cych przy tym niemi³osiernie. W momencie, gdy Kang otwiera³ furtkê, wiedzia³ ju¿, ¿e pope³ni³ b³±d. U³amek sekundy pó¼niej upad³ twarz± na chodnik po silnym kopniêciu. Jednak klasztor Szaolin wyrobi³ w nim pewne zachowania które prawdopodobnie uratowa³y mu ¿ycie. B³yskawicznie poderwa³ siê na nogi unikaj±c tym samym mia¿d¿±cego buta. Jeszcze w tej samej sekundzie wyprowadzi³ dwa szybkie ciosy lew± nog± prosto w gard³o pozbawiaj±c przeciwnika oddechu, a chwilê pó¼niej ¿ycia.
');
INSERT INTO texts (name, text) VALUES ('tekst16b.txt', '
Rozejrza³ siê. Woko³o by³ tylko las i droga. Las. Postanowi³, ¿e ukryje siê miêdzy drzewami i poczeka na roboty. Wprawdzie przeciwko trzem mia³ ma³e szanse, ale mia³ nadziejê, ¿e mo¿e siê rozdziel±. Wszed³ g³êbiej w las. Dotychczas roboty trzyma³y siê bezb³êdnie jego ¶ladów. Liczy³, ¿e miêdzy drzewami trochê siê pogubi± i ofiara zamieni siê w my¶liwego. W pewnym momencie zamajaczy³o mu w oddali migaj±ce ¶wiate³ko. Ruszy³ w tamt± stronê. ¦wiate³ko okaza³o siê ma³ym ogniskiem, przy którym siedzia³o dwoje ludzi. A on zna³ tych ludzi.
');
INSERT INTO texts (name, text) VALUES ('tekst16.txt', '
Ucieka³ ju¿ mniej wiêcej dwie godziny. Zaczyna³o mu brakowaæ oddechu. Podczas biegu zastanawia³ siê, jak go znale¼li. Ju¿ wcze¶niej ukry³ siê poza miastem, gdy¿ przewidzia³, ¿e mo¿e zostaæ zdradzony. Teraz gonili go jego dawni przyjaciele. Chcieli go zabiæ. Wszystko by³o dobrze do czasu, gdy w laboratorium opracowano nowy model cyborga, który by³ lepszym wojownikiem ni¿ ludzie. Po tym wszystkim sta³ siê on niepotrzebny. A poniewa¿ za du¿o wiedzia³, chciano go zlikwidowaæ. Trzy wys³ane za nim roboty wpad³y na trop dopiero dwie godziny temu. Od tego czasu zacz±³ siê szaleñczy wy¶cig cz³owieka z maszynami. Przystan±³ i obejrza³ siê za siebie. Za nim rozci±ga³a siê pusta ulica. Ogóln± ciemno¶æ rozja¶nia³y postawione tu i ówdzie latarnie. Wzi±³ g³êbszy oddech i pobieg³ dalej, ale po kilku minutach zatrzyma³ siê ponownie. Zadecydowa³, ¿e najwy¿szy czas przej¶æ do ofensywy.
');
INSERT INTO texts (name, text) VALUES ('tekst17.txt', '
Gdy powiedzia³, ¿e j± kocha, zapyta³a, czy prêdko siê pobior±. Wówczas on o¶wiadczy³, ¿e niestety, ale jest ¿onaty. By³a tym tak zgnêbiona, ¿e chcia³a zaraz i¶æ do domu, a on nie pu¶ci³ jej, dopóki nie obieca³a, ¿e jutro przyjdzie. Nie przysz³a jednak wiêcej, a to dlatego, ¿e zwierzy³a siê nazajutrz kole¿ance z siódmej klasy, pannie Jó¼wiñskiej, ta za¶ wyt³umaczy³a Magdzie wiele rzeczy, o których Magda dotychczas pojêcia nie mia³a. Drug± mi³o¶ci± by³ w³a¶nie brat Toli Jó¼wiñskiej. Zaprzyja¼ni³y siê po tych zwierzeniach i Tola zaprasza³a j± do siebie na potañcówki. Pan Jó¼wiñski by³ bardzo bogatym adwokatem, a Karol studiowa³ na politechnice, mia³ motocykl z wózkiem i kilka razy zabiera³ Magdê a¿ za Wilanów.
');
INSERT INTO texts (name, text) VALUES ('tekst18b.txt', '
Kilkakrotnie odbywano wycieczki do lasów, le¿±cych na Dalekim Zachodzie. Koloni¶ci nie obawiali siê zbyt wysokiej temperatury, bo promienie s³oneczne zaledwie gdzieniegdzie zdo³a³y siê przedrzeæ przez nadzwyczaj gêste sklepienie lasu. Zwiedzili ca³y lewy brzeg Rzeki Mi³osierdzia. Wybieraj±c siê na te wycieczki, zawsze dobrze siê uzbrajali, gdy¿ czêsto zachodzi³y im drogê dziki nadzwyczaj zuchwa³e, z którymi musieli staczaæ uparte walki.
W tej tak¿e porze roku Gedeon i Harbert rozpoczêli straszn± wojnê z jaguarami. Obaj my¶liwi uzupe³niali siê wzajemnie. Harbert by³ nadzwyczaj odwa¿ny, reporter odznacza³ siê zimn± krwi± i przezorno¶ci±. Dziêki tym zapalonym my¶liwym ju¿ przesz³o dwadzie¶cia prze¶licznych skór jaguarów zdobi³o ¶ciany wielkiej sali Granitowego Pa³acu, z czego mo¿na by³o wnosiæ, ¿e potrafi± osi±gn±æ zamierzony cel i oczyszcz± wyspê z tych niebezpiecznych zwierz±t.
');
INSERT INTO texts (name, text) VALUES ('tekst18.txt', '
12 lutego ca³a instalacja by³a ju¿ wykoñczona, i zaraz Cyrus zapyta³ Ayrtona, czy co z³ego nie zasz³o w owczarni; w kilka minut odebra³ zadowalaj±c± odpowied¼. Penkroff nie posiada³ siê z rado¶ci i codziennie rano i wieczór wysy³a³ telegramy do owczarni, na które zawsze odbiera³ ¿±dane odpowiedzi.
Urz±dzenie telegrafu zapewnia³o podwójn± korzy¶æ: po pierwsze mogli zawsze wiedzieæ, czy Ayrton nie opu¶ci³ chaty, a po wtóre, nie pozwalali mu zostawaæ w zupe³nym odosobnieniu. Oprócz tego Cyrus odwiedza³ go regularnie przynajmniej raz na tydzieñ, a ilekroæ Ayrton przybywa³ do Granitowego Pa³acu, przyjmowano go ¿yczliwie.
');
INSERT INTO texts (name, text) VALUES ('tekst19.txt', '
Powrócili wszyscy do niej, aby przyjrzeæ siê lepiej. Mia³a piêæ stóp d³ugo¶ci, a trzy szeroko¶ci; by³a starannie zamkniêta i pokryta grub± skór±, przybit± mosiê¿nymi gwo¼dziami; dwie pró¿ne beczu³ki, szczelnie zaszpuntowane, przywi±zane by³y do jej boków mocnymi powrozami. Nie znaæ na niej by³o ¿adnego uszkodzenia, co mo¿na by przypisaæ temu, ¿e morze wyrzuci³o j± na piasek, a nie miêdzy ska³y. Nadto, przyjrzawszy siê jej bacznie, trudno by³o nie poznaæ, ¿e nied³ugo przebywa³a w morzu i niedawno osiad³a na piasku.
Morze tymczasem przybiera³o ci±gle i woda dochodzi³a ju¿ do skrzyni. Nab i Penkroff odrzucili obsypuj±cy j± piasek i wkrótce ³ódka, ci±gn±c za sob± skrzyniê, oddali³a siê od w±skiego pasa ziemi, który nazwano Cyplem Skrzyni.
');
INSERT INTO texts (name, text) VALUES ('tekst20b.txt', '
Bardzo mo¿liwe, ¿e w Gedeonie odezwa³a siê ¿y³ka dziennikarska i pragn±³ wys³aæ w ¶wiat krótki artykulik streszczaj±cy przygody kolonistów Wyspy Lincolna przewiduj±c, jak wielkiego tam narobi rozg³osu. Opisa³ wszystko, co siê sta³o, tre¶ciwie na æwiartce papieru, i do³±czy³ usiln± pro¶bê, aby ktokolwiek znajdzie to pismo, przes³a³ je natychmiast do redakcji New York Heralda. Nastêpnie w³o¿y³ karteczkê do ma³ego woreczka z gumowego p³ótna i przywi±za³ go nie do nogi, lecz do szyi albatrosa, gdy¿ te ptaki odpoczywaj± zwykle na powierzchni morza. Gdy wreszcie wypu¶cili powietrznego goñca, z widocznym wzruszeniem patrzyli, dopóki nie znikn±³ im z oczu, lec±c ku zachodowi.
');
INSERT INTO texts (name, text) VALUES ('tekst20.txt', '
W tym czasie koloni¶ci po raz pierwszy spróbowali porozumieæ siê z lud¼mi. Gedeon Spilett od dawna nosi³ siê z tym, aby powierzyæ ma³± karteczkê go³êbiowi lub w zakorkowanej dobrze butelce rzuciæ j± w morze. Zaniecha³ jednak tego zwa¿ywszy, ¿e niepodobna by³o przypu¶ciæ, aby go³±b lub butelka mog³y przebyæ odleg³o¶æ tysi±ca dwustu mil, które oddziela³y wyspê od zamieszkanej ziemi. W ostatnim dniu czerwca uda³o siê Harbertowi schwytaæ albatrosa, którego przedtem zrani³ w nogê strza³em z fuzji. By³ to wielki ptak, którego rozpostarte skrzyd³a mia³y dziesiêæ stóp d³ugo¶ci, móg³ wiêc przebyæ Ocean Spokojny.
');
INSERT INTO texts (name, text) VALUES ('tekst21.txt', '
Ca³a robota zajê³a dwadzie¶cia cztery godziny. Po wielu próbach uda³o im siê porobiæ knoty z w³ókien ro¶linnych, które umoczone w roztopionej stearynie, utworzy³y ¶wiece; brak³o im tylko wybielania i politury. Wprawdzie nie dorównywa³y one ¶wiecom, których knoty nasycone s± kwasem borny, spalaj± siê w miarê topienia stearyny i dlatego nie potrzebuj± obcinania, ale Cyrus Smith zrobi³ dobre szczypce i ¶wiece te bardzo by³y u¿yteczne podczas d³ugich wieczorów.
Przez ca³y ten miesi±c pracowali gorliwie w nowym mieszkaniu. Stolarskiej roboty nie zabrak³o, a oprócz tego udoskonalano i uzupe³niano narzêdzia.
Mogli ju¿ zrobiæ sobie no¿yczki i poobcinaæ w³osy, spadaj±ce prawie na ramiona. Nab i Harbert nie mieli zarostu, lecz towarzysze ich wygl±dali okropnie, wiêc teraz mogli przynajmniej skróciæ brody, w±sy i faworyty.
');
INSERT INTO texts (name, text) VALUES ('tekst22.txt', '
O jedenastej przed po³udniem ¿eglarze byli ju¿ tylko o dwie mile od wyspy, czy raczej wysepki, jak j± nazwa³ Harbert, przypatrzywszy siê jej lepiej, i mogli ju¿ rozró¿niæ grupy rozmaitych drzew. Dziwi³o ich, ¿e nie dostrzegli nigdzie dymu, a na wybrze¿u ¿adnego sygna³u pozwalaj±cego wnosiæ, ¿e cz³owiek tu siê znajduje i wzywa pomocy przep³ywaj±cych statków. Dokument znaleziony w butelce nie pozwala³ jednak w±tpiæ o tym.
Statek przesuwa³ siê ostro¿nie przez w±skie przesmyki miêdzy ska³ami, które Penkroff ¶ledzi³ bacznie, stoj±c na dziobie statku, gdy tymczasem Harbert zastêpowa³ go przy sterze. Na koniec oko³o po³udnia zbli¿ono siê do piaszczystego wybrze¿a, zwiniêto ¿agiel i rzucono kotwicê.
');
INSERT INTO texts (name, text) VALUES ('tekst23.txt', '
Trzy dni pó¼niej wielki, czarny lincoln continental sun±³ zat³oczonymi ulicami Waszyngtonu. Na tylnym siedzeniu, oddzielonym od kierowcy szyb±, siedzia³ starszy, dystyngowany pan o starannie zaczesanych, srebrzystoszarych w³osach. O takim odcieniu mówi siê "salt and pepper". Obok niego na siedzeniu spoczywa³a aktówka z czarnej, cielêcej skóry. By³y w niej trzy kartki papieru, egzemplarz gazety z zakre¶lonym flamastrem komunikatem umieszczonym u do³u drugiej strony oraz przypiête spinaczem t³umaczenie tekstu na jêzyk angielski. Jego tre¶æ sprawia³a, ¿e starszy pan my¶la³ intensywnie, a nie by³y to my¶li weso³e.
');
INSERT INTO texts (name, text) VALUES ('tekst24b.txt', '
Dzieñ by³ ³adny, wiêc po ¶niadaniu poszed³ na spacer, ciesz±c siê niepowtarzaln± atmosfer±, jaka zawsze panuje tam, dok±d przybywa parê tysiêcy m³odych ludzi ze wszystkich stron ¶wiata. Kto¶ wpad³ na pomys³ znakomicie rozwi±zuj±cy problem poruszania siê po rozleg³ym terenie wioski, wprowadzaj±c ma³e rowerki. Od razu cieszy³y siê olbrzymim powodzeniem. By³o ich w wiosce tysi±ce i w niektórych miejscach trzeba by³o uwa¿aæ, by nie zostaæ staranowanym przez ho¿± dziewojê, pêdz±c± na z³amanie karku. Niektórzy zreszt± specjalnie wystawali w takich miejscach.
Polscy floreci¶ci wymy¶lili zabawê w pi³kê rowerowo-no¿n± na trawie i odt±d na placyku przed gmachem, gdzie mieszkali zbiera³a siê coraz liczniejsza grupka kibiców nowego sportu. Jerzy wzi±³ raz tylko udzia³ w takim meczu, ale st³uk³ piszczel i od tego czasu postanowi³ udzielaæ siê wy³±cznie jako sympatyk tego sportu.
');
INSERT INTO texts (name, text) VALUES ('tekst24.txt', '
W¶ród u¶miechów, poklepywañ i gratulacji, czu³, ¿e jeszcze jest co¶ wart, on i jego ambicja. Pojawiaj±ce siê od czasu do czasu na horyzoncie widmo Padwy stawa³o siê coraz bardziej zwiewne i wyblak³e. Stosunki z Dropakiem by³y zimne, lecz poprawne. ¯aden nie ryzykowa³ ostatecznej rozgrywki. Nie stwarza³o to najlepszej atmosfery nawet tu, w Tokio, ale na szczê¶cie gor±czka przedstartowa zepchnê³a wszystko na dalszy plan.
Uspokoiwszy siê nieco poszed³ do mikroskopijnej ³azienki, wzi±³ tusz, po czym u³o¿y³ siê na kozetce i momentalnie zapad³ w sen.
Ranek przyniós³ wyja¶nienie wczorajszych niepokojów. Okaza³o siê, ¿e prze¿y³ pierwsze w ¿yciu trzêsienie ziemi. Nie by³o to silne, gazety po¶wiêca³y mu zaledwie kilkuwierszowe wzmianki.
');
INSERT INTO texts (name, text) VALUES ('tekst25b.txt', '
W ekipie s± przekonani, ¿e ma zapewnione ju¿ miejsce w finale, gdy¿ ostatni± przeszkod± jest W³och Cesare Salwadore, zawodnik zdecydowanie s³abszy.
Ale kto mo¿e byæ pewny czego¶ w sporcie do koñca? Gdy wywo³uj± ich walkê, Paw³owski jest trochê zmêczony, natomiast W³och - jakby chcia³ zmieniæ niepochlebn± opiniê o sobie - atakuje z furi± i trafia. Jerzy szybko przezwyciê¿a kryzys i zaskoczenie, ale impet W³ocha dzia³a deprymuj±co. Pierwsz± walkê wygra³ zaledwie jednym trafieniem, drug± przegra³ do trzech i o wszystkim ma zadecydowaæ ostatnia, trzecia walka.
W³osi ju¿ szalej± z rado¶ci. Im w ogóle niewiele trzeba, ca³± grup± masuj± Salwadoremu nogi, ha³as czyni± niemo¿liwy, a jego przeciwnik...
');
INSERT INTO texts (name, text) VALUES ('tekst25.txt', '
Tu ju¿ zaczynaj± siê problemy. Co prawda system ten daje jeszcze szansê w repasa¿ach, ale przecie¿ wiadomo, ¿e je¿eli nie wyeliminuje swych rywali, to sam odpadnie. ¯ona jest pierwszy raz z nim na mistrzostwach ¶wiata i od rana nie opuszcza hali. Trochê to przeszkadza, ale z drugiej strony...
Do rundy ósemkowej wchodzi bez problemu. Dawno ju¿ mu siê tak dobrze nie walczy³o. Jakby znik³y gdzie¶ k³opoty i zmory, zw³aszcza jedna z nich. Jakby nie spêdzi³ setek godzin na treningach, jakby nie by³o tych trudnych momentów, kiedy siê ma wszystkiego do¶æ, chce siê rzuciæ z rozmachem, a¿ zajêczy, szablê i maskê i pój¶æ gdzie¶ przed siebie.
');
INSERT INTO texts (name, text) VALUES ('tekst26b.txt', '
Z przera¿eniem czeka³ na szczêk metalu, na wybuch i wdarcie siê wody, na potwierdzenie tej strasznej pewno¶ci, ¿e znalaz³ siê w pu³apce, ¿e woda go zadusi, zanim zd±¿y ruszyæ siê z miejsca.
Której¶ nocy uda³o mu siê zasn±æ, mimo ¿e ostrzegano o grupie okrêtów podwodnych gdzie¶ w pobli¿u. Zapad³ w drzemkê po godzinie napiêtej czujno¶ci i w³a¶nie wtedy, pomiêdzy snem a jaw±, us³ysza³ potworny wybuch, jak gdyby w samym wnêtrzu okrêtu. Kiedy wyskoczy³ z koi, rozleg³ siê klakson na alarm i zaraz potem pospieszny tupot nóg. Pêdzi³ co si³ do trapu, do otwartego nieba. Czu³, jak zalewa go fala ¶lepego strachu.
');
INSERT INTO texts (name, text) VALUES ('tekst26.txt', '
Móg³ zej¶æ na dó³ i spaæ w swej kabinie bez przerwy a¿ do rana. Nigdy jednak z tego nie korzysta³, chyba na samym pocz±tku i na koñcu rejsu, kiedy p³ynêli po wodach spokojnych i bezpiecznych. Ju¿ w samym fakcie uk³adania siê do snu poni¿ej linii wodnej by³o co¶, co drêczy³o jego wyobra¼niê. Zdawa³o mu siê zupe³nie wykluczone, aby w ci±gu tej nocy torpeda mog³a nie trafiæ w korwetê. A je¶li trafi, to wedrze siê na pewno a¿ tu, do jego kabiny... W bezsenne noce na otwartym bezkresnym Atlantyku wraca³y koszmarne my¶li. Okrêt stale ko³ysa³ siê i stêka³, a woda przep³ywa³a o kilka cali od jego pos³ania. Poci³ siê z lêku, wpatrywa³ siê w gród¼ i w nity, które trzyma³y razem cienkie blachy poszycia. Tylko to poszycie dzieli³o go od ciemnej wody.
');
INSERT INTO texts (name, text) VALUES ('tekst27b.txt', '
Tomlinson czu³ siê lepiej obs³uguj±c pospiesznie klientów, którzy ¿±dali gor±cych pasztecików lub suchej kie³basy (wy³±cznie za gotówkê, bez ¿adnych reklamacji!), ni¿ w wytworniejszym ¶wiecie mesy oficerskiej. Poniewa¿ jednak Lockhart dawnym zwyczajem zasiada³ do swych samotnych posi³ków z ksi±¿k± w rêku, nie dra¿ni³y go ani niedba³a obs³uga, ani bezbarwne jedzenie.
Korweta by³a przycumowana tu¿ obok "Viperous", na którym tak¿e czyszczono kot³y. Po raz pierwszy Lockhart mia³ mo¿no¶æ z bliska ogl±daæ niszczyciela. Korzystaj±c z tego s±siedztwa, odwiedza³ do¶æ czêsto kolegê na bratnim okrêcie. By³ nim podporucznik ze s³u¿by zawodowej, pozostawiony równie¿ na dy¿urze, gdy inni poszli na urlop.
');
INSERT INTO texts (name, text) VALUES ('tekst27.txt', '
Lockhart wyci±gn±³ los, ¿e zostanie jako dy¿urny oficer na okrêcie. Jego kolej na urlop mia³a przyj¶æ nastêpnym razem. Nie uwa¿a³ siê wcale za skrzywdzonego. Ostatnio dosta³ awans na porucznika. Dodatkowy z³ocisty pasek b³yszcza³ na rêkawie, potêguj±c poczucie odpowiedzialno¶ci. Poza tym móg³ za¿yæ odpoczynku, jakiego potrzebowa³. Wolne chwile spêdza³ na urlopie - czyta³ i s³ucha³ radia, rozpl±tywa³ skomplikowany wêze³ ostatnich miesiêcy. Na "Compass Rose" wygaszono kot³y, wentylatory nie dzia³a³y, by³o ch³odno i cicho. Dziwne wra¿enie sprawia³a korweta, przedtem zawsze aktywna i ruchliwa, a teraz zawieszona w mg³awicy lenistwa, jak on sam. Mia³ bardzo ma³o do roboty, a ju¿ zupe³nie nic takiego, co wymaga³oby skupienia. Po ¶niadaniu robi³ przegl±d za³ogi i zapowiada³ Phillipsowi, co trzeba w tym dniu sprz±tn±æ i co pomalowaæ.
');
INSERT INTO texts (name, text) VALUES ('tekst28b.txt', '
Wci±¿ siê mylili, spó¼niali, robota nie wychodzi³a. Dziwili siê, kiedy co¶ posz³o g³adko, a gdy siê nie uda³o, spogl±dali posêpnie, obojêtnie. Pozostawiony sam sobie, Ferraby pewnie by okrzep³ i stopniowo doprowadzi³ swój dzia³ do stanu sprawno¶ci. Lecz Bennett cel ³atwiejszy od Lockharta. £azi³ wiêc bez ustanku na pok³ad nad ruf± i przechyliwszy siê przez reling, zasypywa³ m³odszego oficera mnóstwem uwag i sprzecznych rozkazów, kruszy³ na proch tê odrobinê ufno¶ci w swe si³y, jak± Ferraby zdo³a³ odbudowaæ. Dosz³o do tego, ¿e Ferraby ze strachem rozpoczyna³ æwiczenia, które musia³ prowadziæ co dzieñ w czasie ca³ego postoju w porcie.
');
INSERT INTO texts (name, text) VALUES ('tekst28.txt', '
Ferraby, odosobniony na rufie wraz ze swoimi bombami, nie móg³ siê pochwaliæ sukcesem w podci±gniêciu swych ludzi do jakiego¶ zno¶nego poziomu. Obydwu starszym marynarzom trudno by³o cokolwiek zarzuciæ - obaj byli zupe³nie pewni i energiczni. Torpedysta Wainwright odbezpiecza³ i nastawia³ bomby, a tak¿e sam je wyrzuca³. Starszy marynarz Tonbridge sta³ na czele ca³ej obs³ugi wyrzutni. Lecz reszta ludzi by³a w wiêkszo¶ci poni¿ej przeciêtnego poziomu. Praca ich polega³a na szybkim wk³adaniu bomb do opró¿nionych przedzia³ów. Wymaga³o to zgranego wspó³dzia³ania zespo³u ludzi. Ferraby rozporz±dza³ do¶æ przypadkowym kompletem marynarzy z maszyny, którzy nie mieli wachty, oraz radiotelegrafistów nie kwapi±cych siê zbytnio do pracy na pok³adzie, gdzie wiatr przewiewa³ cz³owieka na wylot.
');
INSERT INTO texts (name, text) VALUES ('tekst29b.txt', '
Starszy marynarz Tonbridge mia³ dwadzie¶cia trzy lata, by³ dzieckiem londyñskich slumsów i mia³ za sob± siedem lat s³u¿by w Royal Navy. Fakt, ¿e nie uciek³ od tej próby, ¿e potrafi³ okazaæ sprawno¶æ w dzia³aniu, wykracza³ swoj± tre¶ci± poza wszelkie normalne pochwa³y.
Robili, co tylko mogli. Wios³owali w ciemno¶ci, kieruj±c siê wo³aniem, przera¿eni do szpiku ko¶ci zduszonym krzykiem ludzi, którzy tonêli, zanim zdo³ali podp³yn±æ. Ze wszystkich si³ starali siê ratowaæ i pomagaæ. Wyci±gnêli czternastu ludzi: jeden ju¿ nie ¿y³, drugi by³ konaj±cy, o¶miu rannych, a pozostali oszo³omieni wstrz±sem i ca³kowicie wyczerpani. Niewiele brakowa³o, a by³oby piêtnastu.
');
INSERT INTO texts (name, text) VALUES ('tekst29.txt', '
Gdy Tonbridge uj±³ za rumpel i spojrza³ w jego kierunku chc±c wzi±æ w³a¶ciwy kurs, rozleg³ siê ponad wod± zgrzyt rozdzieranej stali i statek zacz±³ siê pogr±¿aæ. Tonbridge patrzy³, wstrz±¶niêty do g³êbi groz± i lêkiem. Nigdy nie widzia³ czego¶ podobnego, nigdy nie powierzono mu jeszcze takiego zadania. Nie³atwo bêdzie je spe³niæ jak nale¿y. Wystarczy³o, ¿e odeszli od "Compass Rose" w sam ¶rodek ciemno¶ci, ¿e widzieli, jak ich okrêt rozp³ywa siê w mroku, ¿e konwój tak¿e znik³ w oddali, oni za¶ byli sami w maleñkiej ³odzi pod niebem pe³nym gwiazd, po¶ród wielkiego, nieprzyjaznego oceanu. Ale to, na co musieli patrzeæ teraz, podobne by³o raczej do zmory sennej ni¿ do jawy: storpedowany statek zanurza³ siê w ich oczach, ludzie, miotaj±c siê w wodzie, krzyczeli rozpaczliwie, dusz±cy zapach ropy niós³ siê ciê¿k± fal± w powietrzu.
');
INSERT INTO texts (name, text) VALUES ('tekst30b.txt', '
Potworny zgie³k sk³êbiony nad konwojem osi±gn±³ punkt kulminacyjny w chwili, gdy samolot zrzuci³ dwie bomby na czo³o ¶rodkowej kolumny: jedna upad³a w morze, wzbijaj±c ogromny, pierzasty s³up wody, po³yskuj±cy w po¶wiecie ksiê¿yca; druga trafi³a w cel. Trzasnê³a z metalicznym szczêkiem w statek, którego nie mogli dojrzeæ i którego na pewno ju¿ nigdy nie zobacz±. Bo zaraz po pierwszym wybuchu rozleg³ siê drugi. Potê¿na pomarañczowa ³una o¶wietli³a widmowym blaskiem konwój i ca³e niebo nad konwojem. Pod takim ciosem ka¿dy statek, obojêtne - ma³y czy du¿y, musia³ natychmiast rozlecieæ siê w drzazgi. Wyrzucone w powietrze szcz±tki statku z pluskiem spada³y znów do morza w promieniu pó³ mili od miejsca eksplozji.
');
INSERT INTO texts (name, text) VALUES ('tekst30.txt', '
Atakuj±cy samolot lecia³ nisko nad ¶rodkiem konwoju, ¶cigany i smagany ogniem dzia³ przeciwlotniczych z kilkudziesiêciu statków równocze¶nie. Samolotu nie by³o widaæ, lecz jego drogê znaczy³y p³on±ce wstêgi pocisków ¶wietlnych, rozwijaj±ce siê w olbrzymi wachlarz nad czo³em konwoju. Powsta³ straszliwy zgie³k - warkot samolotu dr±¿y³ ciemno¶æ, hucza³y setki dzia³ naraz, na kilku statkach rycza³y syreny alarmowe. Prawdziwym piek³em musia³ byæ ¶rodek konwoju, gdzie ze wszystkich statków prano w nisko lec±cy samolot, nie troszcz±c siê o to, co znajdzie siê na linii celu. Stali na rufie, tu¿ nad wod± umykaj±c± wartkim strumieniem spod ¶ruby, i patrzyli, czekali, usi³owali przewidzieæ, w któr± stronê poleci samolot po skoñczonym ataku. Nad nimi, na platformie 47-milimetrowego dzia³a, marynarze z obs³ugi stali w he³mach na g³owie, nieruchomi na tle ciemnego nieba, gotowi do oddania strza³u, gdy przyjdzie ich kolej. Ale nie przysz³a ich kolej, gotowe do u¿ycia ta¶my pocisków nie zosta³y u¿yte.
');
INSERT INTO texts (name, text) VALUES ('tekst31.txt', '
Teoria narastaj±cych defektów opiera siê na innym za³o¿eniu - stopniowym zu¿ywaniu komórek, spowodowanym ci±g³ym przeprowadzaniem przez nie niezbêdnych do ¿ycia reakcji chemicznych, które powoli zatruwaj± ich mechanizmy. Mechanizmy obronne komórki po prostu po pewnym czasie siê wyczerpuj± i zaczyna ona siê starzeæ a¿ w koñcu umiera. Najbardziej prawdopodobn± przyczyn± tak szybkiego zu¿ywania siê komórek s± tzw. wolne rodniki, grupa zwi±zków chemicznych, bêd±cych produktem ubocznym procesów przemian niektórych zwi±zków. Te zwi±zki chemiczne kiedy ju¿ zostan± uwolnione w komórce, uszkadzaj± cz±steczki niezbêdne do jej naprawy.
');
INSERT INTO texts (name, text) VALUES ('tekst32.txt', '
Do tej chwili wyk³ad Golema nie odbiega wiele od rewelacji wspó³czesnych genetyków, jest te¿, co ciekawe, zadziwiaj±co zbie¿ny z g³o¶n±, a powsta³± niezale¿nie i w zbli¿onym czasie ksi±¿k± Richarda Dawkinsa Samolubny gen. W±tek nowy pojawi siê w momencie, gdy Lem, g³osem komputera, pocznie dywagowaæ nad kwesti± uwik³ania Rozumu w drabinê ewoluuj±cych gatunków. Powie nam wówczas, ¿e Rozum nie tyle jest ukoronowaniem doskonal±cych siê funkcji organicznych, ile ko³em ratowniczym rzuconym zdefektowanym, niedoskona³ym w³a¶nie, produktom pó¼nych etapów biologicznej kreacji.
');
INSERT INTO texts (name, text) VALUES ('tekst33.txt', '
Ju¿ chcia³em skierowaæ siê na powrót w bezmiar przestrzeni, gdy dostrzeg³em, ¿e jaka¶ malutka postaæ daje mi z do³u znaki. Zamkn±wszy silnik, splanowa³em szybko i osadzi³em wehiku³ w pobli¿u grupy malowniczych ska³, na których wznosi³ siê spory budynek z ciosanego kamienia. Na moje spotkanie bieg³ polem ros³y starzec w bia³ym habicie dominikanina. By³ to, jak siê okaza³o, ojciec Lacymon, prze³o¿ony wszystkich misji dzia³aj±cych na obszarach pobliskich gwiazdozbiorów w promieniu sze¶ciuset lat ¶wietlnych. Okolica ta liczy oko³o piêciu milionów planet, w tym dwa miliony czterysta tysiêcy zamieszkanych. Ojciec Lacymon, dowiedziawszy siê o przyczynie, która sprowadzi³a mnie w te strony, wyrazi³ wspó³czucie, zarazem za¶ rado¶æ z mego przybycia, bo jak mi rzek³, jestem pierwszym cz³owiekiem, jakiego widzi od siedmiu miesiêcy.
');
INSERT INTO texts (name, text) VALUES ('tekst34.txt', '
Pytanie, które zosta³o pomy¶lane nie doczeka³o siê pomy¶lnej odpowiedzi, a to zaowocowa³o podejrzeniem w stosunku do le¿±cego przede mn± kalafiora. Postanowi³em rozkroiæ go na pó³ aby przyjrzeæ siê mu od ¶rodka. Tak te¿ zrobi³em. W ¶rodku kalafiora by³... najzwyklejszy ¶rodek kalafiora, nic szczególnego. Znaczy³o to zapewne, ¿e ten kalafior by³ najzupe³niej zdrowy - przynajmniej od ¶rodka. No to sekcja ugotowanego kalafiora zrobiona, ale co to za czarne ma³e drobinki?? Czy to aby jest normalne u takiego ugotowanego kalafiora? Przed skonsumowaniem tej ro¶liny postanowi³em zaistnia³± sytuacjê zbadaæ osobi¶cie.
');
INSERT INTO texts (name, text) VALUES ('tekst35.txt', '
Otó¿ pisarz to w gruncie rzeczy ¶winia. Ostatni cham. Nie, to zbyt ³agodne okre¶lenia. To kat. Morderca. Spójrzcie - tworzy ¶wiaty, zapala s³oñca, ziszcza ludzi - zupe³nie jak Pan Bóg. Tylko, ¿e on je potem niszczy. Pomy¶lcie, ile ksi±¿ek nie powsta³o dla jednego opowiadania, ile¿ dzie³ zosta³o zamordowanych w zarodku, by mog³o powstaæ jedno. To ju¿ znamy, gdzie¶ zapewne s³yszeli¶my. Ale to nie jest jeszcze najgorsze. Mo¿na to z³o¿yæ na karby po¶wiêcenia, musi zgin±æ jeden, by móg³ ¿yæ inny, nie ma tutaj mowy o ¿adnej niehumanitarno¶ci. Lecz czy nie pomy¶leli¶cie nigdy, ¿e pisarz mo¿e sobie tworzyæ ¶wiaty dla samej zabawy i potem je sobie obserwowaæ, a¿ sczezn± - z jego winy.
');
INSERT INTO texts (name, text) VALUES ('tekst36.txt', '
Klawiatura to taka wspania³a, przydatna i wygodna rzecz. Dlaczego w takim razie, siedz±c przed ni± kilka godzin, nie jestem w stanie napisaæ ani jednego sensownego zdania? Zlecenie jest, termin oddania te¿, wiem nawet, jakie bêdzie honorarium. Nie bêdzie zbyt wysokie, ale zawsze co¶. Zreszt± nie piszê dla zarobku. Robiê to tylko dlatego, ¿e lubiê. Mimo wszystko, tylko siedzê i patrzê w okno. Szukam pomys³ów, gdzie tylko mogê. Patrzê na deszcz, widzê jak jego krople bardzo powoli sp³ywaj± po szybie. £±cz± siê z innymi i odp³ywaj± dalej, w tylko sobie znanym kierunku. Przypomina to trochê ludzkie ¿ycie. To znaczy, te krople deszczu, one s± jak ludzie.
');
INSERT INTO texts (name, text) VALUES ('tekst37.txt', '
By³ przeciêtn± m³od± osob±, chodzi³ do przeciêtnej szko³y ¶redniej, przeciêtnie siê uczy³, przeciêtnie wygl±da³. ¯y³ w przeciêtno¶ci i razem z ni±. Nic nie m±ci³o mu spokoju, mia³ swoje ¿ycie, ze zwyk³ymi problemami. Wiedzia³, ¿e jest jak wszyscy, ale wcale mu to nie przeszkadza³o. Nie lubi³ siê wyró¿niaæ, to mog³o przynie¶æ wy³±cznie k³opoty. Mia³ kolegów i kole¿anki, normaln± rodzinê, dobre widoki na przysz³o¶æ. Lubi³ ogl±daæ telewizjê, graæ na komputerze. Robili to przecie¿ wszyscy. Czu³ siê bezpiecznie. S±dzi³, ¿e trudno o lepsze szczê¶cie. Myli³ siê.
');
